// DevOps board data — auto-synced from Jira project TD (Trastbank devops)
// Last sync: 2026-06-23
// Format: [key, summary, status, type, assignee, created, priority]
window.DEVOPS_ISSUES = [
["TD-286","ДБО: DBO in domein ga fp-gateway servisini ulab berish kerak","TO DO","История","Ikhtiyar Abdukhashimov","2026-06-23","Medium"],
["TD-285","(pg rech tech) 172.16.103.17/18 shu ikkta serverdan iabs serverlariga 172.16.101.115 host va 1521 portiga connection ochish kerak","Проверка","История","Mashkurov Azamat","2026-06-22","Medium"],
["TD-284","need to put the .JAR file to the needed destination and make a restart the loader first then bmms and need to see the logs how it works .","DONE","История","Ikhtiyar Abdukhashimov","2026-06-19","Medium"],
["TD-283","BMMS > jarka qo'yish kerak","DONE","История","Mustonov Ilyos","2026-06-19","Medium"],
["TD-282","ДБО: ДБО ни dump ни олиб бериш","TO DO","История","Mashkurov Azamat","2026-06-19","Medium"],
["TD-281","ДБО: https://192.168.18.228 wi-fi доступ Алмаз","TO DO","История","Mashkurov Azamat","2026-06-19","Medium"],
["TD-280","ДБО: Нужно дать доступ до https://repo.packagist.org","TO DO","История","Mashkurov Azamat","2026-06-18","Medium"],
["TD-279","ДБО: При работе с GitLab возникает ошибка","DONE","История","Mashkurov Azamat","2026-06-18","Medium"],
["TD-278","BMMS > jarka qo'yish kerak","DONE","История","Mustonov Ilyos","2026-06-18","Medium"],
["TD-277","ДБО ни DUMPни олиш Сервердаги accessable path га койиб бериш","DONE","История","Yaxyo Sunnatov","2026-06-18","Medium"],
["TD-276","deploy trastpay-transactions-perform-service","DONE","История","Ikhtiyar Abdukhashimov","2026-06-16","Medium"],
["TD-275","deploy Trastpay-payment-api","DONE","История","Ikhtiyar Abdukhashimov","2026-06-16","Medium"],
["TD-274","Trastpay > BMMS > Yaml update qilish kerak","DONE","История","Ikhtiyar Abdukhashimov","2026-06-16","Medium"],
["TD-273","ДБО: [Groub-IB] Проверить и восстановить проксирование /api/fl/ в Nginx на af-backend.trustpay.uz/api/fl","DONE","История","Yaxyo Sunnatov","2026-06-16","Medium"],
["TD-272","Yangi Postgres serverlar uchun Ixtiyor Abduxoshimov Yaxyo Sunnatovlarni PAMiga qoshib berishingizni soraymiz","DONE","История","Mustonov Ilyos","2026-06-16","Medium"],
["TD-268","ДБО: Необходимо систематизировать сбор логов","DONE","История","Yaxyo Sunnatov","2026-06-15","Medium"],
["TD-267","BMMS > qr oplata > purpose code o'zgartirish kerak","DONE","История","Ikhtiyar Abdukhashimov","2026-06-15","Medium"],
["TD-266","X-GO: Настройка сетевого доступа к сервисам Uzcard/Humo для OTP-верификации карт","DONE","Задача","Mashkurov Azamat","2026-06-15","High"],
["TD-265","2 TB dan har bitta gnodelarga qoshilgan deco projectida shuni sys adminlarga safe qilib qaytarish","DONE","История","Ikhtiyar Abdukhashimov","2026-06-15","Medium"],
["TD-264","Trastpay: Mastercard uchun JAR ka update va bmms.yaml config update qilish","DONE","История","Ikhtiyar Abdukhashimov","2026-06-15","Medium"],
["TD-263","Deploy payment api exp","DONE","История","Ikhtiyar Abdukhashimov","2026-06-12","Medium"],
["TD-262","MINIO 172.16.101.1 serverga joy qoshish kk Sababi Mongo db dumplarini saqlamoqchimiza ( Trastpayni dumplarini )","Selected for Development","История","Mashkurov Azamat","2026-06-11","Highest"],
["TD-261","AI Chat Serverga dostup ochish kerak","DONE","История","Mustonov Ilyos","2026-06-11","Medium"],
["TD-260","MuamalatPay: Telekom AF ni agentini production serverdan alohida serverga ko'chirish kerak","DONE","История","Mashkurov Azamat","2026-06-11","Medium"],
["TD-259","3 ta server Postrges Cluster uchun 4 CPU 8 RAM 2TB /data ga mount qilish kere 3 ta server yozilgan harakteristikada bolish kerak.","DONE","История","Mashkurov Azamat","2026-06-11","Medium"],
["TD-258","k8s mongodb (172.27.1.12 , 172.27.1.13 ) ga internet 15 daqiqaga yoqish va shu serverlardan 172.16.101.1 9000 va 9001 portga connection ochish","DONE","История","Mashkurov Azamat","2026-06-10","Medium"],
["TD-257","MONGO DB DUMP olishni optimiize qilish va dumplarni Minioga saqlash","Проверка","История","Ikhtiyar Abdukhashimov","2026-06-10","Medium"],
["TD-256","FCI: Food city проектини ни ограниченный IP адресларида очадиган килиш","Selected for Development","Задача","Mashkurov Azamat","2026-06-10","Medium"],
["TD-255","ДБО: Доступ в Sentry","Selected for Development","Задача","Mashkurov Azamat","2026-06-10","Medium"],
["TD-254","ДБО: Нужно в env установить (Павел)","DONE","Задача","Ikhtiyar Abdukhashimov","2026-06-10","Medium"],
["TD-253","ДБО: микросервисс bank в воркере statement.export периодически падает(Алмаз)","DONE","Задача","Ikhtiyar Abdukhashimov","2026-06-10","Medium"],
["TD-252","Optimizing Taking Dump with help of MONGO db for TRASTPAY","DONE","История","Ikhtiyar Abdukhashimov","2026-06-09","Medium"],
["TD-251","fix auto deploy in client-api exp","DONE","История","Ikhtiyar Abdukhashimov","2026-06-09","Medium"],
["TD-250","Открытие доступа для интеграции Bill Master","Проверка","Задача","Mashkurov Azamat","2026-06-08","Medium"],
["TD-249","Muamalatpay: Humo Payment va Humo Middleware login nomlarini bilib berish","DONE","История","Yaxyo Sunnatov","2026-06-08","Medium"],
["TD-248","Bill Master (172.20.21.2) дан Food City (172.16.102.85) 3000 портга connection очиш кере","DONE","История","Mashkurov Azamat","2026-06-08","Medium"],
["TD-247","DECO. Masofaviy tizimga kira olish huquqini ochish kerak.","Проверка","История","Mustonov Ilyos","2026-06-08","Medium"],
["TD-246","fix auto deploy in client-api exp","DONE","История","Yaxyo Sunnatov","2026-06-08","Medium"],
["TD-245","deploy client-api prod","DONE","История","Ikhtiyar Abdukhashimov","2026-06-08","Medium"],
["TD-244","adding new variables to .env in client-api","DONE","История","Ikhtiyar Abdukhashimov","2026-06-08","Medium"],
["TD-243","Payment Hub Server Experimantal va production ochish kere","Проверка","История","Mashkurov Azamat","2026-06-08","Medium"],
["TD-242","Ошибка 404 NOT_FOUND при вызове методов Agent Check и Agent Pay","DONE","Баг","Ikhtiyar Abdukhashimov","2026-06-08","Highest"],
["TD-241","ДБО: Установить переменные для файлового хранилища","DONE","История","Yaxyo Sunnatov","2026-06-05","Medium"],
["TD-239","DECO. 192.168.254.6 ga Abduxoshimov Ixtiyor akaga dostup ochish kerak.","DONE","История","Mashkurov Azamat","2026-06-04","Medium"],
["TD-238","FCI: Pipeline да хатоли бервотти","DONE","История","Yaxyo Sunnatov","2026-06-03","Medium"],
["TD-237","DECO. Serverga sql querylartni qo'yish kerak","DONE","История","Ikhtiyar Abdukhashimov","2026-06-03","Medium"],
["TD-236","DECO. 192.168.254.7 serveridan fayllarni olib berish kerak","DONE","История","Ikhtiyar Abdukhashimov","2026-06-03","Medium"],
["TD-235","MuamalatPay: Rabbitmq serveridan Muamalat serverlariga dostup ochish kerak","DONE","История","Mashkurov Azamat","2026-06-02","Medium"],
["TD-234","ДБО: Не удается выполнить сборку проекта bank в GitLab","DONE","История","Yaxyo Sunnatov","2026-06-02","Medium"],
["TD-233","trastpay-admin-front master dagi ohirgi ozgarishlani prodga deploy","DONE","История","Yaxyo Sunnatov","2026-06-02","Medium"],
["TD-232","ДБО: Не удаётся установить Composer-пакеты с сервера, ошибка SSL certificate problem (curl error 60)","DONE","История","Mashkurov Azamat","2026-06-02","Medium"],
["TD-231","ДБО: В микросервисе references настроить доступ к папке","DONE","История","Yaxyo Sunnatov","2026-06-02","Medium"],
["TD-230","ДБО: Проверить для очередей notifications","DONE","История","Yaxyo Sunnatov","2026-06-02","Medium"],
["TD-229","ДБО: В микросервисе notifications, добавить отельный deployment для слушателя rabbit","DONE","История","Yaxyo Sunnatov","2026-06-01","Medium"],
["TD-228","DECO. Klasterni tiklash uchun gnode1/gnode2 serverlarida disk va RAM resurslarini oshirish","DONE","История","Mashkurov Azamat","2026-06-01","Medium"],
["TD-227","ДБО: Необходимо развернуть сервис Loki для хранения логов","DONE","История","Ikhtiyar Abdukhashimov","2026-06-01","Medium"],
["TD-226","Create user in Grafana for backend developer [Dony]","DONE","История","Yaxyo Sunnatov","2026-06-01","Medium"],
["TD-225","Chat Bot AI project Ubuntu Server 4 cpu 16 ram, SSD 80 GB","DONE","Задача","Mashkurov Azamat","2026-06-01","Medium"],
["TD-224","Logging service deploy qilindi va domenni service ga qaratib berish kerak.","IN PROGRESS","История","Mashkurov Azamat","2026-06-01","Medium"],
["TD-223","FCI: 172.16.102.85 dan 172.20.21.2 va 172.20.21.5 8080 portiga connection килиб беришиззи сориман","DONE","История","Mashkurov Azamat","2026-05-26","Medium"],
["TD-222","ДБО: Проверка и запуск pipeline для sms-gateway","DONE","История","Yaxyo Sunnatov","2026-05-25","Medium"],
["TD-221","ДБО: Нужно открыть доступ для a.davranbekov к grafana и promiteus","DONE","История","Ikhtiyar Abdukhashimov","2026-05-25","Medium"],
["TD-220","Logging Service for Middleware","DONE","История","Yaxyo Sunnatov","2026-05-25","Medium"],
["TD-219","Food city: Prod, exp serverlariga env qo'shish kerak","DONE","История","Ikhtiyar Abdukhashimov","2026-05-25","Medium"],
["TD-218","ofdms-prod.ymldan","DONE","История","Ikhtiyar Abdukhashimov","2026-05-25","Medium"],
["TD-217","MuamalatPay Rabbit MQ nastroyka qilish kerak","DONE","История","Yaxyo Sunnatov","2026-05-25","Medium"],
["TD-216","MuamalatPay dan Groub-IB ni RabbitMQ siga dostup kerak va MuamalatPay da nastroyka qilish kerak.","DONE","История","Yaxyo Sunnatov","2026-05-25","Medium"],
["TD-215","docs-api ga file-stronge-service ulash","DONE","Задача","Yaxyo Sunnatov","2026-05-25","Medium"],
["TD-214","Soliqni ip adresini middleware env ga qo'shish kerak","DONE","История","Yaxyo Sunnatov","2026-05-25","Medium"],
["TD-213","Dostup ochish kere Trastpay-docs dan Minio ga","DONE","История","Yaxyo Sunnatov","2026-05-25","Medium"],
["TD-212","ДБО: Бэкендан Group-IB аписига доступ бор йоклигини текшириш керак","DONE","История","Yaxyo Sunnatov","2026-05-25","Medium"],
["TD-211","ДБО: Выяснить и исправить","DONE","История","Ikhtiyar Abdukhashimov","2026-05-25","Medium"],
["TD-210","ДБО: получить env переменные","DONE","История","Ikhtiyar Abdukhashimov","2026-05-25","Medium"],
["TD-209","ДБО: в микросервисе Notification","DONE","История","Ikhtiyar Abdukhashimov","2026-05-25","Medium"],
["TD-208","ДБО: 192.168.18.199 локальный доступ","DONE","История","Mashkurov Azamat","2026-05-22","Medium"],
["TD-207","ДБО: не получается в микросервисе profiles запустить билд","DONE","История","Yaxyo Sunnatov","2026-05-21","Medium"],
["TD-206","ДБО: Pipeline падает в микросервисе notifications","DONE","История","Yaxyo Sunnatov","2026-05-21","Medium"],
["TD-205","ДБО: Архитектурасини тузиб чикиш","DONE","История","Ikhtiyar Abdukhashimov","2026-05-21","Medium"],
["TD-204","ДБО: SDK→ mTLS Proxy га запрос юворвотканда 502 хато кайтарвотти","IN PROGRESS","История","Mashkurov Azamat","2026-05-20","Medium"],
["TD-203","Trastpay-admin-api-exp ga rasm yuklaganda error bervotti: 413 Request Entity Too Large.","DONE","История","Mashkurov Azamat","2026-05-20","Medium"],
["TD-202","BM серверида ofdms сервиси нечинчи портда ишлаб турганини толик url кере","DONE","История","Yaxyo Sunnatov","2026-05-19","Medium"],
["TD-201","ДБО: api.trustbank.uz curl вызов клиш кере","DONE","История","Yaxyo Sunnatov","2026-05-19","Medium"],
["TD-200","ДБО: Group IB серверидан бизани Бэкенд серверга доступ кбериш кере","DONE","История","Mashkurov Azamat","2026-05-19","Medium"],
["TD-199","Food city учун dev server котариш кере","DONE","История","Yaxyo Sunnatov","2026-05-19","Medium"],
["TD-198","Mtls proxy uchun dostup","DONE","История","Mashkurov Azamat","2026-05-19","Medium"],
["TD-197","Trastpay: Visa direct request tekshirish","DONE","История","Ikhtiyar Abdukhashimov","2026-05-19","Medium"],
["TD-196","MuamalatPay: https://git.trustbank.uz/chontakpay/pay-api/-/jobs/13256 da joblar yiqilishi kuzatilyapti","DONE","История","Yaxyo Sunnatov","2026-05-18","Medium"],
["TD-195","ДБО: Mtls proxy","DONE","История","Mashkurov Azamat","2026-05-12","Medium"],
["TD-190","Hashicorp сервис котариш","DONE","История","Yaxyo Sunnatov","2026-05-12","Medium"],
["TD-189","BitWarden ko'tarish kere login parollar saqlash uchun","DONE","История","Yaxyo Sunnatov","2026-05-07","Medium"],
["TD-188","Trastpay: fix the env variables","DONE","История","Yaxyo Sunnatov","2026-05-06","Medium"],
["TD-187","ДБО: rabbitevents:listen middleware.transaction.finished по какой то причине перестал обрабатываться","DONE","История","Yaxyo Sunnatov","2026-05-06","Medium"],
["TD-186","Trastpay: connection","DONE","История","Yaxyo Sunnatov","2026-05-06","Medium"],
["TD-185","fix the env variables","DONE","История","Ikhtiyar Abdukhashimov","2026-05-06","Medium"],
["TD-184","DWH Segment 6 dagi tizim indekslarida hatolik","DONE","История","Ikhtiyar Abdukhashimov","2026-05-06","Medium"],
["TD-183","BMMS mini change. 22216 -> 22616","DONE","История","Yaxyo Sunnatov","2026-05-05","Medium"],
["TD-182","Transaction time noto'g'ri ko'rsatilmoqda","DONE","История","Yaxyo Sunnatov","2026-05-05","Medium"],
["TD-181","Trastpay: update env trastpay-client-api-exp","DONE","История","Ikhtiyar Abdukhashimov","2026-05-05","Medium"],
["TD-180","DECO 192.168.254.9:5432 dan 192.168.254.9:6002 ga connection bo'lmayapti","DONE","История","Yaxyo Sunnatov","2026-05-04","Medium"],
["TD-179","dostuplarni hal qilish","DONE","Подзадача","Yaxyo Sunnatov","2026-05-04","Medium"]
];

// Jira project URL base for TD project
window.DEVOPS_JIRA_BASE = "https://test-tb.atlassian.net";
