// Last sync: 2026-06-29
window.DEVOPS_ISSUES = [
  ["TD-308", "отправить прямой запрос ", "DONE", "Задача", "Abduxoshimov Ixtiyor", "2026-06-29", "Medium"],
  ["TD-307", "Trastpay Docs Frontend va backend togri connection ololmayapti", "Selected for Development", "Баг", "Abduxoshimov Ixtiyor", "2026-06-29", "Medium"],
  ["TD-306", "192.168.18.205 (компьютер) дан Трастпэй базасига доступ очип коган", "TO DO", "История", "Mashkurov Azamat", "2026-06-29", "Medium"],
  ["TD-305", "PROD deploy trastpay-monitoring-api trastpay-admin-api trastpay-card-api", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-06-29", "Medium"],
  ["TD-304", "ABS: Jira va boshqa saytlarga dostup berilishi kerak", "TO DO", "История", "Mashkurov Azamat", "2026-06-29", "Medium"],
  ["TD-303", "MuamalatPay:  php user /srv/project/pay-api/storage/logs/*.log filega yozish uchun dostup kerak", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-06-29", "Medium"],
  ["TD-302", "BMMS > jarka qo'yish kerak", "Проверка", "История", "Mustonov Ilyos", "2026-06-26", "Medium"],
  ["TD-301", "Trastpay > BMMS > Yaml update qilish kerak", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-06-26", "Medium"],
  ["TD-300", "ДБО: не проходит билд в микросервисе petitions", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-06-26", "Medium"],
  ["TD-299", "ДБО: на фронте деплой перестал работать", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-06-26", "Medium"],
  ["TD-298", "ДБО: Сделать curl запрос из микросервиса middlware", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-06-26", "Medium"],
  ["TD-297", "ДБО: api.trustbank.uz/fpgateway/ zapros yuborilganda 502 Bad Gateway qaytvoti", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-06-26", "Medium"],
  ["TD-296", "Trastpay > QR code > BMMS jarka yuklash", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-06-25", "Medium"],
  ["TD-295", "DECO: Kompyerga dostuplarni ochib berish kerak.", "TO DO", "История", "Mashkurov Azamat", "2026-06-25", "Medium"],
  ["TD-294", "Chatbot AI uchun yengi domen yaratib berish kerak", "IN PROGRESS", "История", "Mashkurov Azamat", "2026-06-25", "Medium"],
  ["TD-293", "DBO-V2 uchun yangi server ochish kerak.", "Selected for Development", "История", "Mashkurov Azamat", "2026-06-25", "Medium"],
  ["TD-292", "Trastpay > BMMS > Yaml update qilish kerak", "DONE", "История", "Sunnatov Yaxyo", "2026-06-24", "Medium"],
  ["TD-291", "BMMS jarka qo'yish. QR oplata", "DONE", "История", "Mustonov Ilyos", "2026-06-24", "Medium"],
  ["TD-290", "Trastpay: OFB product API credentials-ni latest change-larga uzgartirish", "DONE", "Баг", "Abduxoshimov Ixtiyor", "2026-06-24", "Medium"],
  ["TD-289", "PG REG TECH uchun Postgres Cluster kotarish", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-06-24", "Medium"],
  ["TD-288", "DECO: DBeaver databazasida 192.168.254.7:5432 portga connection yo'q.", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-06-24", "Medium"],
  ["TD-287", "FCI: Foot city базани хафталик backup олиш кере", "DONE", "Задача", "Abduxoshimov Ixtiyor", "2026-06-23", "Medium"],
  ["TD-286", "ДБО: DBO in domein ga fp-gateway servisini ulab berish kerak", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-06-23", "Medium"],
  ["TD-285", "(pg rech tech) 172.16.103.17/18 shu ikkta serverdan iabs serverlariga 172.16.101.115 host va 1521 portiga connection ochish kerak", "DONE", "История", "Mashkurov Azamat", "2026-06-22", "Medium"],
  ["TD-284", "need to put the .JAR file to the needed destination and make a restart the loader first then bmms and need to see the logs how it works .", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-06-19", "Medium"],
  ["TD-283", "BMMS > jarka qo'yish kerak", "DONE", "История", "Mustonov Ilyos", "2026-06-19", "Medium"],
  ["TD-282", "ДБО: ДБО ни dump ни олиб бериш", "DONE", "История", "Sunnatov Yaxyo", "2026-06-19", "Medium"],
  ["TD-281", "ДБО: https://192.168.18.228 wi-fi доступ Алмаз", "Проверка", "История", "Mashkurov Azamat", "2026-06-19", "Medium"],
  ["TD-280", "ДБО: Нужно дать доступ до https://repo.packagist.org", "Проверка", "История", "Mashkurov Azamat", "2026-06-18", "Medium"],
  ["TD-279", "ДБО: При работе с GitLab возникает ошибка", "DONE", "История", "Mashkurov Azamat", "2026-06-18", "Medium"],
  ["TD-278", "BMMS > jarka qo'yish kerak", "DONE", "История", "Mustonov Ilyos", "2026-06-18", "Medium"],
  ["TD-277", "ДБО ни DUMPни олиш Сервердаги accessable path га койиб бериш", "DONE", "История", "Sunnatov Yaxyo", "2026-06-18", "Medium"],
  ["TD-276", "deploy trastpay-transactions-perform-service", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-06-16", "Medium"],
  ["TD-275", "deploy Trastpay-payment-api", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-06-16", "Medium"],
  ["TD-274", "Trastpay > BMMS > Yaml update qilish kerak", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-06-16", "Medium"],
  ["TD-273", "ДБО: [Groub-IB] Проверить и восстановить проксирование /api/fl/ в Nginx на af-backend.trustpay.uz/api/fl", "DONE", "История", "Sunnatov Yaxyo", "2026-06-16", "Medium"],
  ["TD-272", "Yangi Postgres serverlar uchun Ixtiyor Abduxoshimov Yaxyo Sunnatovlarni PAMiga qoshib berishingizni soraymiz", "DONE", "История", "Mustonov Ilyos", "2026-06-16", "Medium"],
  ["TD-268", "ДБО: Необходимо систематизировать сбор логов", "DONE", "История", "Sunnatov Yaxyo", "2026-06-15", "Medium"],
  ["TD-267", "BMMS > qr oplata > purpose code o'zgartirish kerak", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-06-15", "Medium"],
  ["TD-266", "X-GO: Настройка сетевого доступа к сервисам Uzcard/Humo для OTP-верификации карт", "DONE", "Задача", "Mashkurov Azamat", "2026-06-15", "High"],
  ["TD-265", "2 TB dan har bitta gnodelarga qoshilgan deco projectida shuni sys adminlarga safe qilib qaytarish", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-06-15", "Medium"],
  ["TD-264", "Trastpay: Mastercard uchun JAR ka update va bmms.yaml config update qilish", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-06-15", "Medium"],
  ["TD-263", "Deploy payment api exp", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-06-12", "Medium"],
  ["TD-262", "MINIO 172.16.101.1 serverga joy qoshish kk Sababi Mongo db dumplarini saqlamoqchimiza ( Trastpayni dumplarini )", "Selected for Development", "История", "Mashkurov Azamat", "2026-06-11", "Highest"],
  ["TD-261", "AI Chat Serverga dostup ochish kerak", "DONE", "История", "Mustonov Ilyos", "2026-06-11", "Medium"],
  ["TD-260", "MuamalatPay: Telekom AF ni agentini production serverdan alohida serverga ko'chirish kerak", "DONE", "История", "Mashkurov Azamat", "2026-06-11", "Medium"],
  ["TD-259", "3 ta server Postrges Cluster uchun 4 CPU 8 RAM 2TB /data ga mount qilish kere 3 ta server yozilgan harakteristikada bolish kerak.", "DONE", "История", "Mashkurov Azamat", "2026-06-11", "Medium"],
  ["TD-258", "k8s mongodb (172.27.1.12 , 172.27.1.13 ) ga internet 15 daqiqaga yoqish va shu serverlardan 172.16.101.1 9000 va 9001 portga connection ochish", "DONE", "История", "Mashkurov Azamat", "2026-06-10", "Medium"],
  ["TD-257", "MONGO DB DUMP olishni optimiize qilish va dumplarni Minioga saqlash", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-06-10", "Medium"],
  ["TD-256", "FCI: Food city проектини ни ограниченный IP адресларида очадиган килиш", "Selected for Development", "Задача", "Mashkurov Azamat", "2026-06-10", "Medium"],
  ["TD-255", "ДБО: Доступ в Sentry", "Selected for Development", "Задача", "Mashkurov Azamat", "2026-06-10", "Medium"],
  ["TD-254", "ДБО: Нужно в env установить (Павел)", "DONE", "Задача", "Abduxoshimov Ixtiyor", "2026-06-10", "Medium"],
  ["TD-253", "ДБО: микросервисс bank в воркере statement.export периодически падает(Алмаз)", "DONE", "Задача", "Abduxoshimov Ixtiyor", "2026-06-10", "Medium"],
  ["TD-252", "Optimizing Taking Dump with help of MONGO db for TRASTPAY", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-06-09", "Medium"],
  ["TD-251", "fix auto deploy in client-api exp", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-06-09", "Medium"],
  ["TD-250", "Открытие доступа для интеграции Bill Master", "Проверка", "Задача", "Mashkurov Azamat", "2026-06-08", "Medium"],
  ["TD-249", "Muamalatpay: Humo Payment va Humo Middleware login nomlarini bilib berish", "DONE", "История", "Sunnatov Yaxyo", "2026-06-08", "Medium"],
  ["TD-248", "Bill Master (172.20.21.2) дан Food City (172.16.102.85) 3000 портга connection очиш кере", "DONE", "История", "Mashkurov Azamat", "2026-06-08", "Medium"],
  ["TD-247", "DECO. Masofaviy tizimga kira olish huquqini ochish kerak.", "Проверка", "История", "Mustonov Ilyos", "2026-06-08", "Medium"],
  ["TD-246", "fix auto deploy in client-api exp", "DONE", "История", "Sunnatov Yaxyo", "2026-06-08", "Medium"],
  ["TD-245", "deploy client-api prod", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-06-08", "Medium"],
  ["TD-244", "adding new variables to .env in client-api", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-06-08", "Medium"],
  ["TD-243", "Payment Hub Server Experimantal va production ochish kere", "Проверка", "История", "Mashkurov Azamat", "2026-06-08", "Medium"],
  ["TD-242", "Ошибка 404 NOT_FOUND при вызове методов Agent Check и Agent Pay", "DONE", "Баг", "Abduxoshimov Ixtiyor", "2026-06-08", "Highest"],
  ["TD-241", "ДБО: Установить переменные для файлового хранилища", "DONE", "История", "Sunnatov Yaxyo", "2026-06-05", "Medium"],
  ["TD-239", "DECO. 192.168.254.6 ga Abduxoshimov Ixtiyor akaga dostup ochish kerak.", "DONE", "История", "Mashkurov Azamat", "2026-06-04", "Medium"],
  ["TD-238", "FCI: Pipeline да хатоли бервотти", "DONE", "История", "Sunnatov Yaxyo", "2026-06-03", "Medium"],
  ["TD-237", "DECO. Serverga sql querylartni qo'yish kerak", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-06-03", "Medium"],
  ["TD-236", "DECO. 192.168.254.7 serveridan fayllarni olib berish kerak", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-06-03", "Medium"],
  ["TD-235", "MuamalatPay: Rabbitmq serveridan Muamalat serverlariga dostup ochish kerak", "DONE", "История", "Mashkurov Azamat", "2026-06-02", "Medium"],
  ["TD-234", "ДБО: Не удается выполнить сборку проекта bank в GitLab", "DONE", "История", "Sunnatov Yaxyo", "2026-06-02", "Medium"],
  ["TD-233", "trastpay-admin-front master dagi ohirgi ozgarishlani prodga deploy", "DONE", "История", "Sunnatov Yaxyo", "2026-06-02", "Medium"],
  ["TD-232", "ДБО: Не удаётся установить Composer-пакеты с сервера, ошибка SSL certificate problem (curl error 60)", "DONE", "История", "Mashkurov Azamat", "2026-06-02", "Medium"],
  ["TD-231", "ДБО: В микросервисе references настроить доступ к папке", "DONE", "История", "Sunnatov Yaxyo", "2026-06-02", "Medium"],
  ["TD-230", "ДБО: Проверить для очередей notifications", "DONE", "История", "Sunnatov Yaxyo", "2026-06-02", "Medium"],
  ["TD-229", "ДБО: В микросервисе notifications, добавить отельный deployment для слушателя rabbit", "DONE", "История", "Sunnatov Yaxyo", "2026-06-01", "Medium"],
  ["TD-228", "DECO. Klasterni tiklash uchun gnode1/gnode2 serverlarida disk va RAM resurslarini oshirish", "DONE", "История", "Mashkurov Azamat", "2026-06-01", "Medium"],
  ["TD-227", "ДБО: Необходимо развернуть сервис Loki для хранения логов", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-06-01", "Medium"],
  ["TD-226", "Create user in Grafana for backend developer [Dony]", "DONE", "История", "Sunnatov Yaxyo", "2026-06-01", "Medium"],
  ["TD-225", "Chat Bot AI project Ubuntu Server 4 cpu 16 ram, SSD 80 GB", "DONE", "Задача", "Mashkurov Azamat", "2026-06-01", "Medium"],
  ["TD-224", "Logging service deploy qilindi va yengi domen qo'yib berish kerak.", "Проверка", "История", "Mashkurov Azamat", "2026-06-01", "Medium"],
  ["TD-223", "FCI: 172.16.102.85 dan 172.20.21.2 va 172.20.21.5 8080 portiga connection килиб беришиззи сориман", "DONE", "История", "Mashkurov Azamat", "2026-05-26", "Medium"],
  ["TD-222", "ДБО: Проверка и запуск pipeline для sms-gateway", "DONE", "История", "Sunnatov Yaxyo", "2026-05-25", "Medium"],
  ["TD-221", "ДБО: Нужно открыть доступ для a.davranbekov к grafana и promiteus", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-05-25", "Medium"],
  ["TD-220", "Logging Service for Middleware", "DONE", "История", "Sunnatov Yaxyo", "2026-05-25", "Medium"],
  ["TD-219", "Food city: Prod, exp serverlariga env qo'shish kerak", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-05-25", "Medium"],
  ["TD-218", "ofdms-prod.ymldan", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-05-25", "Medium"],
  ["TD-217", "MuamalatPay Rabbit MQ nastroyka qilish kerak", "DONE", "История", "Sunnatov Yaxyo", "2026-05-25", "Medium"],
  ["TD-216", "MuamalatPay dan Groub-IB ni  RabbitMQ siga dostup kerak va MuamalatPay da nastroyka qilish kerak.", "DONE", "История", "Sunnatov Yaxyo", "2026-05-25", "Medium"],
  ["TD-215", "docs-api ga file-stronge-service ulash ", "DONE", "Задача", "Sunnatov Yaxyo", "2026-05-25", "Medium"],
  ["TD-214", "Soliqni ip adresini middleware env ga qo'shish kerak", "DONE", "История", "Sunnatov Yaxyo", "2026-05-25", "Medium"],
  ["TD-213", "Dostup ochish kere Trastpay-docs dan Minio ga", "DONE", "История", "Sunnatov Yaxyo", "2026-05-25", "Medium"],
  ["TD-212", "ДБО: Бэкендан Group-IB аписига доступ бор йоклигини текшириш керак", "DONE", "История", "Sunnatov Yaxyo", "2026-05-25", "Medium"],
  ["TD-211", "ДБО: Выяснить и исправить", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-05-25", "Medium"],
  ["TD-210", "ДБО: получить env переменные", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-05-25", "Medium"],
  ["TD-209", "ДБО: в микросервисе Notification", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-05-25", "Medium"],
  ["TD-208", "ДБО: 192.168.18.199 локальный доступ", "DONE", "История", "Mashkurov Azamat", "2026-05-22", "Medium"],
  ["TD-207", "ДБО: не получается в микросервисе profiles запустить билд", "DONE", "История", "Sunnatov Yaxyo", "2026-05-21", "Medium"],
  ["TD-206", "ДБО: Pipeline падает в микросервисе notifications", "DONE", "История", "Sunnatov Yaxyo", "2026-05-21", "Medium"],
  ["TD-205", "ДБО: Архитектурасини тузиб чикиш", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-05-21", "Medium"],
  ["TD-204", "ДБО: SDK→ mTLS Proxy га запрос юворвотканда 502 хато кайтарвотти", "Проверка", "История", "Mashkurov Azamat", "2026-05-20", "Medium"],
  ["TD-203", "Trastpay-admin-api-exp ga rasm yuklaganda error bervotti: 413 Request Entity Too Large.", "DONE", "История", "Mashkurov Azamat", "2026-05-20", "Medium"],
  ["TD-202", "BM серверида ofdms сервиси нечинчи портда ишлаб турганини толик url кере", "DONE", "История", "Sunnatov Yaxyo", "2026-05-19", "Medium"],
  ["TD-201", "ДБО: api.trustbank.uz curl вызов клиш кере", "DONE", "История", "Sunnatov Yaxyo", "2026-05-19", "Medium"],
  ["TD-200", "ДБО: Group IB серверидан бизани Бэкенд серверга доступ кбериш кере", "DONE", "История", "Mashkurov Azamat", "2026-05-19", "Medium"],
  ["TD-199", "Food city учун dev server котариш кере", "DONE", "История", "Sunnatov Yaxyo", "2026-05-19", "Medium"],
  ["TD-198", "Mtls proxy uchun dostup", "DONE", "История", "Mashkurov Azamat", "2026-05-19", "Medium"],
  ["TD-197", "Trastpay: Visa direct request tekshirish", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-05-19", "Medium"],
  ["TD-196", "MuamalatPay: https://git.trustbank.uz/chontakpay/pay-api/-/jobs/13256 da joblar yiqilishi kuzatilyapti", "DONE", "История", "Sunnatov Yaxyo", "2026-05-18", "Medium"],
  ["TD-195", "ДБО: Mtls proxy ", "DONE", "История", "Mashkurov Azamat", "2026-05-12", "Medium"],
  ["TD-190", "Hashicorp сервис котариш", "DONE", "История", "Sunnatov Yaxyo", "2026-05-12", "Medium"],
  ["TD-189", "BitWarden ko'tarish kere login parollar saqlash uchun", "DONE", "История", "Sunnatov Yaxyo", "2026-05-07", "Medium"],
  ["TD-188", "Trastpay: fix the env variables", "DONE", "История", "Sunnatov Yaxyo", "2026-05-06", "Medium"],
  ["TD-187", "ДБО: rabbitevents:listen middleware.transaction.finished по какой то причине перестал обрабатываться", "DONE", "История", "Sunnatov Yaxyo", "2026-05-06", "Medium"],
  ["TD-186", "Trastpay: connection", "DONE", "История", "Sunnatov Yaxyo", "2026-05-06", "Medium"],
  ["TD-185", "fix the env variables", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-05-06", "Medium"],
  ["TD-184", "DWH Segment 6 dagi tizim indekslarida hatolik", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-05-06", "Medium"],
  ["TD-183", "BMMS mini change. 22216 -> 22616", "DONE", "История", "Sunnatov Yaxyo", "2026-05-05", "Medium"],
  ["TD-182", "Transaction time noto‘g‘ri ko‘rsatilmoqda", "DONE", "История", "Sunnatov Yaxyo", "2026-05-05", "Medium"],
  ["TD-181", "Trastpay: update env trastpay-client-api-exp", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-05-05", "Medium"],
  ["TD-180", "DECO 192.168.254.9:5432 dan 192.168.254.9:6002 ga connection bo'lmayapti", "DONE", "История", "Sunnatov Yaxyo", "2026-05-04", "Medium"],
  ["TD-179", "dostuplarni hal qilish", "DONE", "Подзадача", "Sunnatov Yaxyo", "2026-05-04", "Medium"],
  ["TD-178", "ecommerce billing serverda o'zgarish qilish", "DONE", "Подзадача", "Abduxoshimov Ixtiyor", "2026-05-04", "Medium"],
  ["TD-177", "ecommerce billing serverda o'zgarishlar qilish", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-05-04", "Medium"],
  ["TD-176", "middleware data-service uchun Redis create qilish kerak.", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-05-01", "Medium"],
  ["TD-175", "Nginx nastroyka qilish grafana uchun DBO proyektda.", "DONE", "История", "Sunnatov Yaxyo", "2026-05-01", "Medium"],
  ["TD-174", "Dataservice Api loyihasi uchun server ochish va unga  backend deploy qilish.", "DONE", "История", "Sunnatov Yaxyo", "2026-04-29", "Medium"],
  ["TD-173", "foodcity loyihasi uchun server ochish va unga frontend va backend deploy qilish experimental.", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-04-29", "Medium"],
  ["TD-171", "ДБО: Postgres Exporter", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-04-29", "Medium"],
  ["TD-170", "Abs token expire vaqtlarini 3540 sekundga almashtirish", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-04-29", "Medium"],
  ["TD-169", "Visa direct: BM serverida zapros jo'natib ko'rish", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-04-29", "Medium"],
  ["TD-168", "Доступ очиб бериш экоммерс сервис учун.", "DONE", "Задача", "Sunnatov Yaxyo", "2026-04-28", "Medium"],
  ["TD-167", "Открыть графана для БМ чтобы смотреть логи", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-04-28", "Medium"],
  ["TD-166", "получить полные логи  через Bmms", "DONE", "История", "Sunnatov Yaxyo", "2026-04-27", "Medium"],
  ["TD-165", "e-commerce-billing-api uchun grafana ulash kerak", "DONE", "История", "Sunnatov Yaxyo", "2026-04-27", "Medium"],
  ["TD-164", "192.168.254.8 ga space qo'shish kerak 300 GB ajratilgan keyin /data/segment4/primary/gpseg3/pg_xlog logni ko'rish kerak 500GB bo'lib ketganakan", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-04-27", "Medium"],
  ["TD-163", "Log lar bir necha bo'lib ko'rinyapti", "DONE", "История", "Sunnatov Yaxyo", "2026-04-27", "Medium"],
  ["TD-162", "Telecom exp da ishlamayapgan edi uni to'g'irlash", "DONE", "История", "Sunnatov Yaxyo", "2026-04-27", "Medium"],
  ["TD-161", "android update asset links.json", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-04-23", "Medium"],
  ["TD-160", "ДБО: Рэббит выдает ошибку", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-04-21", "Medium"],
  ["TD-159", "ДБО: В микросервисе bank (https://ibank-gitlab.trustbank.uz/multibank/back/bank)", "DONE", "История", "Sunnatov Yaxyo", "2026-04-17", "Medium"],
  ["TD-158", "ДБО: Для очередей bank.documents.sync", "DONE", "История", "Sunnatov Yaxyo", "2026-04-14", "Medium"],
  ["TD-157", "ДБО: Нужно в микросервисе middleware в env указать", "DONE", "История", "Sunnatov Yaxyo", "2026-04-14", "Medium"],
  ["TD-156", "В микросервисе notifications перевести job на deployment.", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-04-07", "Medium"],
  ["TD-155", "N8N: Настроит домен и доступы", "DONE", "История", "Sunnatov Yaxyo", "2026-04-01", "Medium"],
  ["TD-154", "e-commerce-billing-api prod and exper deployment", "DONE", "История", "Sunnatov Yaxyo", "2026-04-01", "Medium"],
  ["TD-153", "ДБО: Нужно выяснить объем database Trastbank Business со всеми данными в MB, и объем самого проекта который нужно что бы запустить проект в локалке", "DONE", "История", "Sunnatov Yaxyo", "2026-03-31", "Medium"],
  ["TD-152", "ДБО: Нужно получить response двух методов для проверки", "DONE", "История", "Sunnatov Yaxyo", "2026-03-31", "Medium"],
  ["TD-151", "Trastpay: deploy card-api", "DONE", "История", "Abduxoshimov Ixtiyor", "2026-03-30", "Medium"],
  ["TD-150", "Trastbank: Поднять сервис n8n внутри инфраструктуры банка", "DONE", "История", "Zokirov Bobur", "2026-03-25", "Блокер"],
  ["TD-149", "ДБО: Необходимо выяснить по какой причине воркеры не перезапускаются автоматически(Павел)", "DONE", "История", "Sunnatov Yaxyo", "2026-03-25", "Medium"],
  ["TD-148", "Visa direct: BMMS-prod ga shu sozlamalarni qoshish kerak", "DONE", "История", "Sunnatov Yaxyo", "2026-03-19", "High"],
  ["TD-147", "ДБО: В микросервисе profiles https://ibank-gitlab.trustbank.uz/multibank/back/profiles", "DONE", "История", "Sunnatov Yaxyo", "2026-03-19", "Medium"],
  ["TD-146", "ДБО: В микросервисе middleware https://ibank-gitlab.trustbank.uz/multicard-ws/middleware", "DONE", "История", "Sunnatov Yaxyo", "2026-03-19", "Medium"],
  ["TD-145", "trastpay-identification-api-exp da va trastpay-admin-api-exp NODE_ENV ikki xil emasmi. Qarab bera olasizmi", "DONE", "История", "Sunnatov Yaxyo", "2026-03-19", "Medium"],
  ["TD-144", "Upgrade BM with jar file", "DONE", "История", "Mirzabayev Damir", "2026-03-18", "Medium"],
  ["TD-143", "trastpay-client-api' ga dostup", "DONE", "История", "Sunnatov Yaxyo", "2026-03-17", "Medium"],
  ["TD-142", "trastpay-admin-front exp - deploy", "DONE", "История", "Sunnatov Yaxyo", "2026-03-17", "Medium"],
  ["TD-140", "ДБО: В микросервисе notifications перевести job на deployment. (Алмаз)", "DONE", "История", "Sunnatov Yaxyo", "2026-03-16", "Medium"],
  ["TD-139", "ДБО: Нужно установить переменные в микросервисе notifications(Алмаз)", "DONE", "История", "Sunnatov Yaxyo", "2026-03-16", "Medium"],
  ["TD-138", "ДБО: Переменные добавить в прод", "DONE", "История", "Sunnatov Yaxyo", "2026-03-16", "Medium"],
  ["TD-137", "MyID: experimentalda PROD API bilan tekshirib ko'rish uchun nastroyka qilib berish", "DONE", "История", "Sunnatov Yaxyo", "2026-03-12", "Medium"],
  ["TD-136", "ДБО: Сделать полную архитектуру ДБО", "DONE", "История", "Sunnatov Yaxyo", "2026-03-12", "Medium"],
  ["TD-134", "trastpay-client-api deploy qilish", "DONE", "История", "Sunnatov Yaxyo", "2026-03-11", "Medium"],
  ["TD-133", "ДБО: Доступ к База Данных (Паша)", "DONE", "История", "Sunnatov Yaxyo", "2026-03-11", "Medium"],
  ["TD-132", "CI/CD настройка сервера SUBSIDIYA.IDM", "DONE", "История", "Sunnatov Yaxyo", "2026-03-10", "Medium"],
  ["TD-131", "ДБО: в микросервисе notifications не билдится (Алмаз)", "DONE", "История", "Sunnatov Yaxyo", "2026-03-10", "Medium"],
  ["TD-130", "ДБО: Перезапустить жобы в микросервисе bank.", "DONE", "История", "Sunnatov Yaxyo", "2026-03-10", "Medium"],
  ["TD-129", "v-2 trastpay-project-docs  dagi oxirgi ozgarishni main ga deploy qilish kerak. ", "DONE", "История", "Sunnatov Yaxyo", "2026-03-06", "Medium"],
  ["TD-128", "trastpay-card-api deploy qilish kerak ", "DONE", "История", "Sunnatov Yaxyo", "2026-03-06", "Medium"],
  ["TD-127", "[ASAP] Trastpay proxy> tas-ix IP list update qilish (DeepLink issue with IOS)", "DONE", "История", "Sunnatov Yaxyo", "2026-03-06", "Блокер"],
  ["TD-126", "trastpay-identification-api dagi oxirigi o'zgarishni exp ga deploy qilish kerak", "DONE", "История", "Sunnatov Yaxyo", "2026-03-05", "Medium"],
  ["TD-125", "ДБО: Не отправляются запросы на middleware prod с локалки", "DONE", "История", "To'xtashev Asadbek", "2026-03-05", "Medium"],
  ["TD-123", "Middleware deploy exp and prod", "DONE", "История", "Sunnatov Yaxyo", "2026-03-05", "Medium"],
  ["TD-121", "ДБО: profiles и auth да хатолик бервотти", "DONE", "История", "Sunnatov Yaxyo", "2026-03-05", "Medium"],
  ["TD-120", "ДБО: umarov.ulugbek7869@gmail.com SENTRY га логин пароль ", "DONE", "История", "Sunnatov Yaxyo", "2026-03-05", "Medium"],
  ["TD-119", "ДБО: fp_gateway даги охирги озгаришларни тест ва продга деплой клиш кере", "DONE", "История", "Sunnatov Yaxyo", "2026-03-04", "Medium"],
  ["TD-118", "trastpay-project-docs staging dagi oxirigi o'zgarishni prod ga deploy qilish kerak", "DONE", "Задача", "Sunnatov Yaxyo", "2026-03-04", "Medium"],
  ["TD-117", "trastpay-admin-front dev dagi oxirigi o'zgarishni prod ga deploy qilish kerak", "DONE", "История", "Sunnatov Yaxyo", "2026-03-04", "Medium"],
  ["TD-116", "Trastbank Business DBO - DB qismini Deco (DWH) ga ulab berish yoki alohida baza qilib berish kerak, biz analiz qila olishimiz uchun", "DONE", "История", "Sunnatov Yaxyo", "2026-03-04", "Medium"],
  ["TD-114", "Trastpay DB qismini Deco (DWH) ga ulab berish yoki alohida baza qilib berish kerak, biz analiz qila olishimiz uchun", "DONE", "История", "Sunnatov Yaxyo", "2026-03-04", "Medium"],
  ["TD-113", "Rasm hajmi muammosi", "DONE", "История", "Zokirov Bobur", "2026-03-02", "Medium"],
  ["TD-112", "Prod subdomain nomini yangilash kerak", "DONE", "История", "Zokirov Bobur", "2026-03-02", "Medium"],
  ["TD-111", "MuamalatPay: Dev va Test serverdan curl -I https://fcm.googleapis.com ga dostup ochish", "DONE", "История", "Zokirov Bobur", "2026-02-25", "Medium"],
  ["TD-110", "MuamalatPay: ci/cd da permission yoq", "DONE", "История", "Sunnatov Yaxyo", "2026-02-25", "Medium"],
  ["TD-109", "trastpay-admin-front dev dagi oxirigi o'zgarishni prod ga deploy qilish kerak", "DONE", "История", "Sunnatov Yaxyo", "2026-02-23", "Medium"],
  ["TD-108", "trasttrastpay-project-docs frontend deploy to experimental and production", "DONE", "История", "Zokirov Bobur", "2026-01-19", "Medium"],
  ["TD-107", "trastpay-project-docs-api backend deploy to experimental and production server.", "DONE", "История", "Sunnatov Yaxyo", "2026-01-16", "Medium"],
  ["TD-106", "minio-file-storage PR 14", "DONE", "История", "Toxirov Sarvar", "2026-01-12", "Medium"],
  ["TD-105", "minio-file-storage PR 12", "DONE", "История", "Sunnatov Yaxyo", "2026-01-09", "Medium"],
  ["TD-104", "minio-file-storage PR 9", "DONE", "История", "Saidov Jamshid", "2026-01-08", "Medium"],
  ["TD-103", "minio-file-storage PR 5", "DONE", "История", "Saidov Jamshid", "2026-01-05", "Medium"],
  ["TD-102", "minio-file-storage PR 4", "DONE", "История", "Saidov Jamshid", "2025-12-30", "Medium"],
  ["TD-101", "trastpay-admin-front dev dagi oxirigi o'zgarishni prod ga deploy qilish kerak", "DONE", "Задача", "Sunnatov Yaxyo", "2025-12-30", "Medium"],
  ["TD-100", "trastpay-admin-front PR-304", "DONE", "Задача", "Sunnatov Yaxyo", "2025-12-29", "Medium"],
  ["TD-99", "trastpay-admin-front dev dagi oxirigi o'zgarishni exp ga deploy qilish kerak", "DONE", "Задача", "Sunnatov Yaxyo", "2025-12-29", "Medium"],
  ["TD-98", "(Front) trastpay-admin-front reports branch dan devga push qilib, dev dan experimentalga deploy qilish kerak", "DONE", "Задача", "Saidov Jamshid", "2025-12-29", "Medium"],
  ["TD-97", "trastpay-admin-front dev dagi oxirigi o'zgarishni prod ga deploy qilish kerak", "DONE", "История", "Sunnatov Yaxyo", "2025-12-26", "Medium"],
  ["TD-96", "trastpay-admin-api (prod) нужно хадеплоить", "DONE", "История", "Sunnatov Yaxyo", "2025-12-25", "Medium"],
  ["TD-95", "trastpay-admin-front dev dagi oxirigi o'zgarishni prod ga deploy qilish kerak", "DONE", "История", "Amanhojaev Nodirkhon", "2025-12-23", "Medium"],
  ["TD-94", "trustbank-eimzo-serivce prod, нужно проверить работоспособность. Сервис не отвечает", "DONE", "История", "Sunnatov Yaxyo", "2025-12-22", "Medium"],
  ["TD-93", "ДБО: trustbank-(bank, middleware, profiles, auth, references)-back нужно добавить prometheus и grafana", "DONE", "История", "Sunnatov Yaxyo", "2025-12-22", "Medium"],
  ["TD-92", "trustbank-bank-back нужно сделать разделение микросервиса на два pod. Один для api микросервиса, другой для обработки queue микросервиса", "DONE", "История", "Sunnatov Yaxyo", "2025-12-22", "Medium"],
  ["TD-91", "trustbank-iabs-api test, нужны доступы к базе данных", "DONE", "История", "Sunnatov Yaxyo", "2025-12-22", "Medium"],
  ["TD-90", "trastpay-admin-front dev dagi oxirigi o'zgarishni prod ga deploy qilish kerak", "DONE", "История", "Sunnatov Yaxyo", "2025-12-12", "Medium"],
  ["TD-89", "trastpay-admin-front dev dagi oxirigi o'zgarishni prod ga deploy qilish kerak", "DONE", "История", "Sunnatov Yaxyo", "2025-12-11", "Medium"],
  ["TD-86", "trastpay-admin-front dev dagi oxirigi o'zgarishni prod ga deploy qilish kerak", "DONE", "История", "Sunnatov Yaxyo", "2025-12-05", "Medium"],
  ["TD-85", "trastpay-admin-front dev dagi oxirigi o'zgarishni prod ga deploy qilish kerak", "DONE", "История", "Sunnatov Yaxyo", "2025-12-03", "Medium"],
  ["TD-84", "idsys-abs-scheduler-exp auto deploy ishlamaypti", "DONE", "История", "Sunnatov Yaxyo", "2025-11-26", "Highest"],
  ["TD-83", "trastpay-client-api-exp dan Telecom anti fraud ga chiqishini tekshirib bera olasizlarmi", "DONE", "История", "Zokirov Bobur", "2025-11-21", "Medium"],
  ["TD-82", "Code togri tersam ham hato qaytarvati. 2FA o'chirib qo'yolimizmi uchotkam uchun?", "DONE", "История", "Zokirov Bobur", "2025-11-21", "Medium"],
  ["TD-81", "BM дан шу вакт оралигидаги шу транзакцияни ЛОГи керак", "DONE", "История", "Zokirov Bobur", "2025-11-21", "Medium"],
  ["TD-79", "Шу сервисда узилишла кузатилвотти(п2п да копрок) \"http://uzservice2.trustbank.uz/api/jsonrpc\": Read timed", "DONE", "История", "Sunnatov Yaxyo", "2025-11-21", "Medium"],
  ["TD-78", "trastpay-client-api-exp. Token expire vaqtini 1 kunlik qilish kerak.", "DONE", "История", "Amanhojaev Nodirkhon", "2025-11-21", "Medium"],
  ["TD-77", "git.trastpay.uz ga kirolmayapman.", "DONE", "История", "Amanhojaev Nodirkhon", "2025-11-21", "Medium"],
  ["TD-76", "trastpay-admin-api Producationda deploy qilish kerak", "DONE", "История", "Amanhojaev Nodirkhon", "2025-11-20", "Medium"],
  ["TD-75", "Prodga trastpay-product-api ni deploy qivarish kerek", "DONE", "История", "Amanhojaev Nodirkhon", "2025-11-20", "Highest"],
  ["TD-74", "idsys-handler experimental da avto deploy ishlamayapti", "DONE", "История", "Amanhojaev Nodirkhon", "2025-11-20", "Highest"],
  ["TD-73", "idsys-client-api experimental avto deploy ishlamaypti", "DONE", "История", "Amanhojaev Nodirkhon", "2025-11-20", "Highest"],
  ["TD-72", "trastpay-payment-api trastpay-transaction-perform-service Production da deploy qilib bera olasizmi", "DONE", "История", "Amanhojaev Nodirkhon", "2025-11-20", "Medium"],
  ["TD-71", "Нужно дать правы в гитлаб", "DONE", "История", "Sunnatov Yaxyo", "2025-11-10", "Medium"],
  ["TD-70", "idsys-handler деплой на прод", "DONE", "История", "Sunnatov Yaxyo", "2025-11-04", "Medium"],
  ["TD-69", "IB Group бойича rabbitMQ га доступ", "DONE", "История", "Sunnatov Yaxyo", "2025-11-04", "Medium"],
  ["TD-67", "Logs - описанияга кошганим бойича логлар кере", "DONE", "Задача", "Sunnatov Yaxyo", "2025-11-03", "Medium"],
  ["TD-66", "Bmms Logs - for bug fix and optimisation", "DONE", "Задача", "Sunnatov Yaxyo", "2025-11-03", "Medium"],
  ["TD-65", "trastpay-transaction-perform-service Prod deploy qilish kerak", "DONE", "История", "Amanhojaev Nodirkhon", "2025-10-30", "Medium"],
  ["TD-64", "trastpay-vendor-api PROD deploy qilish kerak", "DONE", "История", "Amanhojaev Nodirkhon", "2025-10-30", "Medium"],
  ["TD-63", "trastpay-payment-api PROD deploy qilish kerak", "DONE", "История", "Amanhojaev Nodirkhon", "2025-10-28", "Medium"],
  ["TD-62", "trastpay-product-handler PROD ga deploy va env failiga yangi parametrlarni qo'shish", "DONE", "История", "Amanhojaev Nodirkhon", "2025-10-27", "Medium"],
  ["TD-61", "identification-services-frontend: exp deploy", "DONE", "История", "Amanhojaev Nodirkhon", "2025-10-27", "Medium"],
  ["TD-60", "trastpay-card-api PROD deploy qilish kerak", "DONE", "История", "Amanhojaev Nodirkhon", "2025-10-24", "Medium"],
  ["TD-59", "indentification-service-frontend deploy-exp", "DONE", "История", "Amanhojaev Nodirkhon", "2025-10-23", "Medium"],
  ["TD-58", "trastpay-client-api deploy production", "DONE", "История", "Amanhojaev Nodirkhon", "2025-10-21", "Medium"],
  ["TD-57", "identification-services-api grafana надо добвить", "DONE", "История", "Amanhojaev Nodirkhon", "2025-10-17", "Medium"],
  ["TD-56", "Прошу открыть доступ к GitLab проекта Multicard.", "DONE", "История", "Zokirov Bobur", "2025-10-16", "Medium"],
  ["TD-55", "trastpay-product-handler Деплой на прод ", "DONE", "История", "Amanhojaev Nodirkhon", "2025-10-16", "Medium"],
  ["TD-54", "trastpay-card-api deploy qilish kerak", "DONE", "История", "Amanhojaev Nodirkhon", "2025-10-14", "Medium"],
  ["TD-53", "trastpay-admin-api-exp ishlamayapti", "DONE", "История", "Amanhojaev Nodirkhon", "2025-10-08", "Medium"],
  ["TD-52", "trastpay-transactions-perform-service надо сделать деплой на проде", "DONE", "История", "Amanhojaev Nodirkhon", "2025-10-08", "Medium"],
  ["TD-51", "trastpay-payment-api надо сделать деплой на проде", "DONE", "История", "Amanhojaev Nodirkhon", "2025-10-08", "Medium"],
  ["TD-50", "trastpay-transactions-perform-service надо сделать деплой на проде", "DONE", "История", "Amanhojaev Nodirkhon", "2025-10-07", "Medium"],
  ["TD-49", "object-storage-service deploy to production", "DONE", "История", "Zokirov Bobur", "2025-10-07", "Medium"],
  ["TD-48", "identification-services-api деплой на exp", "DONE", "История", "Amanhojaev Nodirkhon", "2025-10-07", "Medium"],
  ["TD-47", "trastpay-client-api va trastpay-payment-api deploy qilish kerak", "DONE", "История", "Amanhojaev Nodirkhon", "2025-10-02", "Medium"],
  ["TD-46", "trastpay-client-api-exp va trastpay-payment-api-exp deploy qilish kerak ", "DONE", "История", "Amanhojaev Nodirkhon", "2025-10-02", "Medium"],
  ["TD-45", "Продга деплой idsys-handler", "DONE", "История", "Amanhojaev Nodirkhon", "2025-09-30", "Highest"],
  ["TD-44", "trastpay-client-api deploy qilish kerak", "DONE", "История", "Abduvokhid", "2025-09-30", "Medium"],
  ["TD-43", "trastpay-payment-api deploy qilish kerak", "DONE", "История", "Amanhojaev Nodirkhon", "2025-09-30", "Medium"],
  ["TD-42", "3. trastpay-payment-api deploy qilish kerak", "DONE", "История", "Amanhojaev Nodirkhon", "2025-09-29", "Medium"],
  ["TD-41", "2. trastpay-client-api prodga deploy qilish kerak", "DONE", "История", "Amanhojaev Nodirkhon", "2025-09-29", "Medium"],
  ["TD-40", "1. trastpay-admin-api prodga deploy qilish kerak", "DONE", "История", "Amanhojaev Nodirkhon", "2025-09-29", "Medium"],
  ["TD-39", "Prodda trastpay-product-api deploy qilish kerek", "DONE", "История", "Amanhojaev Nodirkhon", "2025-09-23", "Medium"],
  ["TD-38", "trastpay-perform-abs-transactions-scheduler-exp auto deploy не работает", "DONE", "История", "Amanhojaev Nodirkhon", "2025-09-19", "Medium"],
  ["TD-37", "trastpay-notification-service-exp auto deploy не работает", "DONE", "История", "Amanhojaev Nodirkhon", "2025-09-19", "Medium"],
  ["TD-36", "trastpay-routine-schedulers-exp auto deploy не работает", "DONE", "История", "Amanhojaev Nodirkhon", "2025-09-19", "Medium"],
  ["TD-35", "trastpay-cashback-perform-scheduler-exp auto deploy не работает", "DONE", "История", "Amanhojaev Nodirkhon", "2025-09-19", "Medium"],
  ["TD-34", "trastpay-sync-merchants-scheduler-exp auto deploy не работает", "DONE", "История", "Amanhojaev Nodirkhon", "2025-09-19", "Medium"],
  ["TD-33", "trastpay-sync-bank-branch-scheduler-exp auto deploy не работает", "DONE", "История", "Amanhojaev Nodirkhon", "2025-09-19", "Medium"],
  ["TD-32", "Деплой на прод trastpay-product-api", "DONE", "История", "Amanhojaev Nodirkhon", "2025-09-19", "Highest"],
  ["TD-31", "Env parametrlarni trastpay-card-api-exp dan trastpay-product-handler-exp ga ko'chirib qo'yish", "DONE", "Задача", "Abduvokhid", "2025-09-08", "Highest"],
  ["TD-30", "Открыть доступ к новой gitlab", "DONE", "Задача", "Abduvokhid", "2025-09-08", "Medium"],
  ["TD-29", "trastpay-admin-api prodga deploy qivarish kerek", "DONE", "Задача", "Amanhojaev Nodirkhon", "2025-09-05", "Medium"],
  ["TD-28", "trastid-client-api-exp eski kod deploy bo'vati yangisi bo'maypti", "DONE", "Задача", "Abduvokhid", "2025-09-02", "Highest"],
  ["TD-27", "trastpay-identifications-check-scheduler-exp ni env faylidan IDENTIFICATION_SERVICE_ENDPOINT IDENTIFICATION_SERVICE_LOGIN IDENTIFICATION_SERVICE_PASSWORD qiymatlarini trastpay-admin-api-exp ni env siga qo'shvarish kerek", "DONE", "Задача", "Abduraxmonov Islom", "2025-09-02", "Highest"],
  ["TD-26", "trastpay-admin-api деплой прод", "DONE", "Задача", "Amanhojaev Nodirkhon", "2025-08-28", "Medium"],
  ["TD-25", "Нужно открыть доступ к Деко для уч. запись b.zokirov", "DONE", "История", "Zokirov Bobur", "2025-08-27", "Highest"],
  ["TD-23", "Деплой на прод trastpay-callback-receiver-api", "DONE", "Задача", "Amanhojaev Nodirkhon", "2025-08-22", "Medium"],
  ["TD-22", "Деплой на прод idsys-operator-api, idsys-handlaer idsys-abs-scheduler,", "DONE", "Задача", "Amanhojaev Nodirkhon", "2025-08-22", "Medium"],
  ["TD-20", "redis-commander [docker]", "DONE", "История", "Sunnatov Yaxyo", "2025-08-15", "Medium"],
  ["TD-19", "trastpay-vendor-api prod deploy qilish", "DONE", "Задача", "Amanhojaev Nodirkhon", "2025-08-08", "Highest"],
  ["TD-18", "Bonus loyihasini prod ga o'tqazish kerak", "DONE", "Задача", "Zokirov Bobur", "2025-08-08", "Medium"],
  ["TD-17", "[*.*.*16.5] test-server (open access to MyID, ABS, INTIS, PLAYMOBILE)", "DONE", "Задача", "Saidov Jamshid", "2025-08-07", "Medium"],
  ["TD-16", "[service] private-cloud-storage (minio)", "DONE", "Задача", "Abduvokhid", "2025-08-06", "Medium"],
  ["TD-14", "[back] trastpay-card-api деплой на прод", "DONE", "Задача", "Saidov Jamshid", "2025-08-05", "Medium"],
  ["TD-13", "Jar file upload for Bill Master", "DONE", "История", "Abduvokhid", "2025-08-04", "Medium"],
  ["TD-12", "[back] trastpay-vendor-api деплой на прод", "DONE", "Задача", "Saidov Jamshid", "2025-07-31", "Medium"],
  ["TD-11", "[back] trastpay-card-api деплой на прод", "DONE", "История", "Saidov Jamshid", "2025-07-29", "Medium"],
  ["TD-10", "[front] trastpay-admin-front деплой на прод", "DONE", "История", "Saidov Jamshid", "2025-07-29", "Medium"],
  ["TD-9", "[back] trastpay-card-api деплой на прод", "DONE", "Задача", "Saidov Jamshid", "2025-07-28", "Medium"],
  ["TD-8", "Нужно задеплойит на проде trastpay-client-api", "DONE", "История", "Abduvokhid", "2025-06-13", "Medium"],
  ["TD-7", "Bonus proektni local git ga ulash", "DONE", "История", "Abduvokhid", "2025-05-22", "Medium"],
  ["TD-6", "Dev Server ochib berish kerak", "DONE", "История", "Abduvokhid", "2025-05-22", "Medium"],
  ["TD-5", "Javohir aka ga testoviy virtualka ochib berish kerak", "DONE", "Задача", "Zokirov Bobur", "2025-05-15", "Medium"],
  ["TD-4", "Shu ikkita servisni deploy qilish: trastpay-transactions-perform-service trastpay-transactions-check-scheduler", "DONE", "История", "Abduvokhid", "2025-05-12", "Medium"],
  ["TD-3", "эксперименталдаги проекталрни .env ларига данныйлар кошиб чикиш", "DONE", "История", "Abduvokhid", "2025-05-06", "Highest"],
  ["TD-2", "trastpay-product-api ni deploy qivarish kerek", "DONE", "Задача", "Abduvokhid", "2025-05-06", "Medium"],
  ["TD-1", "ElasticSearch тизим жорий килиш", "DONE", "История", "Zokirov Bobur", "2025-04-08", "Medium"],
  ["BSA-3", "Документация Scoring Клиентов Юр-лиц и ИП", "UseCase & User Story", "Задание", "Pulatov Nozimjon", "2026-06-29", "Medium"],
  ["BSA-4", "Документация для создание договора Escrow", "API Integrations", "Задание", "Pulatov Nozimjon", "2026-06-29", "Medium"],
  ["BSA-5", "Документация для получение статуса по договору Escrow", "К выполнению", "Задание", "Pulatov Nozimjon", "2026-06-29", "Medium"]
];
