// Jira issues pre-fetched per epic — generated 2026-06-23 (sync updated 2026-06-29)
window.TB_JIRA_ISSUES = {
  "FC-13": [
    {"key": "FC-3", "summary": "Добавить поле - ФИО", "type": "История", "status": "Backlog", "done": false},
    {"key": "FC-9", "summary": "Cancel - Пул возврати", "type": "Задание", "status": "Backlog", "done": false},
    {"key": "FC-11", "summary": "Detail page га файл прикрепления кошиш", "type": "Задание", "status": "Backlog", "done": false},
    {"key": "FC-23", "summary": "QR генерация хар бир объект учун", "type": "Задание", "status": "Backlog", "done": false},
  ],
  "FC-14": [
    {"key": "FC-8", "summary": "Толовларга Rabbit кошиш", "type": "Задание", "status": "Backlog", "done": false},
    {"key": "FC-15", "summary": "Anorga интеграция", "type": "История", "status": "Backlog", "done": false},
    {"key": "FC-16", "summary": "Error handle", "type": "История", "status": "Backlog", "done": false},
  ],
  "FC-29": [
    {"key": "FC-1", "summary": "Соликга хисобод кетиши хар бир толов бойича", "type": "Задание", "status": "Готово", "done": true},
  ],
  "FC-30": [
    {"key": "FC-4", "summary": "Tarif - Ойлик ва кунлик расталар болиб чикиш", "type": "История", "status": "in dev", "done": false},
    {"key": "FC-6", "summary": "Auto Fill - толов вактида", "type": "История", "status": "Ready for dev", "done": false},
    {"key": "FC-10", "summary": "Check Api - Такрорий толов block", "type": "Задание", "status": "Ready for dev", "done": false},
    {"key": "FC-12", "summary": "Таблицада раста нархларини чкариб койиш", "type": "Задание", "status": "Ready for dev", "done": false},
  ],
  "FC-31": [
    {"key": "FC-24", "summary": "Анализ DSQ учун", "type": "История", "status": "Готово", "done": true},
  ],
  "FC-32": [
    {"key": "FC-33", "summary": "Видео Аналитика(AI)", "type": "Задание", "status": "Backlog", "done": false},
  ],
  "KT-25": [
  ],
  "KT-26": [
  ],
  "KT-27": [
    {"key": "KT-11", "summary": "Back: Push уведомления для платежных операции", "type": "История", "status": "Backlog", "done": false},
  ],
  "KT-28": [
  ],
  "KT-29": [
    {"key": "KT-35", "summary": "Mobile: Android da User ID yuborilmayapti", "type": "Баг", "status": "Blocked", "done": false},
    {"key": "KT-36", "summary": "Back: API реализация для 2 метода malware", "type": "История", "status": "Готово", "done": true},
    {"key": "KT-37", "summary": "Mobile: Malware API Integration", "type": "История", "status": "in dev", "done": false},
    {"key": "KT-135", "summary": "Front: Session_Id не отправляется", "type": "Баг", "status": "Готово", "done": true},
    {"key": "KT-136", "summary": "Mobile: Добавить тестовое приложение для проверки blacklist API", "type": "История", "status": "Готово", "done": true},
  ],
  "KT-30": [
    {"key": "KT-6", "summary": "FACEID ЦБ-ГЦИ", "type": "История", "status": "Blocked", "done": false},
  ],
  "KT-31": [
  ],
  "KT-32": [
  ],
  "KT-33": [
  ],
  "KT-34": [
    {"key": "KT-10", "summary": "Back: В случае если проводка удалена нужно синхронизировать статус", "type": "История", "status": "Documentation", "done": false},
  ],
  "MW-2": [
  ],
  "MW-3": [
    {"key": "MW-4", "summary": "Разработка API для перевода со счета на карту в рамках флоу разделения платежей / X-GO (BM)", "type": "История", "status": "Готово", "done": true},
    {"key": "MW-6", "summary": "X-GO: Интеграция с Uzcard/Humo для добавления карт (OTP/Verify)", "type": "История", "status": "В работе", "done": false},
  ],
  "MW-5": [
  ],
  "MW-7": [
  ],
  "SL-5": [
    {"key": "SL-31", "summary": "Not getting insurance amount", "type": "Задание", "status": "Готово", "done": true},
  ],
  "SL-6": [
    {"key": "SL-18", "summary": "GET payment-info with deal_ID", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-20", "summary": "Check status of transaction-id", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-35", "summary": "Оплата по deal_ID", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-42", "summary": "Add 'sender name' to BM request", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-43", "summary": "change date format in BM request", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-201", "summary": "[flutter] last payment recomendation", "type": "История", "status": "Готово", "done": true},
  ],
  "SL-7": [
    {"key": "SL-22", "summary": "Get client info by Prestige", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-46", "summary": "[back] Create token API", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-52", "summary": "[back] Integrate with BM (Check, Pay)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-53", "summary": "[back] Send transaction status to Prestige with Callback URL", "type": "История", "status": "Готово", "done": true},
  ],
  "SL-9": [
    {"key": "SL-26", "summary": "Проверка карты получателя", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-27", "summary": "Совершения перевода", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-28", "summary": "Получить статус транзакции", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-65", "summary": "Инициализация перевода Visa Direct", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-69", "summary": "Верстка", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-130", "summary": "Take payment info (Android)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-132", "summary": "Send payment detail to BM", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-230", "summary": "Moneysend > Tittle kelmayabti", "type": "Баг", "status": "Готово", "done": true},
  ],
  "SL-15": [
    {"key": "SL-29", "summary": "Клиент подает заявку на аннулирование карты", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-30", "summary": "Предоставить доступ сотрудникам", "type": "Задание", "status": "Готово", "done": true},
    {"key": "SL-32", "summary": "Add all IP's who accepts applications from users", "type": "Задание", "status": "Готово", "done": true},
    {"key": "SL-40", "summary": "Create login password for employees ПК", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-72", "summary": "Добавить в Админку, сортировку по дате", "type": "История", "status": "Готово", "done": true},
  ],
  "SL-16": [
    {"key": "SL-56", "summary": "Добавить Момент карту (Android)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-82", "summary": "Проверка сущности карты (меторд P2P info)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-83", "summary": "Получение токена карты (метод cards.new.otp)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-84", "summary": "Проверка ОТП и получение токена карты (card.new.verify)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-85", "summary": "Запрос на регистрацию карты ( create-instant-card-app )", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-86", "summary": "Вызов метода для установкиПИН-КОД (online.pin.set)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-87", "summary": "Проверка статуса (get-status-card)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-88", "summary": "Отправка об успешной установке", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-89", "summary": "Добавить Момент карту (iOS)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-90", "summary": "Добавить OTP (Android)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-91", "summary": "Добавить OTP (iOS)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-92", "summary": "Создать PIN (Android)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-93", "summary": "Создать PIN (iOS)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-94", "summary": "Успешно добавлена (Android)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-95", "summary": "Успешно добавлена (iOS)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-125", "summary": "Открыть сайт Uzcard во webview внутри TrastPay. После ввода PIN-кода открыть страницу Car...", "type": "История", "status": "Готово", "done": true},
  ],
  "SL-71": [
    {"key": "SL-70", "summary": "Добавить проводку из бэкенда трастпей", "type": "История", "status": "Готово", "done": true},
  ],
  "SL-100": [
    {"key": "SL-99", "summary": "Add comment in P2P (Android)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-106", "summary": "Trastpay > users can use only Mobile network, revoke the using wifi connections", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-115", "summary": "Add comment in P2P (iOS)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-120", "summary": "Trastpay > users can use only Mobile network, revoke the using wifi connections", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-121", "summary": "Trastpay > users can use only Mobile network, revoke the using wifi connections", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-122", "summary": "Add new comment to the P2P (Android)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-123", "summary": "Add new comment to the P2P (iOS)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-160", "summary": "20 - Zararli dastur yoki masofadan boshqaruv aniqlanganda SMS-xabarnoma yuborish", "type": "История", "status": "IN ANALYSIS", "done": false},
    {"key": "SL-164", "summary": "60 - Ilova ishga tushganda qurilma xavfsizligini tekshirish va salbiy holatda ilovani bloklash + SMS yuborish", "type": "История", "status": "IN ANALYSIS", "done": false},
    {"key": "SL-176", "summary": "[back]  Проверка совпадения ПИНФЛ и номера телефона", "type": "История", "status": "К выполнению", "done": false},
    {"key": "SL-178", "summary": "[flutter]  Проверка совпадения ПИНФЛ и номера телефона", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-186", "summary": "ЦБ so'ragan ma'lumotlarni bazadan olib berish", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-256", "summary": "Интеграция с сервисом Xolis", "type": "История", "status": "IN ANALYSIS", "done": false},
    {"key": "SL-257", "summary": "Льготная ипотека «Мой дом» (Mening Uyim ТСЧЖ)", "type": "История", "status": "IN ANALYSIS", "done": false},
    {"key": "SL-258", "summary": "Валютный Вклад 'Qulay sarmoya'", "type": "История", "status": "К выполнению", "done": false},
    {"key": "SL-259", "summary": "возврат платежа МУНИС", "type": "История", "status": "К выполнению", "done": false},
    {"key": "SL-262", "summary": "dinamic QR не притягивает сумму", "type": "Баг", "status": "PENDING", "done": false},
    {"key": "SL-275", "summary": "в БМ нужно добавить параметр", "type": "Задание", "status": "К выполнению", "done": false},
  ],
  "SL-103": [
    {"key": "SL-102", "summary": "Add check-request to Create-customer", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-143", "summary": "Flutter | Bug Fixing", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-179", "summary": "[flutter] FIX client auth header. user-agent", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-182", "summary": "40,90 statusi tori kelmayabti karta qoshvotganda", "type": "Баг", "status": "К выполнению", "done": false},
    {"key": "SL-184", "summary": "Картани пин-кодини сет клиш методини кошиб бериш (Момент кард)", "type": "Баг", "status": "К выполнению", "done": false},
    {"key": "SL-183", "summary": "эксп ва прод-да ассетсни жавоби хархил", "type": "Баг", "status": "Готово", "done": true},
    {"key": "SL-190", "summary": "Notification bormasligini tekshirish, testiviy accountga. Phone: 909756057", "type": "История", "status": "К выполнению", "done": false},
    {"key": "SL-200", "summary": "add card images", "type": "История", "status": "К выполнению", "done": false},
    {"key": "SL-202", "summary": "Правильно отображать погашения по графику и еж.месячный платеж", "type": "Баг", "status": "Готово", "done": true},
    {"key": "SL-206", "summary": "Правильно отображать на главном списке кредитов сумму просроченного платежа", "type": "Баг", "status": "К выполнению", "done": false},
    {"key": "SL-207", "summary": "Отобразить сумму следующего месяца платежа на окне 'Детали кредита'", "type": "Баг", "status": "К выполнению", "done": false},
    {"key": "SL-209", "summary": "Уведомления приходит на английском языке", "type": "Баг", "status": "К выполнению", "done": false},
    {"key": "SL-211", "summary": "в погашении кредита не приходит typePay и Tranzit", "type": "Баг", "status": "К выполнению", "done": false},
    {"key": "SL-217", "summary": "Icon image'lar cashirovanie qilish kerak", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-219", "summary": "[Flutter] Avto rassrochka", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-224", "summary": "Identification > case: Error message chiqarish kerak", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-225", "summary": "'Exchange' при обмене на визу карту, не передается 'pan' карты VISA", "type": "Баг", "status": "К выполнению", "done": false},
    {"key": "SL-226", "summary": "Omonot > History ko'rinmayapti", "type": "Баг", "status": "Готово", "done": true},
    {"key": "SL-229", "summary": "В чеке оплаты по Budget показывает некорректную сумму", "type": "Баг", "status": "Готово", "done": true},
    {"key": "SL-231", "summary": "'Anti-fraud' - внедрить алгоритм для обхода 1-минутной ошибки", "type": "Задание", "status": "К выполнению", "done": false},
    {"key": "SL-232", "summary": "Operation not faund ошибка при попытке перевести между счетами", "type": "Баг", "status": "К выполнению", "done": false},
    {"key": "SL-233", "summary": "Добавить апи для смены пин-кода", "type": "Задание", "status": "К выполнению", "done": false},
    {"key": "SL-234", "summary": "Подготовка к релизу платформы Андроид '3.0.37'", "type": "Задание", "status": "Готово", "done": true},
    {"key": "SL-235", "summary": "История платежей статусы платежей не обновляются", "type": "Баг", "status": "К выполнению", "done": false},
    {"key": "SL-236", "summary": "Чеклардеги, вахтни тогри такдиг этиш", "type": "Баг", "status": "К выполнению", "done": false},
    {"key": "SL-238", "summary": "A2A > Text UX ga to'ri holatda mobilkaga berilishi kerak", "type": "Баг", "status": "Готово", "done": true},
    {"key": "SL-240", "summary": "Virtual kartadan > koshelekga pul o'tmayapti", "type": "Баг", "status": "Готово", "done": true},
    {"key": "SL-241", "summary": "Chekda 'komissiya miqdori' xato ko'rsatvotti", "type": "Баг", "status": "Готово", "done": true},
    {"key": "SL-248", "summary": "SMS shablon qo'shish", "type": "Задание", "status": "Готово", "done": true},
    {"key": "SL-260", "summary": "notificationda broadcast-notification paytida microservice qotbqovotti", "type": "Баг", "status": "IN DEV", "done": false},
    {"key": "SL-261", "summary": "Chekda 'komissiya miqdori' xato ko'rsatvotti [budget tolov]", "type": "Баг", "status": "Готово", "done": true},
    {"key": "SL-265", "summary": "A2A > bind qilishda filtr olib tashlash kerak", "type": "Задание", "status": "READY TO QA", "done": false},
    {"key": "SL-266", "summary": "A2A > bind check ishlamayapti", "type": "Баг", "status": "IN QA", "done": false},
    {"key": "SL-267", "summary": "trastpaydan iABS ga, transaction metodiga cheksiz zapros tashalvotti har kuni. Loop ni to'xtatish kerak", "type": "Задание", "status": "К выполнению", "done": false},
    {"key": "SL-268", "summary": "A2A > poluchatel kartasida select button'ni FIX qilib qo'yish kerak", "type": "История", "status": "IN QA", "done": false},
    {"key": "SL-271", "summary": "При сканере QR-кода не переходит на следующий page", "type": "Баг", "status": "Готово", "done": true},
    {"key": "SL-272", "summary": "Иловага виртуал картасини кушомиетти", "type": "Задание", "status": "Готово", "done": true},
    {"key": "SL-276", "summary": "A2A > bind_phone_wallet > unknown error", "type": "Баг", "status": "IN ANALYSIS", "done": false},
  ],
  "SL-104": [
    {"key": "SL-101", "summary": "Release Group-IB", "type": "История", "status": "Готово", "done": true},
  ],
  "SL-107": [
    {"key": "SL-109", "summary": "Get access token", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-110", "summary": "Create session", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-111", "summary": "Get data with code", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-112", "summary": "Initialize SDK with session_ID (Android)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-114", "summary": "Integrate with iABS", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-142", "summary": "Verification MyID", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-175", "summary": "Identification > Adminka > List page'dan inner page ochganda Telefon raqam UX formatda tu...", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-187", "summary": "MyID: ЦБ district, mahalla code mapping. Convert to mongDB", "type": "История", "status": "Готово", "done": true},
  ],
  "SL-119": [
    {"key": "SL-116", "summary": "Настроить получение и обновление данных о налоговых задолженностях (BackEnd)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-117", "summary": "Реализовать отображение баннера на главном экране приложения (Mobile)(Android)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-197", "summary": "[Backend] Интеграция API для мобилки", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-198", "summary": "[Frontend] Сделать раздел для Push Soliq Qarzi", "type": "История", "status": "Готово", "done": true},
  ],
  "SL-128": [
    {"key": "SL-127", "summary": "Payment UzRTSB (Android)", "type": "История", "status": "Готово", "done": true},
  ],
  "SL-134": [
    {"key": "SL-135", "summary": "Add new list for 'p2p white-list'", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-136", "summary": "Add 'p2p white-list' for adminka", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-137", "summary": "Integrate 'white-list' to client API", "type": "История", "status": "Готово", "done": true},
  ],
  "SL-144": [
    {"key": "SL-145", "summary": "Telefon raqami va JSHSHIR mosligini tekshirish (ro'yxatdan o'tish va karta biriktirishda)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-146", "summary": "Ro'yxatdan o'tgandan so'ng foydalanuvchini login, parol va OTP orqali autentifikatsiyadan...", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-147", "summary": "Ro'yxatdan o'tgandan so'ng sessiyani yakunlash va kartani OTP + biometrik tasdiqlash orqa...", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-148", "summary": "Telefon raqami mos kelmaganda karta biriktirishni bloklash va PUSH-xabar yuborish", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-149", "summary": "OTP kodga qo'yiladigan talablarni joriy etish", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-150", "summary": "OTP 3 marta noto'g'ri kiritilganda foydalanuvchini vaqtincha bloklash va SMS-xabarnoma yuborish", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-152", "summary": "8 - Masofaviy biometrik identifikatsiyada liveness detection funksiyasini joriy etish", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-153", "summary": "9 - Biometrik identifikatsiya xizmat provayderi bilan shartnomaga javobgarlik bandlarini kiritish", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-154", "summary": "10 - Foydalanuvchi akkauntiga faqat tegishli (va yaqin qarindoshlar) hisoblarini biriktirish va P2P o'tkazmalarni cheklash", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-155", "summary": "12 - OTP kodni qurilmaga bog'lash (device binding) va boshqa qurilmalarda ishlatilishini cheklash", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-156", "summary": "14 - Yangi qurilmadan kirish yoki parol tiklanganda kartalarni unlink qilish va tranzaksiya tarixini tozalash", "type": "История", "status": "Готово", "done": true},
  ],
  "SL-151": [
    {"key": "SL-157", "summary": "15 - mobil qurilmaning texnik identifikatsiya va dasturiy parametrlari avtomatik tarzda a...", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-158", "summary": "16 - Ro'yxatdan o'tmagan qurilmadan akkauntga kirish urinishida SMS-xabarnoma yuborish", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-159", "summary": "18 - Foydalanuvchi sessiyasi uchun inactivity timeout (3 daqiqa) joriy etish", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-161", "summary": "26 - Moliyaviy operatsiyalar oldidan foydalanuvchidan qo'shimcha tasdiq (anti-fraud warni...", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-162", "summary": "27 - Mobil ilovada 'Firibgarlik haqida xabar berish' bo'limini joriy etish", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-163", "summary": "59 - Root/Jailbreak aniqlanganda mobil ilova funksionalligini cheklash", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-165", "summary": "61 - Mobil ilova kodini reverse engineering va dekompilyatsiyadan himoyalash", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-166", "summary": "62 - Mobil ilovaga antivirus va antifraud funksiyalariga ega xavfsizlik SDK integratsiyasi", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-167", "summary": "64 - Mobil ilovadagi akkauntga 1 daqiqa mobaynida 1 ta IP manzildan 2 va undan ortiq quri...", "type": "История", "status": "Готово", "done": true},
  ],
  "SL-194": [
    {"key": "SL-195", "summary": "[Flutter] Draw UI for full flow", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-196", "summary": "[flutter] Integrate with backend API", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-212", "summary": "Привязка номера телефона к кошелку счет (22616)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-213", "summary": "[back] BM > p2p/info", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-214", "summary": "[back] BM > p2p/pay", "type": "История", "status": "Готово", "done": true},
  ],
  "SL-203": [
    {"key": "SL-138", "summary": "Drag Metal (Oltin depozit)", "type": "История", "status": "К выполнению", "done": false},
    {"key": "SL-140", "summary": "Add card - analogue: ANOR", "type": "История", "status": "К выполнению", "done": false},
    {"key": "SL-168", "summary": "Visa direct", "type": "История", "status": "К выполнению", "done": false},
    {"key": "SL-170", "summary": "Paynet > Кредит погашение", "type": "История", "status": "К выполнению", "done": false},
    {"key": "SL-171", "summary": "Urban drive", "type": "История", "status": "К выполнению", "done": false},
    {"key": "SL-174", "summary": "Remove 1 hour block for adding virtual Visa/Mastercard", "type": "История", "status": "К выполнению", "done": false},
    {"key": "SL-204", "summary": "Humo moment card", "type": "История", "status": "К выполнению", "done": false},
    {"key": "SL-208", "summary": "Tez QR", "type": "История", "status": "К выполнению", "done": false},
    {"key": "SL-218", "summary": "Humo / Visa cobadge kartalarda cvv ko'rsatish", "type": "История", "status": "К выполнению", "done": false},
    {"key": "SL-242", "summary": "AFIN card", "type": "История", "status": "К выполнению", "done": false},
    {"key": "SL-244", "summary": "EWA (Earned wage success)", "type": "История", "status": "К выполнению", "done": false},
    {"key": "SL-245", "summary": "Оплата на места", "type": "История", "status": "К выполнению", "done": false},
    {"key": "SL-246", "summary": "Емиссия ПК через трастпаи", "type": "История", "status": "К выполнению", "done": false},
    {"key": "SL-247", "summary": "Steam оплата", "type": "История", "status": "К выполнению", "done": false},
    {"key": "SL-249", "summary": "Camera card scan", "type": "История", "status": "К выполнению", "done": false},
    {"key": "SL-250", "summary": "Буквенно-цифровой OTP-код", "type": "История", "status": "К выполнению", "done": false},
    {"key": "SL-251", "summary": "Изучение системы Alipay", "type": "История", "status": "К выполнению", "done": false},
    {"key": "SL-254", "summary": "Проверка владельца номера телефона", "type": "История", "status": "К выполнению", "done": false},
  ],
  "SL-222": [
    {"key": "SL-223", "summary": "Identifikatsiya rasm olishga retry button", "type": "История", "status": "Готово", "done": true},
  ],
  "SL-243": [
  ],
  "SL-252": [
  ],
  "SL-253": [
  ],
  "PH-1": [
    {"key": "PH-2", "summary": "Uzcard ва HUMO P2P интеграцияси", "type": "История", "status": "Ready for Test", "done": false},
    {"key": "PH-3", "summary": "OFD (Солиқ) тизими билан интеграция", "type": "История", "status": "Ready for Test", "done": false},
    {"key": "PH-4", "summary": "HUMO терминаллари бўйича Reconciliation интеграцияси", "type": "История", "status": "В работе", "done": false},
    {"key": "PH-5", "summary": "Uzcard Terminal API (Check/Add/Remove) интеграцияси", "type": "История", "status": "Ready for Test", "done": false},
  ],
  "TB-3": [
    {"key": "TB-4", "summary": "Modul-RBAC + ko'p-kompaniya modeli", "type": "Задание", "status": "Готово", "done": true},
    {"key": "TB-5", "summary": "Auth/notification/integration modellari", "type": "Задание", "status": "Готово", "done": true},
    {"key": "TB-6", "summary": "To'lov domeni modeli", "type": "Задание", "status": "Готово", "done": true},
    {"key": "TB-8", "summary": "Kontragent domeni modeli", "type": "Задание", "status": "Готово", "done": true},
  ],
  "TB-12": [
    {"key": "TB-24", "summary": "Env konfiguratsiya + fail-fast validatsiya", "type": "Задание", "status": "ready for dev", "done": false},
    {"key": "TB-25", "summary": "Strukturali JSON logging + PII masking", "type": "Задание", "status": "Documentation", "done": false},
    {"key": "TB-26", "summary": "Global HTTP kontrakt (ValidationPipe + envelope)", "type": "Задание", "status": "backlog", "done": false},
    {"key": "TB-27", "summary": "X-Correlation-ID middleware", "type": "Задание", "status": "backlog", "done": false},
    {"key": "TB-28", "summary": "App bootstrap + Swagger + Health", "type": "Задание", "status": "backlog", "done": false},
    {"key": "TB-29", "summary": "Queue infra + worker skeleti", "type": "Задание", "status": "backlog", "done": false},
    {"key": "TB-30", "summary": "Observability wiring (OTel + Sentry)", "type": "Задание", "status": "backlog", "done": false},
  ],
  "TB-14": [
    {"key": "TB-31", "summary": "SMS-OTP oqimi", "type": "Задание", "status": "backlog", "done": false},
    {"key": "TB-32", "summary": "Login + refresh + parol tiklash", "type": "Задание", "status": "backlog", "done": false},
    {"key": "TB-33", "summary": "JWT sessiya + logout blacklist", "type": "Задание", "status": "backlog", "done": false},
    {"key": "TB-34", "summary": "JwtAuthGuard + @CurrentUser ni api'da chiqarish", "type": "Задание", "status": "backlog", "done": false},
    {"key": "TB-35", "summary": "To'liq registratsiya", "type": "Задание", "status": "backlog", "done": false},
  ],
  "TB-15": [
    {"key": "TB-36", "summary": "Kompaniya tanlash + ruxsatlar endpointlari", "type": "Задание", "status": "backlog", "done": false},
    {"key": "TB-37", "summary": "Modul-darajali RBAC guard", "type": "Задание", "status": "backlog", "done": false},
    {"key": "TB-38", "summary": "Imzo siyosati servisi", "type": "Задание", "status": "backlog", "done": false},
    {"key": "TB-39", "summary": "Settings endpointlari", "type": "Задание", "status": "backlog", "done": false},
    {"key": "TB-40", "summary": "Self-service profil", "type": "Задание", "status": "backlog", "done": false},
  ],
  "TB-16": [
    {"key": "TB-41", "summary": "References modulini yaratish (4 endpoint + lookup)", "type": "Задание", "status": "Готово", "done": true},
    {"key": "TB-42", "summary": "Seed infratuzilmasi + bazaviy data", "type": "Задание", "status": "in dev", "done": false},
    {"key": "TB-43", "summary": "To'liq MFO + to'lov maqsadi data importi", "type": "Задание", "status": "backlog", "done": false},
  ],
  "TB-17": [
    {"key": "TB-44", "summary": "Gateway auth + token boshqaruvi", "type": "Задание", "status": "in dev", "done": false},
    {"key": "TB-45", "summary": "Hisob raqamlar va hisoblar servisi", "type": "Задание", "status": "backlog", "done": false},
    {"key": "TB-46", "summary": "Tranzaksiya yaratish + poll + idempotentlik", "type": "Задание", "status": "backlog", "done": false},
    {"key": "TB-47", "summary": "ABS ma'lumotnoma (dictionary)", "type": "Задание", "status": "backlog", "done": false},
    {"key": "TB-48", "summary": "audit + circuit breaker", "type": "Задание", "status": "backlog", "done": false},
    {"key": "TB-49", "summary": "ABS status - DocumentStatus mapping", "type": "Задание", "status": "backlog", "done": false},
  ],
  "TB-18": [
    {"key": "TB-50", "summary": "Hisoblar ro'yxati + ko'chirma + eksport", "type": "Задание", "status": "backlog", "done": false},
    {"key": "TB-51", "summary": "Dashboard + imzolanmagan hujjatlar", "type": "Задание", "status": "backlog", "done": false},
    {"key": "TB-52", "summary": "To'lov draftini yaratish (idempotent)", "type": "Задание", "status": "backlog", "done": false},
    {"key": "TB-53", "summary": "To'lovni validatsiya qilish", "type": "Задание", "status": "backlog", "done": false},
    {"key": "TB-54", "summary": "Imzolash va bankka yuborish", "type": "Задание", "status": "backlog", "done": false},
    {"key": "TB-55", "summary": "To'lovlar ro'yxati (filtr)", "type": "Задание", "status": "backlog", "done": false},
    {"key": "TB-56", "summary": "To'lov shablonlari CRUD", "type": "Задание", "status": "backlog", "done": false},
    {"key": "TB-57", "summary": "Draftlar ro'yxati va saqlash", "type": "Задание", "status": "backlog", "done": false},
  ],
  "TB-19": [
    {"key": "TB-58", "summary": "Hujjatlar ro'yxati + tafsilot (status tarixi)", "type": "Задание", "status": "backlog", "done": false},
    {"key": "TB-59", "summary": "Qayta yuborish + bekor qilish", "type": "Задание", "status": "backlog", "done": false},
    {"key": "TB-60", "summary": "Kvitansiya: real PDF + MinIO", "type": "Задание", "status": "backlog", "done": false},
  ],
  "TB-20": [
    {"key": "TB-61", "summary": "Dispatch pipeline + kanal portlari", "type": "Задание", "status": "backlog", "done": false},
    {"key": "TB-62", "summary": "RabbitMQ consumer (worker)", "type": "Задание", "status": "backlog", "done": false},
    {"key": "TB-63", "summary": "Bildirishnomalar ro'yxati", "type": "Задание", "status": "backlog", "done": false},
    {"key": "TB-64", "summary": "Bildirishnoma sozlamalari", "type": "Задание", "status": "backlog", "done": false},
    {"key": "TB-65", "summary": "Producer publish: bank - RabbitMQ", "type": "Задание", "status": "backlog", "done": false},
    {"key": "TB-66", "summary": "Centrifugo (WS) + FCM (push) real adapterlari", "type": "Задание", "status": "backlog", "done": false},
  ],
  "TB-21": [
    {"key": "TB-67", "summary": "Kontragent CRUD + soft delete", "type": "Задание", "status": "backlog", "done": false},
    {"key": "TB-68", "summary": "INN qidiruv + primary autofill", "type": "Задание", "status": "backlog", "done": false},
    {"key": "TB-69", "summary": "Ierarxik kontragent guruhlari", "type": "Задание", "status": "backlog", "done": false},
    {"key": "TB-70", "summary": "GNK lookup + sync (port + stub)", "type": "Задание", "status": "backlog", "done": false},
    {"key": "TB-71", "summary": "Real GNK adapteri", "type": "Задание", "status": "backlog", "done": false},
  ],
  "TB-22": [
    {"key": "TB-72", "summary": "Integratsiyalar holatini ko'rsatish", "type": "Задание", "status": "backlog", "done": false},
    {"key": "TB-73", "summary": "Webhook key larini berish (xavfsiz)", "type": "Задание", "status": "backlog", "done": false},
    {"key": "TB-74", "summary": "Kiruvchi webhook'ni tekshirish endpointi", "type": "Задание", "status": "backlog", "done": false},
    {"key": "TB-75", "summary": "Integratsiya provisioning + real sync", "type": "Задание", "status": "backlog", "done": false},
  ],
  "TB-23": [
    {"key": "TB-76", "summary": "Har modul uchun e2e qamrov", "type": "Задание", "status": "backlog", "done": false},
    {"key": "TB-77", "summary": "Rol-asosli UAT stsenariylari", "type": "Задание", "status": "backlog", "done": false},
    {"key": "TB-78", "summary": "Pilot + monitoring", "type": "Задание", "status": "backlog", "done": false},
  ],
  "TB-79": [
    {"key": "TB-80", "summary": "CI gate (Node 20) + pnpm audit", "type": "Задание", "status": "backlog", "done": false},
    {"key": "TB-81", "summary": "secret-store + skan", "type": "Задание", "status": "backlog", "done": false},
    {"key": "TB-82", "summary": "prom-client metrika (C-modullar)", "type": "Задание", "status": "backlog", "done": false},
    {"key": "TB-83", "summary": "Audit log", "type": "Задание", "status": "backlog", "done": false},
    {"key": "TB-84", "summary": "Monitoring (Sentry + Grafana)", "type": "Задание", "status": "backlog", "done": false},
  ],
  "MDI-1": [
    {"key": "MDI-11", "summary": "D-1 — Documentatsiya taxlash, requirementlarni analiz qilish", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-12", "summary": "D-2 — Alternative loyihalarni organish", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-13", "summary": "D-3 — Marketplace doc + ADR", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-14", "summary": "D-4 — Polyglot FDK matrisa + ABI (ADR)", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-15", "summary": "D-5 — GitOps + tashqi CI/CD kontrakti", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-16", "summary": "D-6 — Functional nodes", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-17", "summary": "D-7 — Edge/WASM tier", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-18", "summary": "D-8 — SLO/errors", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-19", "summary": "D-9 — Decode kontrakt doc qayta yozish", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-20", "summary": "D-10 — Sync-reply correlation", "type": "Задание", "status": "Backlog", "done": false},
    {"key": "MDI-21", "summary": "D-11 — Konformans opt-in markerlar", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-22", "summary": "D-12 — Generation vs build plan_version", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-23", "summary": "D-13 — Node.js node-host compat", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-24", "summary": "D-14 — Workspace delete vs audit FK", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-25", "summary": "D-15a — Loop primitive", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-26", "summary": "D-17 — Environments + Promotion", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-27", "summary": "D-18 — In-house version registry + lockfile", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-28", "summary": "D-20 — DevOps developer loop", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-29", "summary": "D-21 — Collaborative designer qarori", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-30", "summary": "D-23 — Hybrid custom-roles RBAC", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-31", "summary": "D-24 — Per-env generation source-of-truth", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-32", "summary": "D-25 — Per-env overlay vs build-once", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-33", "summary": "D-26 — Declared-ref cross-env scope", "type": "Задание", "status": "Готово", "done": true},
  ],
  "MDI-2": [
    {"key": "MDI-34", "summary": "P1-1a — Monorepo scaffold", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-35", "summary": "P1-1b — CI + lint + build matrix", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-36", "summary": "P1-2 — Postgres sxema + migratsiyalar", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-37", "summary": "P1-3 — NestJS skeleton CRUD", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-38", "summary": "P1-4 — Auth/RBAC: SSO/OIDC + MFA", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-39", "summary": "P1-5 — Workspace API key/secret", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-40", "summary": "P1-6 — Go gateway: ingress + key validatsiya", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-41", "summary": "P1-7 — Go runner pool", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-42", "summary": "P1-8 — Docker driver + abstraction", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-43", "summary": "P1-6b — Tech debt: key-verify HTTP to gRPC", "type": "Задание", "status": "Backlog", "done": false},
    {"key": "MDI-44", "summary": "P1-8c — Tech debt: Docker SDK migratsiya", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-45", "summary": "P1-4a — Bug: mfa.service otplib tsc fail", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-46", "summary": "P1-9 — fn-format UDS ABI verbatim", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-47", "summary": "P1-10 — Per-key rate limit + IP allow/deny", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-48", "summary": "P1-G — GATE: auth + CRUD + invoke", "type": "Задание", "status": "Готово", "done": true},
  ],
  "MDI-3": [
    {"key": "MDI-49", "summary": "P2-1 — Event bus (Kafka/NATS)", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-50", "summary": "P2-2 — Actor-per-node engine", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-51", "summary": "P2-2a — Bug: shutdown channel race", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-52", "summary": "P2-3 — Backpressure ladder", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-53", "summary": "P2-4 — Inline fusion + DAG walk + routing", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-54", "summary": "P2-5 — Declarative reconcile kontrakti", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-55", "summary": "P2-6 — React designer: DAG canvas", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-56", "summary": "P2-7 — React: folder tree", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-57", "summary": "P2-G — GATE: backpressure bilan flow", "type": "Задание", "status": "Готово", "done": true},
  ],
  "MDI-4": [
    {"key": "MDI-58", "summary": "P3-1 — Adapter SDK Go kontrakti", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-59", "summary": "P3-2 — In-tree adapterlar HTTP/gRPC/GraphQL", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-60", "summary": "P3-2a — Tech debt: GraphQL status klassifikatsiya", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-61", "summary": "P3-2b — Gateway route-group wiring + gRPC streaming", "type": "Задание", "status": "Backlog", "done": false},
    {"key": "MDI-62", "summary": "P3-3 — Pull adapterlar Kafka/RabbitMQ", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-63", "summary": "P3-3a — Tech debt: Kafka adapter haqiqiy busga", "type": "Задание", "status": "Backlog", "done": false},
    {"key": "MDI-64", "summary": "P3-4 — Out-of-tree gRPC sidecar adapter", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-65", "summary": "P3-5 — Leader-elected scheduler", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-66", "summary": "P3-6 — Gateway Route Group", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-67", "summary": "P3-G — GATE: yangi protokol SDK orqali", "type": "Задание", "status": "Готово", "done": true},
  ],
  "MDI-5": [
    {"key": "MDI-68", "summary": "P4-1 — Build service: validate-classify-plan-compile", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-69", "summary": "P4-1a — Tech debt: flowplan library ajratish", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-70", "summary": "P4-2 — BuildKit image (Go orchestration)", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-71", "summary": "P4-2i — Build-farm runtime (Ops infra)", "type": "Задание", "status": "Backlog", "done": false},
    {"key": "MDI-72", "summary": "P4-3 — SBOM+vuln+cosign+SLSA (Go slice)", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-73", "summary": "P4-3i — Signing & registry runtime (Ops infra)", "type": "Задание", "status": "Backlog", "done": false},
    {"key": "MDI-74", "summary": "P4-4 — Emit PlanSpec to desired state", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-75", "summary": "P4-4a — Tech debt: plan_version persist mismatch", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-76", "summary": "P2-5a — Bug: migration role_permissions seed", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-77", "summary": "P4-5 — Warm pool + predictive prewarm", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-78", "summary": "P4-6 — Node.js compat host (legacy nodes)", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-79", "summary": "P4-G — GATE: flows-signed image-warm invoke", "type": "Задание", "status": "Готово", "done": true},
  ],
  "MDI-6": [
    {"key": "MDI-80", "summary": "P5-1 — KEDA ScaledObjects per function", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-81", "summary": "P5-2 — Durable execution: WAL/idempotency/outbox", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-82", "summary": "P5-2i — Live durable store (infra)", "type": "Задание", "status": "Backlog", "done": false},
    {"key": "MDI-83", "summary": "P5-3 — Partitioned ownership", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-84", "summary": "P5-4 — Durable Join barrier + branch idempotency", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-85", "summary": "P5-5 — Notification pipeline + DLQ", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-86", "summary": "P5-G — GATE: scale-to-zero + crash-safe replay", "type": "Задание", "status": "Готово", "done": true},
  ],
  "MDI-7": [
    {"key": "MDI-87", "summary": "P6-1 — OTel to Prometheus/Jaeger/Grafana", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-88", "summary": "P6-1a — Tech debt: tenant-scope bypass", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-89", "summary": "P6-2 — Usage metering (off hot path)", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-90", "summary": "P6-3 — React dashboard metrics/logs/traces", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-91", "summary": "P6-4 — React: DLQ browser + replay", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-92", "summary": "P6-5 — Append-only tamper-evident audit log", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-93", "summary": "P6-5a — Bug: verifyChain JSONB false-positive", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-94", "summary": "P6-6 — Live flow visualizer (split)", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-95", "summary": "P6-6a — Plane 1: aggregate topology heatmap", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-96", "summary": "P6-6b-go — Flow Tap ENGINE track", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-97", "summary": "P6-6b-nest — Flow Tap NESTJS track", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-98", "summary": "P6-6b-react — Flow Tap REACT track", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-99", "summary": "P6-G — GATE: observability + metering off hot path", "type": "Задание", "status": "Готово", "done": true},
  ],
  "MDI-8": [
    {"key": "MDI-100", "summary": "P7-1 — Marketplace registry + publish/install", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-101", "summary": "P7-2 — Polyglot FDK konformans harness", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-102", "summary": "P7-3 — GitOps publisher (NestJS)", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-103", "summary": "P7-4 — Tenant-scoped model catalogue", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-104", "summary": "P7-5 — Edge/WASM tier (Go)", "type": "Задание", "status": "Backlog", "done": false},
  ],
  "MDI-9": [
    {"key": "MDI-105", "summary": "CLI-1 — CLI buyruq sirti (Port gap)", "type": "Задание", "status": "В работе", "done": false},
    {"key": "MDI-106", "summary": "P8-UI-1 — UI hardening/cleanup", "type": "Задание", "status": "Готово", "done": true},
    {"key": "MDI-107", "summary": "P8-INT-1 — Live UI to control-plane integratsiya", "type": "Задание", "status": "В работе", "done": false},
    {"key": "MDI-108", "summary": "P8-INT-2 — Data-plane to control-plane reconcile wiring", "type": "Задание", "status": "В работе", "done": false},
    {"key": "MDI-109", "summary": "P8-INT-3 — Live build/sign + GitOps integratsiya", "type": "Задание", "status": "В работе", "done": false},
    {"key": "MDI-110", "summary": "P8-INT-4 — Flow Tap end-to-end + descope", "type": "Задание", "status": "Backlog", "done": false},
  ],
  "MDI-10": [],
  "BSA-BOARD": [
    {"key": "BSA-3", "summary": "Документация Scoring Клиентов Юр-лиц и ИП", "type": "Задание", "status": "UseCase & User Story", "done": false},
    {"key": "BSA-4", "summary": "Документация для создание договора Escrow", "type": "Задание", "status": "API Integrations", "done": false},
    {"key": "BSA-5", "summary": "Документация для получение статуса по договору Escrow", "type": "Задание", "status": "К выполнению", "done": false}
  ],
  "TD-BOARD": [
    {"key": "TD-303", "summary": "MuamalatPay: php user /srv/project/pay-api/storage/logs/*.l", "type": "История", "status": "TO DO", "done": false},
    {"key": "TD-302", "summary": "BMMS > jarka qo'yish kerak", "type": "История", "status": "Проверка", "done": false},
    {"key": "TD-301", "summary": "Trastpay > BMMS > Yaml update qilish kerak", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-300", "summary": "ДБО: не проходит билд в микросерв", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-299", "summary": "ДБО: на фронте деплой перестал работать", "type": "История", "status": "TO DO", "done": false},
    {"key": "TD-298", "summary": "ДБО: Сделать curl запрос из микросервиса", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-297", "summary": "ДБО: api.trustbank.uz/fpgateway/ zapros yuborilganda 502", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-296", "summary": "Trastpay > QR code > BMMS jarka yuklash", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-295", "summary": "DECO: Kompyerga dostuplarni ochib berish kerak", "type": "История", "status": "TO DO", "done": false},
    {"key": "TD-294", "summary": "Chatbot AI uchun yengi domen yaratib berish kerak", "type": "История", "status": "IN PROGRESS", "done": false},
    {"key": "TD-293", "summary": "DBO-V2 uchun yangi server ochish kerak", "type": "История", "status": "Selected for Development", "done": false},
    {"key": "TD-292", "summary": "Trastpay > BMMS > Yaml update qilish kerak", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-291", "summary": "BMMS jarka qo'yish. QR oplata", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-290", "summary": "Trastpay: OFB product API credentials-ni latest change-larga mos", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-289", "summary": "PG REG TECH uchun Postgres Cluster kotarish", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-288", "summary": "DECO: DBeaver databazasida 192.168.254.7:5432 portga connect", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-287", "summary": "FCI: Foot city базани хафталик backup олиш", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-286", "summary": "ДБО: DBO in domein ga fp-gateway servisini ulab berish kerak", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-285", "summary": "(pg rech tech) shu ikkta serverdan iabs serverlariga connection", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-284", "summary": "need to put the .JAR file to the needed destination", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-283", "summary": "BMMS > jarka qo'yish kerak", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-282", "summary": "ДБО: ДБО ни dump ни олиб бериш", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-281", "summary": "ДБО: wi-fi доступ Алмаз", "type": "История", "status": "Проверка", "done": false},
    {"key": "TD-280", "summary": "ДБО: Нужно дать доступ до repo.packagist.org", "type": "История", "status": "Проверка", "done": false},
    {"key": "TD-279", "summary": "ДБО: При работе с GitLab возникает ошибка", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-278", "summary": "BMMS > jarka qo'yish kerak", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-277", "summary": "ДБО ни DUMPни олиш Сервердаги accessable path га", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-276", "summary": "deploy trastpay-transactions-perform-service", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-275", "summary": "deploy Trastpay-payment-api", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-274", "summary": "Trastpay > BMMS > Yaml update qilish kerak", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-273", "summary": "ДБО: Проверить и восстановить проксирование /api/fl/ в Nginx", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-272", "summary": "Yangi Postgres serverlar uchun Ixtiyor va Yaxyo PAMiga qoshish", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-268", "summary": "ДБО: Необходимо систематизировать сбор логов", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-267", "summary": "BMMS > qr oplata > purpose code o'zgartirish kerak", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-266", "summary": "X-GO: Настройка сетевого доступа", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-265", "summary": "2 TB dan har bitta gnodelarga qoshilgan deco projectida", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-264", "summary": "Trastpay: Mastercard uchun JAR update va bmms.yaml config", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-263", "summary": "Deploy payment api exp", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-262", "summary": "MINIO 172.16.101.1 serverga joy qoshish", "type": "История", "status": "Selected for Development", "done": false},
    {"key": "TD-261", "summary": "AI Chat Serverga dostup ochish kerak", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-260", "summary": "MuamalatPay: Telekom AF ni agentini production serverdan", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-259", "summary": "3 ta server Postrges Cluster uchun 4 CPU 8 RAM 2TB", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-258", "summary": "k8s mongodb ga internet 15 daqiqa", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-257", "summary": "MONGO DB DUMP olishni optimize qilish va dumplarni Minioga", "type": "История", "status": "Проверка", "done": false},
    {"key": "TD-256", "summary": "FCI: Food city проектини ни ограниченный доступ", "type": "История", "status": "Selected for Development", "done": false},
    {"key": "TD-255", "summary": "ДБО: Доступ в Sentry", "type": "История", "status": "Selected for Development", "done": false},
    {"key": "TD-254", "summary": "ДБО: Нужно в env установить (Павел)", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-253", "summary": "ДБО: микросервисс bank в воркере", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-252", "summary": "Optimizing Taking Dump with help of MONGO db for TRASTPAY", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-251", "summary": "fix auto deploy in client-api exp", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-250", "summary": "Открытие доступа для интеграции", "type": "История", "status": "Проверка", "done": false},
    {"key": "TD-249", "summary": "Muamalatpay: Humo Payment va Humo Middleware login nomlarini", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-248", "summary": "Bill Master dan Food City ga 3 ta port ochish", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-247", "summary": "DECO. Masofaviy tizimga kira olish huquqini ochish", "type": "История", "status": "Проверка", "done": false},
    {"key": "TD-246", "summary": "fix auto deploy in client-api exp", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-245", "summary": "deploy client-api prod", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-244", "summary": "adding new variables to .env in client-api", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-243", "summary": "Payment Hub Server Experimantal va production ochish", "type": "История", "status": "Проверка", "done": false},
    {"key": "TD-242", "summary": "Ошибка 404 NOT_FOUND при вызове методов", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-241", "summary": "ДБО: Установить переменные для frontend", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-239", "summary": "DECO. 192.168.254.6 ga dostup ochish", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-238", "summary": "FCI: Pipeline да хатоли бервотти", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-237", "summary": "DECO. Serverga sql querylartni qo'yish kerak", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-236", "summary": "DECO. 192.168.254.7 serveridan fayllarni olib berish", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-235", "summary": "MuamalatPay: Rabbitmq serveridan Muamalat serverlariga dostup", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-234", "summary": "ДБО: Не удается выполнить сборку", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-233", "summary": "trastpay-admin-front master dagi ohirgi ozgarishlani prodga", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-232", "summary": "ДБО: Не удаётся установить Composer-пакет", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-231", "summary": "ДБО: В микросервисе references настроить", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-230", "summary": "ДБО: Проверить для очередей notification", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-229", "summary": "ДБО: В микросервисе notifications добавить", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-228", "summary": "DECO. Klasterni tiklash uchun gnode1/gnode2 serverlarida disk", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-227", "summary": "ДБО: Необходимо развернуть сервис", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-226", "summary": "Create user in Grafana for backend developer [Dony]", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-225", "summary": "Chat Bot AI project Ubuntu Server 4 cpu 16 ram, SSD 80 GB", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-224", "summary": "Logging service deploy qilindi va yengi domen qo'yib berish", "type": "История", "status": "Проверка", "done": false},
    {"key": "TD-223", "summary": "FCI: 172.16.102.85 dan 172.20.21.2 va 172.20.21.5 8080 porta", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-222", "summary": "ДБО: Проверка и запуск pipeline для sms", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-221", "summary": "ДБО: Нужно открыть доступ для a.davr", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-220", "summary": "Logging Service for Middleware", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-219", "summary": "Food city: Prod, exp serverlariga env qo'shish kerak", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-218", "summary": "ofdms-prod.yml update", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-217", "summary": "MuamalatPay Rabbit MQ nastroyka qilish kerak", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-216", "summary": "MuamalatPay dan Groub-IB ni RabbitMQ siga dostup kerak", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-215", "summary": "docs-api ga file-stronge-service ulash", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-214", "summary": "Soliqni ip adresini middleware env ga qo'shish kerak", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-213", "summary": "Dostup ochish kere Trastpay-docs dan Minio ga", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-212", "summary": "ДБО: Бэкендан Group-IB аписига доступ", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-211", "summary": "ДБО: Выяснить и исправить", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-210", "summary": "ДБО: получить env переменные", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-209", "summary": "ДБО: в микросервисе Notification", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-208", "summary": "ДБО: 192.168.18.199 локальный доступ", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-207", "summary": "ДБО: не получается в микросервисе", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-206", "summary": "ДБО: Pipeline падает в микросервисе notifications", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-205", "summary": "ДБО: Архитектурасини тузиб чикиш", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-204", "summary": "ДБО: SDK→ mTLS Proxy га запрос юворвотки", "type": "История", "status": "Проверка", "done": false},
    {"key": "TD-203", "summary": "Trastpay-admin-api-exp ga rasm yuklaganda error bervotti", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-202", "summary": "BM серверида ofdms сервиси нечинчи портда", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-201", "summary": "ДБО: api.trustbank.uz curl вызов клиш кере", "type": "История", "status": "DONE", "done": true},
    {"key": "TD-200", "summary": "ДБО: Group IB серверидан бизани Бэкенд", "type": "История", "status": "DONE", "done": true}
  ]
};
