// Jira issues pre-fetched per epic — generated 2026-06-29 (sync updated 2026-06-29)
window.TB_JIRA_ISSUES = {
  "FC-13": [
    {"key": "FC-3", "summary": "Добавить поле - ФИО", "type": "История", "status": "Backlog", "done": false, "assignee": "Xolikulov Farrux"},
    {"key": "FC-9", "summary": "Cancel - Пул возврати ", "type": "Задание", "status": "Backlog", "done": false, "assignee": "Xolikulov Farrux"},
    {"key": "FC-11", "summary": "Detail page га файл прикрепления кошиш", "type": "Задание", "status": "Backlog", "done": false, "assignee": null},
    {"key": "FC-23", "summary": "QR генерация хар бир объект учун", "type": "Задание", "status": "Backlog", "done": false, "assignee": null}
  ],
  "FC-14": [
    {"key": "FC-8", "summary": "Толовларга Rabbit кошиш", "type": "Задание", "status": "Backlog", "done": false, "assignee": null},
    {"key": "FC-15", "summary": "Anorga интеграция", "type": "История", "status": "Backlog", "done": false, "assignee": null},
    {"key": "FC-16", "summary": "Error handle", "type": "История", "status": "Backlog", "done": false, "assignee": null}
  ],
  "FC-30": [
    {"key": "FC-4", "summary": "Tarif - Ойлик ва кунлик расталар болиб чикиш", "type": "История", "status": "in dev", "done": false, "assignee": "Xolikulov Farrux"},
    {"key": "FC-6", "summary": "Auto Fill - толов вактида ", "type": "История", "status": "Ready for dev", "done": false, "assignee": "Xolikulov Farrux"},
    {"key": "FC-10", "summary": "Check Api - Такрорий толов block ", "type": "Задание", "status": "Готово", "done": true, "assignee": "Xolikulov Farrux"},
    {"key": "FC-12", "summary": "Таблицада раста нархларини чкариб койиш", "type": "Задание", "status": "Ready for dev", "done": false, "assignee": "Xolikulov Farrux"}
  ],
  "FC-32": [
    {"key": "FC-33", "summary": "Видео Аналитика(AI)", "type": "Задание", "status": "Backlog", "done": false, "assignee": null}
  ],
  "KT-25": [],
  "KT-26": [],
  "KT-27": [
    {"key": "KT-11", "summary": "Back: Push уведомления для платежных операции", "type": "История", "status": "Backlog", "done": false, "assignee": "Davranbekov Almazbek"}
  ],
  "KT-28": [],
  "KT-29": [
    {"key": "KT-35", "summary": "Mobile: Android da User ID yuborilmayapti", "type": "Баг", "status": "Blocked", "done": false, "assignee": "Umarov Ulug'bek"},
    {"key": "KT-36", "summary": "Back: API реализация для 2 метода malware", "type": "История", "status": "Готово", "done": true, "assignee": "Axmadov Dilmurod"},
    {"key": "KT-37", "summary": "Mobile: Malware API Integration", "type": "История", "status": "in dev", "done": false, "assignee": "Umarov Ulug'bek"},
    {"key": "KT-135", "summary": "Front: Session_Id не отправляется", "type": "Баг", "status": "Готово", "done": true, "assignee": "G'ayratov Ismoil"},
    {"key": "KT-136", "summary": "Mobile: Добавить тестовое приложение для проверки blacklist API", "type": "История", "status": "Готово", "done": true, "assignee": "Umarov Ulug'bek"}
  ],
  "KT-30": [
    {"key": "KT-6", "summary": "Создание сессии идентификации клиента", "type": "История", "status": "Готово", "done": true, "assignee": "Pankin Pavel"},
    {"key": "KT-156", "summary": "Проверка статуса сессии идентификации", "type": "Задача", "status": "Готово", "done": true, "assignee": "Pankin Pavel"},
    {"key": "KT-157", "summary": "Настроить проксирование от mTLS до GCI сервисов ", "type": "Задача", "status": "Готово", "done": true, "assignee": null},
    {"key": "KT-158", "summary": "Интегрировать SDK от GCI ", "type": "Задача", "status": "Готово", "done": true, "assignee": "Umarov Ulug'bek"},
    {"key": "KT-159", "summary": "Проверка работы enpoint", "type": "Задача", "status": "Backlog", "done": false, "assignee": "Pankin Pavel"},
    {"key": "KT-160", "summary": "Реализовать логику перехвата ответа GCI об идентификации", "type": "Задача", "status": "Backlog", "done": false, "assignee": null},
    {"key": "KT-161", "summary": "Выяснить по какой причине запросы на метод возвращают ответ 404", "type": "Задача", "status": "Backlog", "done": false, "assignee": null},
    {"key": "KT-162", "summary": "Убедиться что ответ после идентификации не возвращает данные пользователя ", "type": "Задача", "status": "Backlog", "done": false, "assignee": "Umarov Ulug'bek"},
    {"key": "KT-163", "summary": "Использовать метод /gci/sessions/{session_id}", "type": "Задача", "status": "Backlog", "done": false, "assignee": "Umarov Ulug'bek"}
  ],
  "KT-31": [],
  "KT-32": [],
  "KT-33": [],
  "KT-34": [
    {"key": "KT-10", "summary": "Back: В случае если проводка удалена нужно синхронизировать статус", "type": "История", "status": "Documentation", "done": false, "assignee": "Pankin Pavel"}
  ],
  "MDI-10": [
    {"key": "MDI-111", "summary": "A1 — Stage-6 QA Linuxda", "type": "История", "status": "Готово", "done": true, "assignee": null},
    {"key": "MDI-112", "summary": "A2 — Stage-5 review qoldighi", "type": "История", "status": "Готово", "done": true, "assignee": null},
    {"key": "MDI-113", "summary": "B3 — NestJS build mijoz", "type": "История", "status": "Готово", "done": true, "assignee": null},
    {"key": "MDI-114", "summary": "B4 — Live build/runner drayverlar", "type": "История", "status": "Backlog", "done": false, "assignee": null},
    {"key": "MDI-115", "summary": "B5 — GitOps live", "type": "История", "status": "В работе", "done": false, "assignee": null},
    {"key": "MDI-116", "summary": "B6 — Kafka/Rabbit haqiqiy adapterlar", "type": "История", "status": "Backlog", "done": false, "assignee": null},
    {"key": "MDI-117", "summary": "B7 — Flow Tap uchma-uch", "type": "История", "status": "Backlog", "done": false, "assignee": null}
  ],
  "MDI-9": [
    {"key": "MDI-105", "summary": "CLI-1 — CLI buyruq sirti (Port gap)", "type": "История", "status": "В работе", "done": false, "assignee": null},
    {"key": "MDI-106", "summary": "P8-UI-1 — UI hardening/cleanup", "type": "История", "status": "Готово", "done": true, "assignee": null},
    {"key": "MDI-107", "summary": "P8-INT-1 — Live UI to control-plane integratsiya", "type": "История", "status": "В работе", "done": false, "assignee": null},
    {"key": "MDI-108", "summary": "P8-INT-2 — Data-plane to control-plane reconcile wiring", "type": "История", "status": "В работе", "done": false, "assignee": null},
    {"key": "MDI-109", "summary": "P8-INT-3 — Live build/sign + GitOps integratsiya", "type": "История", "status": "В работе", "done": false, "assignee": null},
    {"key": "MDI-110", "summary": "P8-INT-4 — Flow Tap end-to-end + descope", "type": "История", "status": "Backlog", "done": false, "assignee": null}
  ],
  "MW-2": [],
  "MW-3": [
    {"key": "MW-4", "summary": "Разработка API для перевода со счета на карту в рамках флоу разделения платежей / X-GO (BM)", "type": "История", "status": "Готово", "done": true, "assignee": "Axmadov Sherzod"},
    {"key": "MW-6", "summary": "X-GO: Интеграция с Uzcard/Humo для добавления карт (OTP/Verify)", "type": "История", "status": "В работе", "done": false, "assignee": "Xabibjonov Jaloliddin"}
  ],
  "MW-5": [],
  "MW-7": [],
  "PH-1": [
    {"key": "PH-2", "summary": "HUMO P2P интеграцияси", "type": "История", "status": "Ready for Test", "done": false, "assignee": "Xabibjonov Jaloliddin"},
    {"key": "PH-3", "summary": "OFD (Солиқ) тизими билан интеграция", "type": "История", "status": "Ready for Test", "done": false, "assignee": "Xabibjonov Jaloliddin"},
    {"key": "PH-4", "summary": "HUMO терминаллари бўйича Reconciliation интеграцияси", "type": "История", "status": "В работе", "done": false, "assignee": "Jabbarov Diyorbek"},
    {"key": "PH-5", "summary": "Uzcard Terminal API (Check/Add/Remove) интеграциясини ишлаб чиқиш", "type": "История", "status": "Ready for Test", "done": false, "assignee": "Xabibjonov Jaloliddin"},
    {"key": "PH-6", "summary": "UZCARD P2P интеграцияси", "type": "История", "status": "В работе", "done": false, "assignee": "Jabbarov Diyorbek"}
  ],
  "SL-100": [
    {"key": "SL-99", "summary": "Add comment in P2P (Android)", "type": "История", "status": "Готово", "done": true, "assignee": "Rasulov Ulugbek"},
    {"key": "SL-106", "summary": "Trastpay > users can use only Mobile network, revoke the using wifi connections", "type": "История", "status": "Готово", "done": true, "assignee": "Alimov Mohirjon"},
    {"key": "SL-115", "summary": "Add comment in P2P (iOS)", "type": "История", "status": "Готово", "done": true, "assignee": "Abdulazim muhammadrafiqov"},
    {"key": "SL-120", "summary": "Trastpay > users can use only Mobile network, revoke the using wifi connections", "type": "История", "status": "Готово", "done": true, "assignee": "Valixonov Baxtiyor"},
    {"key": "SL-121", "summary": "Trastpay > users can use only Mobile network, revoke the using wifi connections", "type": "История", "status": "Готово", "done": true, "assignee": "Abdulazim muhammadrafiqov"},
    {"key": "SL-122", "summary": "Add new comment to the P2P (Android)", "type": "История", "status": "Готово", "done": true, "assignee": "Valixonov Baxtiyor"},
    {"key": "SL-123", "summary": "Add new comment to the P2P (iOS)", "type": "История", "status": "Готово", "done": true, "assignee": "Abdulazim muhammadrafiqov"},
    {"key": "SL-160", "summary": "20 - Zararli dastur yoki masofadan boshqaruv aniqlanganda SMS-xabarnoma yuborish", "type": "История", "status": "IN ANALYSIS", "done": false, "assignee": null},
    {"key": "SL-164", "summary": "60 - Ilova ishga tushganda qurilma xavfsizligini tekshirish va salbiy holatda ilovani bloklash + SMS yuborish", "type": "История", "status": "IN ANALYSIS", "done": false, "assignee": null},
    {"key": "SL-176", "summary": "[back]  Проверка совпадения ПИНФЛ и номера телефона", "type": "История", "status": "К выполнению", "done": false, "assignee": "Toxirov Sarvar"},
    {"key": "SL-178", "summary": "[flutter]  Проверка совпадения ПИНФЛ и номера телефона", "type": "История", "status": "Готово", "done": true, "assignee": "Rasulov Ulugbek"},
    {"key": "SL-186", "summary": "ЦБ so'ragan ma'lumotlarni bazadan olib berish", "type": "История", "status": "Готово", "done": true, "assignee": "Toxirov Sarvar"},
    {"key": "SL-256", "summary": "Интеграция с сервисом Xolis", "type": "История", "status": "IN ANALYSIS", "done": false, "assignee": "Inatullayev Jaxongir"},
    {"key": "SL-258", "summary": "Валютный Вклад \"Qulay sarmoya\"", "type": "История", "status": "К выполнению", "done": false, "assignee": "Inatullayev Jaxongir"},
    {"key": "SL-259", "summary": "возврат платежа МУНИС", "type": "История", "status": "К выполнению", "done": false, "assignee": "Inatullayev Jaxongir"},
    {"key": "SL-262", "summary": "dinamic QR не притягивает сумму ", "type": "Баг", "status": "IN QA", "done": false, "assignee": "Babajanov Abdulaziz"},
    {"key": "SL-275", "summary": "в БМ нужно добавить параметр", "type": "Задание", "status": "IN DEV", "done": false, "assignee": "Jabbarov Diyorbek"}
  ],
  "SL-103": [
    {"key": "SL-102", "summary": "Add check-request to Create-customer", "type": "История", "status": "Готово", "done": true, "assignee": "Toxirov Sarvar"},
    {"key": "SL-143", "summary": "Flutter | Bug Fixing", "type": "История", "status": "Готово", "done": true, "assignee": "Mirzabayev Damir"},
    {"key": "SL-179", "summary": "[flutter] FIX client auth header. user-agent", "type": "История", "status": "Готово", "done": true, "assignee": "Umarov Ulug'bek"},
    {"key": "SL-182", "summary": "40,90 statusi tori kelmayabti karta qoshvotganda", "type": "Баг", "status": "К выполнению", "done": false, "assignee": "Yodgorov Alibek"},
    {"key": "SL-184", "summary": "Картани пин-кодини сет клиш методини кошиб бериш (Момент кард)", "type": "Баг", "status": "К выполнению", "done": false, "assignee": null},
    {"key": "SL-183", "summary": "эксп ва прод-да ассетсни жавоби хархил", "type": "Баг", "status": "Готово", "done": true, "assignee": null},
    {"key": "SL-190", "summary": "Notification bormasligini tekshirish, testiviy accountga. Phone: 909756057", "type": "История", "status": "К выполнению", "done": false, "assignee": "Toxirov Sarvar"},
    {"key": "SL-200", "summary": "add card images", "type": "История", "status": "К выполнению", "done": false, "assignee": "Valixonov Baxtiyor"},
    {"key": "SL-202", "summary": "Правильно отображать погашения по графику и еж.месячный платеж", "type": "Баг", "status": "Готово", "done": true, "assignee": "Alimov Mohirjon"},
    {"key": "SL-206", "summary": "Правильно отображать на главном списке кредитов сумму просроченного платежа", "type": "Баг", "status": "К выполнению", "done": false, "assignee": "Alimov Mohirjon"},
    {"key": "SL-207", "summary": "Отобразить сумму следующего месяца платежа на окне \"Детали кредита\"", "type": "Баг", "status": "К выполнению", "done": false, "assignee": "Alimov Mohirjon"},
    {"key": "SL-209", "summary": "Уведомления приходит на английском языке", "type": "Баг", "status": "К выполнению", "done": false, "assignee": "Toxirov Sarvar"},
    {"key": "SL-211", "summary": "в погашении кредита не приходит typePay и Tranzit", "type": "Баг", "status": "К выполнению", "done": false, "assignee": "Toxirov Sarvar"},
    {"key": "SL-217", "summary": "Icon image'lar cashirovanie qilish kerak", "type": "История", "status": "Готово", "done": true, "assignee": "Rasulov Ulugbek"},
    {"key": "SL-219", "summary": "[Flutter] Avto rassrochka", "type": "История", "status": "Готово", "done": true, "assignee": "Rasulov Ulugbek"},
    {"key": "SL-224", "summary": "Identification > case: Error message chiqarish kerak", "type": "История", "status": "Готово", "done": true, "assignee": "Toxirov Sarvar"},
    {"key": "SL-225", "summary": "\"Exchange\" при обмене на визу карту, не передается \"pan\" карты VISA", "type": "Баг", "status": "К выполнению", "done": false, "assignee": "Yodgorov Alibek"},
    {"key": "SL-226", "summary": "Omonot > History ko'rinmayapti", "type": "Баг", "status": "Готово", "done": true, "assignee": "Rasulov Ulugbek"},
    {"key": "SL-229", "summary": "В чеке оплаты по Budget показывает некорректную сумму", "type": "Баг", "status": "Готово", "done": true, "assignee": "Rasulov Ulugbek"},
    {"key": "SL-231", "summary": "\"Anti-fraud\" - внедрить алгоритм для обхода 1-минутной ошибки", "type": "Задание", "status": "К выполнению", "done": false, "assignee": "Valixonov Baxtiyor"},
    {"key": "SL-232", "summary": "Operation not faund ошибка при попытке перевести между счетами", "type": "Баг", "status": "К выполнению", "done": false, "assignee": "Akramxo'jayev Muhammadrasul"},
    {"key": "SL-233", "summary": "Добавить апи для смены пин-кода", "type": "Задание", "status": "К выполнению", "done": false, "assignee": null},
    {"key": "SL-234", "summary": "Подготовка к релизу платформы Андроид \"3.0.37\"", "type": "Задание", "status": "Готово", "done": true, "assignee": "Mirzabayev Damir"},
    {"key": "SL-235", "summary": "История платежей статусы платежей не обновляются", "type": "Баг", "status": "К выполнению", "done": false, "assignee": null},
    {"key": "SL-236", "summary": "Чеклардеги, вахтни тогри такдиг этиш", "type": "Баг", "status": "К выполнению", "done": false, "assignee": null},
    {"key": "SL-238", "summary": "A2A > Text UX ga to'ri holatda mobilkaga berilishi kerak", "type": "Баг", "status": "Готово", "done": true, "assignee": "Akramxo'jayev Muhammadrasul"},
    {"key": "SL-240", "summary": "Virtual kartadan > koshelekga pul o'tmayapti", "type": "Баг", "status": "Готово", "done": true, "assignee": "Babajanov Abdulaziz"},
    {"key": "SL-241", "summary": "Chekda 'komissiya miqdori' xato ko'rsatvotti", "type": "Баг", "status": "Готово", "done": true, "assignee": "Alimov Mohirjon"},
    {"key": "SL-248", "summary": "SMS shablon qo'shish", "type": "Задание", "status": "Готово", "done": true, "assignee": "Akramxo'jayev Muhammadrasul"},
    {"key": "SL-260", "summary": "notificationda broadcast-notification paytida microservice qotbqovotti", "type": "Баг", "status": "IN DEV", "done": false, "assignee": "Alimov Mohirjon"},
    {"key": "SL-261", "summary": "Chekda 'komissiya miqdori' xato ko'rsatvotti [budget tolov]", "type": "Баг", "status": "Готово", "done": true, "assignee": "Alimov Mohirjon"},
    {"key": "SL-265", "summary": "A2A > bind qilishda filtr olib tashlash kerak", "type": "Задание", "status": "READY TO QA", "done": false, "assignee": "Akramxo'jayev Muhammadrasul"},
    {"key": "SL-266", "summary": "A2A > bind check ishlamayapti", "type": "Баг", "status": "IN QA", "done": false, "assignee": "Akramxo'jayev Muhammadrasul"},
    {"key": "SL-267", "summary": "trastpaydan iABS ga, transaction metodiga cheksiz zapros tashalvotti har kuni. Loop ni to'xtatish kerak", "type": "Задание", "status": "К выполнению", "done": false, "assignee": "Toxirov Sarvar"},
    {"key": "SL-268", "summary": "A2A > poluchatel kartasida select button'ni FIX qilib qo'yish kerak", "type": "История", "status": "IN QA", "done": false, "assignee": "Babajanov Abdulaziz"},
    {"key": "SL-271", "summary": "При сканере QR-кода не переходит на следующий page", "type": "Баг", "status": "Готово", "done": true, "assignee": "Babajanov Abdulaziz"},
    {"key": "SL-272", "summary": "Иловага виртуал картасини кушомиетти", "type": "Задание", "status": "Готово", "done": true, "assignee": "Yokubjonov Azizjon"},
    {"key": "SL-276", "summary": "A2A > bind_phone_wallet > unknown error", "type": "Баг", "status": "IN ANALYSIS", "done": false, "assignee": "Akramxo'jayev Muhammadrasul"}
  ],
  "SL-203": [
    {"key": "SL-138", "summary": "Drag Metal (Oltin depozit)", "type": "История", "status": "К выполнению", "done": false, "assignee": "Mirzabayev Damir"},
    {"key": "SL-140", "summary": "Add card - analogue: ANOR", "type": "История", "status": "К выполнению", "done": false, "assignee": null},
    {"key": "SL-168", "summary": "Visa direct", "type": "История", "status": "К выполнению", "done": false, "assignee": null},
    {"key": "SL-170", "summary": "Paynet > Кредит погашение", "type": "История", "status": "К выполнению", "done": false, "assignee": null},
    {"key": "SL-171", "summary": "Urban drive", "type": "История", "status": "К выполнению", "done": false, "assignee": null},
    {"key": "SL-174", "summary": "Remove 1 hour block for adding virtual Visa/Mastercard", "type": "История", "status": "К выполнению", "done": false, "assignee": "Inatullayev Jaxongir"},
    {"key": "SL-204", "summary": "Humo moment card", "type": "История", "status": "К выполнению", "done": false, "assignee": null},
    {"key": "SL-208", "summary": "Tez QR", "type": "История", "status": "К выполнению", "done": false, "assignee": null},
    {"key": "SL-218", "summary": "Humo / Visa cobadge kartalarda cvv ko’rsatish", "type": "История", "status": "К выполнению", "done": false, "assignee": null},
    {"key": "SL-242", "summary": "AFIN card", "type": "История", "status": "К выполнению", "done": false, "assignee": null},
    {"key": "SL-244", "summary": "EWA (Earned wage success)", "type": "История", "status": "К выполнению", "done": false, "assignee": null},
    {"key": "SL-245", "summary": "Оплата на места", "type": "История", "status": "К выполнению", "done": false, "assignee": null},
    {"key": "SL-246", "summary": "Емиссия ПК через трастпаи", "type": "История", "status": "К выполнению", "done": false, "assignee": null},
    {"key": "SL-247", "summary": "Steam оплата", "type": "История", "status": "К выполнению", "done": false, "assignee": null},
    {"key": "SL-249", "summary": "Camera card scan", "type": "История", "status": "К выполнению", "done": false, "assignee": null},
    {"key": "SL-250", "summary": "Буквенно-цифровой OTP-код", "type": "История", "status": "К выполнению", "done": false, "assignee": null},
    {"key": "SL-251", "summary": "Изучение системы Alipay", "type": "История", "status": "К выполнению", "done": false, "assignee": null},
    {"key": "SL-254", "summary": "Проверка владельца номера телефона", "type": "История", "status": "К выполнению", "done": false, "assignee": null}
  ],
  "SL-243": [],
  "SL-252": [],
  "SL-253": [
    {"key": "SL-257", "summary": "Льготная ипотека «Мой дом» (Mening Uyim ТСЧЖ)", "type": "История", "status": "IN QA", "done": false, "assignee": "Inatullayev Jaxongir"}
  ],
  "TB-12": [
    {"key": "TB-24", "summary": "Env konfiguratsiya + fail-fast validatsiya", "type": "Задание", "status": "ready for dev", "done": false, "assignee": "Sattarov Ravshan"},
    {"key": "TB-25", "summary": "Strukturali JSON logging + PII masking", "type": "Задание", "status": "Documentation", "done": false, "assignee": "Sattarov Ravshan"},
    {"key": "TB-26", "summary": "Global HTTP kontrakt (ValidationPipe + envelope)", "type": "Задание", "status": "backlog", "done": false, "assignee": "Sattarov Ravshan"},
    {"key": "TB-27", "summary": "X-Correlation-ID middleware", "type": "Задание", "status": "backlog", "done": false, "assignee": "Sattarov Ravshan"},
    {"key": "TB-28", "summary": "App bootstrap + Swagger + Health", "type": "Задание", "status": "backlog", "done": false, "assignee": "Sattarov Ravshan"},
    {"key": "TB-29", "summary": "Queue infra + worker skeleti", "type": "Задание", "status": "backlog", "done": false, "assignee": "Sattarov Ravshan"},
    {"key": "TB-30", "summary": "Observability wiring (OTel + Sentry)", "type": "Задание", "status": "backlog", "done": false, "assignee": "Sattarov Ravshan"}
  ],
  "TB-14": [
    {"key": "TB-31", "summary": "SMS-OTP oqimi", "type": "Задание", "status": "backlog", "done": false, "assignee": "Sattarov Ravshan"},
    {"key": "TB-32", "summary": "Login + refresh + parol tiklash", "type": "Задание", "status": "backlog", "done": false, "assignee": "Sattarov Ravshan"},
    {"key": "TB-33", "summary": "JWT sessiya + logout blacklist", "type": "Задание", "status": "backlog", "done": false, "assignee": "Sattarov Ravshan"},
    {"key": "TB-34", "summary": "JwtAuthGuard + @CurrentUser ni api'da chiqarish", "type": "Задание", "status": "backlog", "done": false, "assignee": "Sattarov Ravshan"},
    {"key": "TB-35", "summary": "To'liq registratsiya", "type": "Задание", "status": "backlog", "done": false, "assignee": "Sattarov Ravshan"}
  ],
  "TB-15": [
    {"key": "TB-36", "summary": "Kompaniya tanlash + ruxsatlar endpointlari", "type": "Задание", "status": "backlog", "done": false, "assignee": "Sattarov Ravshan"},
    {"key": "TB-37", "summary": "Modul-darajali RBAC guard", "type": "Задание", "status": "backlog", "done": false, "assignee": "Sattarov Ravshan"},
    {"key": "TB-38", "summary": "Imzo siyosati servisi", "type": "Задание", "status": "backlog", "done": false, "assignee": "Sattarov Ravshan"},
    {"key": "TB-39", "summary": "Settings endpointlari", "type": "Задание", "status": "backlog", "done": false, "assignee": "Sattarov Ravshan"},
    {"key": "TB-40", "summary": "Self-service profil", "type": "Задание", "status": "backlog", "done": false, "assignee": "Sattarov Ravshan"}
  ],
  "TB-16": [
    {"key": "TB-41", "summary": "References modulini yaratish (4 endpoint + lookup)", "type": "Задание", "status": "Готово", "done": true, "assignee": "Saidiy Jahongir"},
    {"key": "TB-42", "summary": "Seed infratuzilmasi + bazaviy data", "type": "Задание", "status": "in dev", "done": false, "assignee": "Saidiy Jahongir"},
    {"key": "TB-43", "summary": "To'liq MFO + to'lov maqsadi data importi", "type": "Задание", "status": "backlog", "done": false, "assignee": "Saidiy Jahongir"}
  ],
  "TB-17": [
    {"key": "TB-44", "summary": "Gateway auth + token boshqaruvi", "type": "Задание", "status": "in dev", "done": false, "assignee": "Axmadov Dilmurod"},
    {"key": "TB-45", "summary": "Hisob raqamlar va hisoblar servisi", "type": "Задание", "status": "backlog", "done": false, "assignee": "Axmadov Dilmurod"},
    {"key": "TB-46", "summary": "Tranzaksiya yaratish + poll + idempotentlik", "type": "Задание", "status": "backlog", "done": false, "assignee": "Axmadov Dilmurod"},
    {"key": "TB-47", "summary": "ABS ma'lumotnoma (dictionary)", "type": "Задание", "status": "backlog", "done": false, "assignee": "Axmadov Dilmurod"},
    {"key": "TB-48", "summary": "audit + circuit breaker", "type": "Задание", "status": "backlog", "done": false, "assignee": "Axmadov Dilmurod"},
    {"key": "TB-49", "summary": "ABS status - DocumentStatus mapping", "type": "Задание", "status": "backlog", "done": false, "assignee": "Axmadov Dilmurod"}
  ],
  "TB-18": [
    {"key": "TB-50", "summary": "Hisoblar ro'yxati + ko'chirma + eksport", "type": "Задание", "status": "backlog", "done": false, "assignee": "Axmadov Dilmurod"},
    {"key": "TB-51", "summary": "Dashboard + imzolanmagan hujjatlar", "type": "Задание", "status": "backlog", "done": false, "assignee": "Axmadov Dilmurod"},
    {"key": "TB-52", "summary": "To'lov draftini yaratish (idempotent)", "type": "Задание", "status": "backlog", "done": false, "assignee": "Axmadov Dilmurod"},
    {"key": "TB-53", "summary": "To'lovni validatsiya qilish", "type": "Задание", "status": "backlog", "done": false, "assignee": "Axmadov Dilmurod"},
    {"key": "TB-54", "summary": "Imzolash va bankka yuborish", "type": "Задание", "status": "backlog", "done": false, "assignee": "Axmadov Dilmurod"},
    {"key": "TB-55", "summary": "To'lovlar ro'yxati (filtr)", "type": "Задание", "status": "backlog", "done": false, "assignee": "Axmadov Dilmurod"},
    {"key": "TB-56", "summary": "To'lov shablonlari CRUD", "type": "Задание", "status": "backlog", "done": false, "assignee": "Axmadov Dilmurod"},
    {"key": "TB-57", "summary": "Draftlar ro'yxati va saqlash", "type": "Задание", "status": "backlog", "done": false, "assignee": "Axmadov Dilmurod"}
  ],
  "TB-19": [
    {"key": "TB-58", "summary": "Hujjatlar ro'yxati + tafsilot (status tarixi)", "type": "Задание", "status": "backlog", "done": false, "assignee": "Axmadov Dilmurod"},
    {"key": "TB-59", "summary": "Qayta yuborish + bekor qilish", "type": "Задание", "status": "backlog", "done": false, "assignee": "Axmadov Dilmurod"},
    {"key": "TB-60", "summary": "Kvitansiya: real PDF + MinIO", "type": "Задание", "status": "backlog", "done": false, "assignee": "Axmadov Dilmurod"}
  ],
  "TB-20": [
    {"key": "TB-61", "summary": "Dispatch pipeline + kanal portlari", "type": "Задание", "status": "backlog", "done": false, "assignee": "Saidiy Jahongir"},
    {"key": "TB-62", "summary": "RabbitMQ consumer (worker)", "type": "Задание", "status": "backlog", "done": false, "assignee": "Saidiy Jahongir"},
    {"key": "TB-63", "summary": "Bildirishnomalar ro'yxati", "type": "Задание", "status": "backlog", "done": false, "assignee": "Saidiy Jahongir"},
    {"key": "TB-64", "summary": "Bildirishnoma sozlamalari", "type": "Задание", "status": "backlog", "done": false, "assignee": "Saidiy Jahongir"},
    {"key": "TB-65", "summary": "Producer publish: bank - RabbitMQ", "type": "Задание", "status": "backlog", "done": false, "assignee": "Saidiy Jahongir"},
    {"key": "TB-66", "summary": "Centrifugo (WS) + FCM (push) real adapterlari", "type": "Задание", "status": "backlog", "done": false, "assignee": "Saidiy Jahongir"}
  ],
  "TB-21": [
    {"key": "TB-67", "summary": "Kontragent CRUD + soft delete", "type": "Задание", "status": "backlog", "done": false, "assignee": "Saidiy Jahongir"},
    {"key": "TB-68", "summary": "INN qidiruv + primary autofill", "type": "Задание", "status": "backlog", "done": false, "assignee": "Saidiy Jahongir"},
    {"key": "TB-69", "summary": "Ierarxik kontragent guruhlari", "type": "Задание", "status": "backlog", "done": false, "assignee": "Saidiy Jahongir"},
    {"key": "TB-70", "summary": "GNK lookup + sync (port + stub)", "type": "Задание", "status": "backlog", "done": false, "assignee": "Saidiy Jahongir"},
    {"key": "TB-71", "summary": "Real GNK adapteri", "type": "Задание", "status": "backlog", "done": false, "assignee": "Saidiy Jahongir"}
  ],
  "TB-22": [
    {"key": "TB-72", "summary": "Integratsiyalar holatini ko'rsatish", "type": "Задание", "status": "backlog", "done": false, "assignee": "Saidiy Jahongir"},
    {"key": "TB-73", "summary": "Webhook key larini berish (xavfsiz)", "type": "Задание", "status": "backlog", "done": false, "assignee": "Saidiy Jahongir"},
    {"key": "TB-74", "summary": "Kiruvchi webhook'ni tekshirish endpointi", "type": "Задание", "status": "backlog", "done": false, "assignee": "Saidiy Jahongir"},
    {"key": "TB-75", "summary": "Integratsiya provisioning + real sync", "type": "Задание", "status": "backlog", "done": false, "assignee": "Saidiy Jahongir"}
  ],
  "TB-23": [
    {"key": "TB-76", "summary": "Har modul uchun e2e qamrov", "type": "Задание", "status": "backlog", "done": false, "assignee": "Saidiy Jahongir"},
    {"key": "TB-77", "summary": "Rol-asosli UAT stsenariylari", "type": "Задание", "status": "backlog", "done": false, "assignee": "Saidiy Jahongir"},
    {"key": "TB-78", "summary": "Pilot + monitoring", "type": "Задание", "status": "backlog", "done": false, "assignee": "Saidiy Jahongir"}
  ],
  "TB-79": [
    {"key": "TB-80", "summary": "CI gate (Node 20) + pnpm audit", "type": "Задание", "status": "backlog", "done": false, "assignee": "Sattarov Ravshan"},
    {"key": "TB-81", "summary": "secret-store + skan", "type": "Задание", "status": "backlog", "done": false, "assignee": "Sattarov Ravshan"},
    {"key": "TB-82", "summary": "prom-client metrika (C-modullar)", "type": "Задание", "status": "backlog", "done": false, "assignee": "Saidiy Jahongir"},
    {"key": "TB-83", "summary": "Audit log", "type": "Задание", "status": "backlog", "done": false, "assignee": "Sattarov Ravshan"},
    {"key": "TB-84", "summary": "Monitoring (Sentry + Grafana)", "type": "Задание", "status": "backlog", "done": false, "assignee": "Sattarov Ravshan"}
  ],
  "FC-29": [
    {"key": "FC-1", "summary": "Соликга хисобод кетиши хар бир толов бойича", "type": "Задание", "status": "Готово", "done": true, "assignee": null}
  ],
  "FC-31": [
    {"key": "FC-48", "summary": "Сводная статистика платежей", "type": "Задание", "status": "Готово", "done": true, "assignee": "Jo'raboyev Axmadillo"},
    {"key": "FC-46", "summary": "Фискальные отчеты (API)", "type": "Задание", "status": "Готово", "done": true, "assignee": "Jo'raboyev Axmadillo"},
    {"key": "FC-45", "summary": "Фискальный дашборд", "type": "Задание", "status": "Готово", "done": true, "assignee": "Jo'raboyev Axmadillo"},
    {"key": "FC-24", "summary": "Анализ DSQ учун", "type": "История", "status": "Готово", "done": true, "assignee": "Xolikulov Farrux"}
  ],
  "KT-24": [],
  "MDI-1": [
    {"key": "MDI-33", "summary": "D-26 — Declared-ref cross-env scope", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-32", "summary": "D-25 — Per-env overlay vs build-once", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-31", "summary": "D-24 — Per-env generation source-of-truth", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-30", "summary": "D-23 — Hybrid custom-roles RBAC", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-29", "summary": "D-21 — Collaborative designer qarori", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-28", "summary": "D-20 — DevOps developer loop", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-27", "summary": "D-18 — In-house version registry + lockfile", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-26", "summary": "D-17 — Environments + Promotion", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-25", "summary": "D-15a — Loop primitive", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-24", "summary": "D-14 — Workspace delete vs audit FK", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-23", "summary": "D-13 — Node.js node-host compat", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-22", "summary": "D-12 — Generation vs build plan_version", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-21", "summary": "D-11 — Konformans opt-in markerlar", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-20", "summary": "D-10 — Sync-reply correlation", "type": "История", "status": "Backlog", "done": false, "assignee": null},
    {"key": "MDI-19", "summary": "D-9 — Decode kontrakt doc qayta yozish", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-18", "summary": "D-8 — SLO/errors", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-17", "summary": "D-7 — Edge/WASM tier", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-16", "summary": "D-6 — Functional nodes", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-15", "summary": "D-5 — GitOps + tashqi CI/CD kontrakti", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-14", "summary": "D-4 — Polyglot FDK matrisa + ABI (ADR)", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-13", "summary": "D-3 — Marketplace doc + ADR", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-12", "summary": "D-2 — Alternative loyihalarni organish", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-11", "summary": "D-1 — Documentatsiya taxlash, requirementlarni analiz qilish", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"}
  ],
  "MDI-2": [
    {"key": "MDI-34", "summary": "P1-1a — Monorepo scaffold", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-35", "summary": "P1-1b — CI + lint + build matrix", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-36", "summary": "P1-2 — Postgres sxema + migratsiyalar", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-37", "summary": "P1-3 — NestJS skeleton CRUD", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-38", "summary": "P1-4 — Auth/RBAC: SSO/OIDC + MFA", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-39", "summary": "P1-5 — Workspace API key/secret", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-40", "summary": "P1-6 — Go gateway: ingress + key validatsiya", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-41", "summary": "P1-7 — Go runner pool", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-42", "summary": "P1-8 — Docker driver + abstraction", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-43", "summary": "P1-6b — Tech debt: key-verify HTTP to gRPC", "type": "История", "status": "Backlog", "done": false, "assignee": null}
  ],
  "MDI-3": [
    {"key": "MDI-44", "summary": "P1-8c — Tech debt: Docker SDK migratsiya", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-45", "summary": "P1-4a — Bug: mfa.service otplib tsc fail", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-46", "summary": "P1-9 — fn-format UDS ABI verbatim", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-47", "summary": "P1-10 — Per-key rate limit + IP allow/deny", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-48", "summary": "P1-G — GATE: auth + CRUD + invoke", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-49", "summary": "P2-1 — Event bus (Kafka/NATS)", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-50", "summary": "P2-2 — Actor-per-node engine", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-51", "summary": "P2-2a — Bug: shutdown channel race", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-52", "summary": "P2-3 — Backpressure ladder", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-53", "summary": "P2-4 — Inline fusion + DAG walk + routing", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-54", "summary": "P2-5 — Declarative reconcile kontrakti", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-55", "summary": "P2-6 — React designer: DAG canvas", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-56", "summary": "P2-7 — React: folder tree", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-57", "summary": "P2-G — GATE: backpressure bilan flow", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-58", "summary": "P3-1 — Adapter SDK Go kontrakti", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-59", "summary": "P3-2 — In-tree adapterlar HTTP/gRPC/GraphQL", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-60", "summary": "P3-2a — Tech debt: GraphQL status klassifikatsiya", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-61", "summary": "P3-2b — Gateway route-group wiring + gRPC streaming", "type": "История", "status": "Backlog", "done": false, "assignee": null},
    {"key": "MDI-62", "summary": "P3-3 — Pull adapterlar Kafka/RabbitMQ", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-63", "summary": "P3-3a — Tech debt: Kafka adapter haqiqiy busga", "type": "История", "status": "Backlog", "done": false, "assignee": null}
  ],
  "MDI-4": [
    {"key": "MDI-64", "summary": "P3-4 — Out-of-tree gRPC sidecar adapter", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-65", "summary": "P3-5 — Leader-elected scheduler", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-66", "summary": "P3-6 — Gateway Route Group", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-67", "summary": "P3-G — GATE: yangi protokol SDK orqali", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-68", "summary": "P4-1 — Build service: validate-classify-plan-compile", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-69", "summary": "P4-1a — Tech debt: flowplan library ajratish", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-70", "summary": "P4-2 — BuildKit image (Go orchestration)", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-71", "summary": "P4-2i — Build-farm runtime (Ops infra)", "type": "История", "status": "Backlog", "done": false, "assignee": null},
    {"key": "MDI-72", "summary": "P4-3 — SBOM+vuln+cosign+SLSA (Go slice)", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-73", "summary": "P4-3i — Signing & registry runtime (Ops infra)", "type": "История", "status": "Backlog", "done": false, "assignee": null}
  ],
  "MDI-5": [
    {"key": "MDI-74", "summary": "P4-4 — Emit PlanSpec to desired state", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-75", "summary": "P4-4a — Tech debt: plan_version persist mismatch", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-76", "summary": "P2-5a — Bug: migration role_permissions seed", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-77", "summary": "P4-5 — Warm pool + predictive prewarm", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-78", "summary": "P4-6 — Node.js compat host (legacy nodes)", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-79", "summary": "P4-G — GATE: flows-signed image-warm invoke", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-80", "summary": "P5-1 — KEDA ScaledObjects per function", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-81", "summary": "P5-2 — Durable execution: WAL/idempotency/outbox", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-82", "summary": "P5-2i — Live durable store (infra)", "type": "История", "status": "Backlog", "done": false, "assignee": null}
  ],
  "MDI-6": [
    {"key": "MDI-83", "summary": "P5-3 — Partitioned ownership", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-84", "summary": "P5-4 — Durable Join barrier + branch idempotency", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-85", "summary": "P5-5 — Notification pipeline + DLQ", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-86", "summary": "P5-G — GATE: scale-to-zero + crash-safe replay", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-87", "summary": "P6-1 — OTel to Prometheus/Jaeger/Grafana", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-88", "summary": "P6-1a — Tech debt: tenant-scope bypass", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-89", "summary": "P6-2 — Usage metering (off hot path)", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-90", "summary": "P6-3 — React dashboard metrics/logs/traces", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-91", "summary": "P6-4 — React: DLQ browser + replay", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-92", "summary": "P6-5 — Append-only tamper-evident audit log", "type": "История", "status": "Готово", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "MDI-93", "summary": "P6-5a — Bug: verifyChain JSONB false-positive", "type": "История", "status": "Готово", "done": true, "assignee": null}
  ],
  "MDI-7": [
    {"key": "MDI-94", "summary": "P6-6 — Live flow visualizer (split)", "type": "История", "status": "Готово", "done": true, "assignee": null},
    {"key": "MDI-95", "summary": "P6-6a — Plane 1: aggregate topology heatmap", "type": "История", "status": "Готово", "done": true, "assignee": null},
    {"key": "MDI-96", "summary": "P6-6b-go — Flow Tap ENGINE track", "type": "История", "status": "Готово", "done": true, "assignee": null},
    {"key": "MDI-97", "summary": "P6-6b-nest — Flow Tap NESTJS track", "type": "История", "status": "Готово", "done": true, "assignee": null},
    {"key": "MDI-98", "summary": "P6-6b-react — Flow Tap REACT track", "type": "История", "status": "Готово", "done": true, "assignee": null},
    {"key": "MDI-99", "summary": "P6-G — GATE: observability + metering off hot path", "type": "История", "status": "Готово", "done": true, "assignee": null},
    {"key": "MDI-100", "summary": "P7-1 — Marketplace registry + publish/install", "type": "История", "status": "Готово", "done": true, "assignee": null},
    {"key": "MDI-101", "summary": "P7-2 — Polyglot FDK konformans harness", "type": "История", "status": "Готово", "done": true, "assignee": null},
    {"key": "MDI-102", "summary": "P7-3 — GitOps publisher (NestJS)", "type": "История", "status": "Готово", "done": true, "assignee": null},
    {"key": "MDI-103", "summary": "P7-4 — Tenant-scoped model catalogue", "type": "История", "status": "Готово", "done": true, "assignee": null}
  ],
  "MDI-8": [
    {"key": "MDI-104", "summary": "P7-5 — Edge/WASM tier (Go)", "type": "История", "status": "Backlog", "done": false, "assignee": null}
  ],
  "SL-104": [],
  "SL-107": [],
  "SL-119": [],
  "SL-128": [],
  "SL-134": [],
  "SL-144": [],
  "SL-15": [],
  "SL-151": [],
  "SL-16": [],
  "SL-194": [],
  "SL-222": [],
  "SL-5": [],
  "SL-6": [],
  "SL-7": [],
  "SL-71": [],
  "SL-9": [],
  "TB-3": [
    {"key": "TB-4", "summary": "Modul-RBAC + ko'p-kompaniya modeli", "type": "Задание", "status": "Готово", "done": true, "assignee": "Sattarov Ravshan"},
    {"key": "TB-5", "summary": "Auth/notification/integration modellari", "type": "Задание", "status": "Готово", "done": true, "assignee": "Sattarov Ravshan"},
    {"key": "TB-6", "summary": "To'lov domeni modeli", "type": "Задание", "status": "Готово", "done": true, "assignee": "Sattarov Ravshan"},
    {"key": "TB-8", "summary": "Kontragent domeni modeli", "type": "Задание", "status": "Готово", "done": true, "assignee": "Sattarov Ravshan"}
  ],
  "BSA-BOARD": [
    {"key": "BSA-3", "summary": "Документация Scoring Клиентов Юр-лиц и ИП", "type": "Задание", "status": "UseCase & User Story", "done": false, "assignee": "Pulatov Nozimjon"},
    {"key": "BSA-4", "summary": "Документация для создание договора Escrow", "type": "Задание", "status": "API Integrations", "done": false, "assignee": "Pulatov Nozimjon"},
    {"key": "BSA-5", "summary": "Документация для получение статуса по договору Escrow", "type": "Задание", "status": "К выполнению", "done": false, "assignee": "Pulatov Nozimjon"}
  ],
  "TD-BOARD": [
    {"key": "TD-308", "summary": "отправить прямой запрос ", "type": "Задача", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-307", "summary": "Trastpay Docs Frontend va backend togri connection ololmayapti", "type": "Баг", "status": "Selected for Development", "done": false, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-306", "summary": "192.168.18.205 (компьютер) дан Трастпэй базасига доступ очип коган", "type": "История", "status": "TO DO", "done": false, "assignee": "Mashkurov Azamat"},
    {"key": "TD-305", "summary": "PROD deploy trastpay-monitoring-api trastpay-admin-api trastpay-card-api", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-304", "summary": "ABS: Jira va boshqa saytlarga dostup berilishi kerak", "type": "История", "status": "TO DO", "done": false, "assignee": "Mashkurov Azamat"},
    {"key": "TD-303", "summary": "MuamalatPay:  php user /srv/project/pay-api/storage/logs/*.log filega yozish uchun dostup kerak", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-302", "summary": "BMMS > jarka qo'yish kerak", "type": "История", "status": "Проверка", "done": false, "assignee": "Mustonov Ilyos"},
    {"key": "TD-301", "summary": "Trastpay > BMMS > Yaml update qilish kerak", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-300", "summary": "ДБО: не проходит билд в микросервисе petitions", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-299", "summary": "ДБО: на фронте деплой перестал работать", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-298", "summary": "ДБО: Сделать curl запрос из микросервиса middlware", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-297", "summary": "ДБО: api.trustbank.uz/fpgateway/ zapros yuborilganda 502 Bad Gateway qaytvoti", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-296", "summary": "Trastpay > QR code > BMMS jarka yuklash", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-295", "summary": "DECO: Kompyerga dostuplarni ochib berish kerak.", "type": "История", "status": "TO DO", "done": false, "assignee": "Mashkurov Azamat"},
    {"key": "TD-294", "summary": "Chatbot AI uchun yengi domen yaratib berish kerak", "type": "История", "status": "IN PROGRESS", "done": false, "assignee": "Mashkurov Azamat"},
    {"key": "TD-293", "summary": "DBO-V2 uchun yangi server ochish kerak.", "type": "История", "status": "Selected for Development", "done": false, "assignee": "Mashkurov Azamat"},
    {"key": "TD-292", "summary": "Trastpay > BMMS > Yaml update qilish kerak", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-291", "summary": "BMMS jarka qo'yish. QR oplata", "type": "История", "status": "DONE", "done": true, "assignee": "Mustonov Ilyos"},
    {"key": "TD-290", "summary": "Trastpay: OFB product API credentials-ni latest change-larga uzgartirish", "type": "Баг", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-289", "summary": "PG REG TECH uchun Postgres Cluster kotarish", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-288", "summary": "DECO: DBeaver databazasida 192.168.254.7:5432 portga connection yo'q.", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-287", "summary": "FCI: Foot city базани хафталик backup олиш кере", "type": "Задача", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-286", "summary": "ДБО: DBO in domein ga fp-gateway servisini ulab berish kerak", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-285", "summary": "(pg rech tech) 172.16.103.17/18 shu ikkta serverdan iabs serverlariga 172.16.101.115 host va 1521 portiga connection ochish kerak", "type": "История", "status": "DONE", "done": true, "assignee": "Mashkurov Azamat"},
    {"key": "TD-284", "summary": "need to put the .JAR file to the needed destination and make a restart the loader first then bmms and need to see the logs how it works .", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-283", "summary": "BMMS > jarka qo'yish kerak", "type": "История", "status": "DONE", "done": true, "assignee": "Mustonov Ilyos"},
    {"key": "TD-282", "summary": "ДБО: ДБО ни dump ни олиб бериш", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-281", "summary": "ДБО: https://192.168.18.228 wi-fi доступ Алмаз", "type": "История", "status": "Проверка", "done": false, "assignee": "Mashkurov Azamat"},
    {"key": "TD-280", "summary": "ДБО: Нужно дать доступ до https://repo.packagist.org", "type": "История", "status": "Проверка", "done": false, "assignee": "Mashkurov Azamat"},
    {"key": "TD-279", "summary": "ДБО: При работе с GitLab возникает ошибка", "type": "История", "status": "DONE", "done": true, "assignee": "Mashkurov Azamat"},
    {"key": "TD-278", "summary": "BMMS > jarka qo'yish kerak", "type": "История", "status": "DONE", "done": true, "assignee": "Mustonov Ilyos"},
    {"key": "TD-277", "summary": "ДБО ни DUMPни олиш Сервердаги accessable path га койиб бериш", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-276", "summary": "deploy trastpay-transactions-perform-service", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-275", "summary": "deploy Trastpay-payment-api", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-274", "summary": "Trastpay > BMMS > Yaml update qilish kerak", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-273", "summary": "ДБО: [Groub-IB] Проверить и восстановить проксирование /api/fl/ в Nginx на af-backend.trustpay.uz/api/fl", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-272", "summary": "Yangi Postgres serverlar uchun Ixtiyor Abduxoshimov Yaxyo Sunnatovlarni PAMiga qoshib berishingizni soraymiz", "type": "История", "status": "DONE", "done": true, "assignee": "Mustonov Ilyos"},
    {"key": "TD-268", "summary": "ДБО: Необходимо систематизировать сбор логов", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-267", "summary": "BMMS > qr oplata > purpose code o'zgartirish kerak", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-266", "summary": "X-GO: Настройка сетевого доступа к сервисам Uzcard/Humo для OTP-верификации карт", "type": "Задача", "status": "DONE", "done": true, "assignee": "Mashkurov Azamat"},
    {"key": "TD-265", "summary": "2 TB dan har bitta gnodelarga qoshilgan deco projectida shuni sys adminlarga safe qilib qaytarish", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-264", "summary": "Trastpay: Mastercard uchun JAR ka update va bmms.yaml config update qilish", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-263", "summary": "Deploy payment api exp", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-262", "summary": "MINIO 172.16.101.1 serverga joy qoshish kk Sababi Mongo db dumplarini saqlamoqchimiza ( Trastpayni dumplarini )", "type": "История", "status": "Selected for Development", "done": false, "assignee": "Mashkurov Azamat"},
    {"key": "TD-261", "summary": "AI Chat Serverga dostup ochish kerak", "type": "История", "status": "DONE", "done": true, "assignee": "Mustonov Ilyos"},
    {"key": "TD-260", "summary": "MuamalatPay: Telekom AF ni agentini production serverdan alohida serverga ko'chirish kerak", "type": "История", "status": "DONE", "done": true, "assignee": "Mashkurov Azamat"},
    {"key": "TD-259", "summary": "3 ta server Postrges Cluster uchun 4 CPU 8 RAM 2TB /data ga mount qilish kere 3 ta server yozilgan harakteristikada bolish kerak.", "type": "История", "status": "DONE", "done": true, "assignee": "Mashkurov Azamat"},
    {"key": "TD-258", "summary": "k8s mongodb (172.27.1.12 , 172.27.1.13 ) ga internet 15 daqiqaga yoqish va shu serverlardan 172.16.101.1 9000 va 9001 portga connection ochish", "type": "История", "status": "DONE", "done": true, "assignee": "Mashkurov Azamat"},
    {"key": "TD-257", "summary": "MONGO DB DUMP olishni optimiize qilish va dumplarni Minioga saqlash", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-256", "summary": "FCI: Food city проектини ни ограниченный IP адресларида очадиган килиш", "type": "Задача", "status": "Selected for Development", "done": false, "assignee": "Mashkurov Azamat"},
    {"key": "TD-255", "summary": "ДБО: Доступ в Sentry", "type": "Задача", "status": "Selected for Development", "done": false, "assignee": "Mashkurov Azamat"},
    {"key": "TD-254", "summary": "ДБО: Нужно в env установить (Павел)", "type": "Задача", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-253", "summary": "ДБО: микросервисс bank в воркере statement.export периодически падает(Алмаз)", "type": "Задача", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-252", "summary": "Optimizing Taking Dump with help of MONGO db for TRASTPAY", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-251", "summary": "fix auto deploy in client-api exp", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-250", "summary": "Открытие доступа для интеграции Bill Master", "type": "Задача", "status": "Проверка", "done": false, "assignee": "Mashkurov Azamat"},
    {"key": "TD-249", "summary": "Muamalatpay: Humo Payment va Humo Middleware login nomlarini bilib berish", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-248", "summary": "Bill Master (172.20.21.2) дан Food City (172.16.102.85) 3000 портга connection очиш кере", "type": "История", "status": "DONE", "done": true, "assignee": "Mashkurov Azamat"},
    {"key": "TD-247", "summary": "DECO. Masofaviy tizimga kira olish huquqini ochish kerak.", "type": "История", "status": "Проверка", "done": false, "assignee": "Mustonov Ilyos"},
    {"key": "TD-246", "summary": "fix auto deploy in client-api exp", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-245", "summary": "deploy client-api prod", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-244", "summary": "adding new variables to .env in client-api", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-243", "summary": "Payment Hub Server Experimantal va production ochish kere", "type": "История", "status": "Проверка", "done": false, "assignee": "Mashkurov Azamat"},
    {"key": "TD-242", "summary": "Ошибка 404 NOT_FOUND при вызове методов Agent Check и Agent Pay", "type": "Баг", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-241", "summary": "ДБО: Установить переменные для файлового хранилища", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-239", "summary": "DECO. 192.168.254.6 ga Abduxoshimov Ixtiyor akaga dostup ochish kerak.", "type": "История", "status": "DONE", "done": true, "assignee": "Mashkurov Azamat"},
    {"key": "TD-238", "summary": "FCI: Pipeline да хатоли бервотти", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-237", "summary": "DECO. Serverga sql querylartni qo'yish kerak", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-236", "summary": "DECO. 192.168.254.7 serveridan fayllarni olib berish kerak", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-235", "summary": "MuamalatPay: Rabbitmq serveridan Muamalat serverlariga dostup ochish kerak", "type": "История", "status": "DONE", "done": true, "assignee": "Mashkurov Azamat"},
    {"key": "TD-234", "summary": "ДБО: Не удается выполнить сборку проекта bank в GitLab", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-233", "summary": "trastpay-admin-front master dagi ohirgi ozgarishlani prodga deploy", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-232", "summary": "ДБО: Не удаётся установить Composer-пакеты с сервера, ошибка SSL certificate problem (curl error 60)", "type": "История", "status": "DONE", "done": true, "assignee": "Mashkurov Azamat"},
    {"key": "TD-231", "summary": "ДБО: В микросервисе references настроить доступ к папке", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-230", "summary": "ДБО: Проверить для очередей notifications", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-229", "summary": "ДБО: В микросервисе notifications, добавить отельный deployment для слушателя rabbit", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-228", "summary": "DECO. Klasterni tiklash uchun gnode1/gnode2 serverlarida disk va RAM resurslarini oshirish", "type": "История", "status": "DONE", "done": true, "assignee": "Mashkurov Azamat"},
    {"key": "TD-227", "summary": "ДБО: Необходимо развернуть сервис Loki для хранения логов", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-226", "summary": "Create user in Grafana for backend developer [Dony]", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-225", "summary": "Chat Bot AI project Ubuntu Server 4 cpu 16 ram, SSD 80 GB", "type": "Задача", "status": "DONE", "done": true, "assignee": "Mashkurov Azamat"},
    {"key": "TD-224", "summary": "Logging service deploy qilindi va yengi domen qo'yib berish kerak.", "type": "История", "status": "Проверка", "done": false, "assignee": "Mashkurov Azamat"},
    {"key": "TD-223", "summary": "FCI: 172.16.102.85 dan 172.20.21.2 va 172.20.21.5 8080 portiga connection килиб беришиззи сориман", "type": "История", "status": "DONE", "done": true, "assignee": "Mashkurov Azamat"},
    {"key": "TD-222", "summary": "ДБО: Проверка и запуск pipeline для sms-gateway", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-221", "summary": "ДБО: Нужно открыть доступ для a.davranbekov к grafana и promiteus", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-220", "summary": "Logging Service for Middleware", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-219", "summary": "Food city: Prod, exp serverlariga env qo'shish kerak", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-218", "summary": "ofdms-prod.ymldan", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-217", "summary": "MuamalatPay Rabbit MQ nastroyka qilish kerak", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-216", "summary": "MuamalatPay dan Groub-IB ni  RabbitMQ siga dostup kerak va MuamalatPay da nastroyka qilish kerak.", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-215", "summary": "docs-api ga file-stronge-service ulash ", "type": "Задача", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-214", "summary": "Soliqni ip adresini middleware env ga qo'shish kerak", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-213", "summary": "Dostup ochish kere Trastpay-docs dan Minio ga", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-212", "summary": "ДБО: Бэкендан Group-IB аписига доступ бор йоклигини текшириш керак", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-211", "summary": "ДБО: Выяснить и исправить", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-210", "summary": "ДБО: получить env переменные", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-209", "summary": "ДБО: в микросервисе Notification", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-208", "summary": "ДБО: 192.168.18.199 локальный доступ", "type": "История", "status": "DONE", "done": true, "assignee": "Mashkurov Azamat"},
    {"key": "TD-207", "summary": "ДБО: не получается в микросервисе profiles запустить билд", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-206", "summary": "ДБО: Pipeline падает в микросервисе notifications", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-205", "summary": "ДБО: Архитектурасини тузиб чикиш", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-204", "summary": "ДБО: SDK→ mTLS Proxy га запрос юворвотканда 502 хато кайтарвотти", "type": "История", "status": "Проверка", "done": false, "assignee": "Mashkurov Azamat"},
    {"key": "TD-203", "summary": "Trastpay-admin-api-exp ga rasm yuklaganda error bervotti: 413 Request Entity Too Large.", "type": "История", "status": "DONE", "done": true, "assignee": "Mashkurov Azamat"},
    {"key": "TD-202", "summary": "BM серверида ofdms сервиси нечинчи портда ишлаб турганини толик url кере", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-201", "summary": "ДБО: api.trustbank.uz curl вызов клиш кере", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-200", "summary": "ДБО: Group IB серверидан бизани Бэкенд серверга доступ кбериш кере", "type": "История", "status": "DONE", "done": true, "assignee": "Mashkurov Azamat"},
    {"key": "TD-199", "summary": "Food city учун dev server котариш кере", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-198", "summary": "Mtls proxy uchun dostup", "type": "История", "status": "DONE", "done": true, "assignee": "Mashkurov Azamat"},
    {"key": "TD-197", "summary": "Trastpay: Visa direct request tekshirish", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-196", "summary": "MuamalatPay: https://git.trustbank.uz/chontakpay/pay-api/-/jobs/13256 da joblar yiqilishi kuzatilyapti", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-195", "summary": "ДБО: Mtls proxy ", "type": "История", "status": "DONE", "done": true, "assignee": "Mashkurov Azamat"},
    {"key": "TD-190", "summary": "Hashicorp сервис котариш", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-189", "summary": "BitWarden ko'tarish kere login parollar saqlash uchun", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-188", "summary": "Trastpay: fix the env variables", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-187", "summary": "ДБО: rabbitevents:listen middleware.transaction.finished по какой то причине перестал обрабатываться", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-186", "summary": "Trastpay: connection", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-185", "summary": "fix the env variables", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-184", "summary": "DWH Segment 6 dagi tizim indekslarida hatolik", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-183", "summary": "BMMS mini change. 22216 -> 22616", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-182", "summary": "Transaction time noto‘g‘ri ko‘rsatilmoqda", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-181", "summary": "Trastpay: update env trastpay-client-api-exp", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-180", "summary": "DECO 192.168.254.9:5432 dan 192.168.254.9:6002 ga connection bo'lmayapti", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-179", "summary": "dostuplarni hal qilish", "type": "Подзадача", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-178", "summary": "ecommerce billing serverda o'zgarish qilish", "type": "Подзадача", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-177", "summary": "ecommerce billing serverda o'zgarishlar qilish", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-176", "summary": "middleware data-service uchun Redis create qilish kerak.", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-175", "summary": "Nginx nastroyka qilish grafana uchun DBO proyektda.", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-174", "summary": "Dataservice Api loyihasi uchun server ochish va unga  backend deploy qilish.", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-173", "summary": "foodcity loyihasi uchun server ochish va unga frontend va backend deploy qilish experimental.", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-171", "summary": "ДБО: Postgres Exporter", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-170", "summary": "Abs token expire vaqtlarini 3540 sekundga almashtirish", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-169", "summary": "Visa direct: BM serverida zapros jo'natib ko'rish", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-168", "summary": "Доступ очиб бериш экоммерс сервис учун.", "type": "Задача", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-167", "summary": "Открыть графана для БМ чтобы смотреть логи", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-166", "summary": "получить полные логи  через Bmms", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-165", "summary": "e-commerce-billing-api uchun grafana ulash kerak", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-164", "summary": "192.168.254.8 ga space qo'shish kerak 300 GB ajratilgan keyin /data/segment4/primary/gpseg3/pg_xlog logni ko'rish kerak 500GB bo'lib ketganakan", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-163", "summary": "Log lar bir necha bo'lib ko'rinyapti", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-162", "summary": "Telecom exp da ishlamayapgan edi uni to'g'irlash", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-161", "summary": "android update asset links.json", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-160", "summary": "ДБО: Рэббит выдает ошибку", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-159", "summary": "ДБО: В микросервисе bank (https://ibank-gitlab.trustbank.uz/multibank/back/bank)", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-158", "summary": "ДБО: Для очередей bank.documents.sync", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-157", "summary": "ДБО: Нужно в микросервисе middleware в env указать", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-156", "summary": "В микросервисе notifications перевести job на deployment.", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-155", "summary": "N8N: Настроит домен и доступы", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-154", "summary": "e-commerce-billing-api prod and exper deployment", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-153", "summary": "ДБО: Нужно выяснить объем database Trastbank Business со всеми данными в MB, и объем самого проекта который нужно что бы запустить проект в локалке", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-152", "summary": "ДБО: Нужно получить response двух методов для проверки", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-151", "summary": "Trastpay: deploy card-api", "type": "История", "status": "DONE", "done": true, "assignee": "Abduxoshimov Ixtiyor"},
    {"key": "TD-150", "summary": "Trastbank: Поднять сервис n8n внутри инфраструктуры банка", "type": "История", "status": "DONE", "done": true, "assignee": "Zokirov Bobur"},
    {"key": "TD-149", "summary": "ДБО: Необходимо выяснить по какой причине воркеры не перезапускаются автоматически(Павел)", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-148", "summary": "Visa direct: BMMS-prod ga shu sozlamalarni qoshish kerak", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-147", "summary": "ДБО: В микросервисе profiles https://ibank-gitlab.trustbank.uz/multibank/back/profiles", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-146", "summary": "ДБО: В микросервисе middleware https://ibank-gitlab.trustbank.uz/multicard-ws/middleware", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-145", "summary": "trastpay-identification-api-exp da va trastpay-admin-api-exp NODE_ENV ikki xil emasmi. Qarab bera olasizmi", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-144", "summary": "Upgrade BM with jar file", "type": "История", "status": "DONE", "done": true, "assignee": "Mirzabayev Damir"},
    {"key": "TD-143", "summary": "trastpay-client-api' ga dostup", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-142", "summary": "trastpay-admin-front exp - deploy", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-140", "summary": "ДБО: В микросервисе notifications перевести job на deployment. (Алмаз)", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-139", "summary": "ДБО: Нужно установить переменные в микросервисе notifications(Алмаз)", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-138", "summary": "ДБО: Переменные добавить в прод", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-137", "summary": "MyID: experimentalda PROD API bilan tekshirib ko'rish uchun nastroyka qilib berish", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-136", "summary": "ДБО: Сделать полную архитектуру ДБО", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-134", "summary": "trastpay-client-api deploy qilish", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-133", "summary": "ДБО: Доступ к База Данных (Паша)", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-132", "summary": "CI/CD настройка сервера SUBSIDIYA.IDM", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-131", "summary": "ДБО: в микросервисе notifications не билдится (Алмаз)", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-130", "summary": "ДБО: Перезапустить жобы в микросервисе bank.", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-129", "summary": "v-2 trastpay-project-docs  dagi oxirgi ozgarishni main ga deploy qilish kerak. ", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-128", "summary": "trastpay-card-api deploy qilish kerak ", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-127", "summary": "[ASAP] Trastpay proxy> tas-ix IP list update qilish (DeepLink issue with IOS)", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-126", "summary": "trastpay-identification-api dagi oxirigi o'zgarishni exp ga deploy qilish kerak", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-125", "summary": "ДБО: Не отправляются запросы на middleware prod с локалки", "type": "История", "status": "DONE", "done": true, "assignee": "To'xtashev Asadbek"},
    {"key": "TD-123", "summary": "Middleware deploy exp and prod", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-121", "summary": "ДБО: profiles и auth да хатолик бервотти", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-120", "summary": "ДБО: umarov.ulugbek7869@gmail.com SENTRY га логин пароль ", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-119", "summary": "ДБО: fp_gateway даги охирги озгаришларни тест ва продга деплой клиш кере", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-118", "summary": "trastpay-project-docs staging dagi oxirigi o'zgarishni prod ga deploy qilish kerak", "type": "Задача", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-117", "summary": "trastpay-admin-front dev dagi oxirigi o'zgarishni prod ga deploy qilish kerak", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-116", "summary": "Trastbank Business DBO - DB qismini Deco (DWH) ga ulab berish yoki alohida baza qilib berish kerak, biz analiz qila olishimiz uchun", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-114", "summary": "Trastpay DB qismini Deco (DWH) ga ulab berish yoki alohida baza qilib berish kerak, biz analiz qila olishimiz uchun", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-113", "summary": "Rasm hajmi muammosi", "type": "История", "status": "DONE", "done": true, "assignee": "Zokirov Bobur"},
    {"key": "TD-112", "summary": "Prod subdomain nomini yangilash kerak", "type": "История", "status": "DONE", "done": true, "assignee": "Zokirov Bobur"},
    {"key": "TD-111", "summary": "MuamalatPay: Dev va Test serverdan curl -I https://fcm.googleapis.com ga dostup ochish", "type": "История", "status": "DONE", "done": true, "assignee": "Zokirov Bobur"},
    {"key": "TD-110", "summary": "MuamalatPay: ci/cd da permission yoq", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-109", "summary": "trastpay-admin-front dev dagi oxirigi o'zgarishni prod ga deploy qilish kerak", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-108", "summary": "trasttrastpay-project-docs frontend deploy to experimental and production", "type": "История", "status": "DONE", "done": true, "assignee": "Zokirov Bobur"},
    {"key": "TD-107", "summary": "trastpay-project-docs-api backend deploy to experimental and production server.", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-106", "summary": "minio-file-storage PR 14", "type": "История", "status": "DONE", "done": true, "assignee": "Toxirov Sarvar"},
    {"key": "TD-105", "summary": "minio-file-storage PR 12", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-104", "summary": "minio-file-storage PR 9", "type": "История", "status": "DONE", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "TD-103", "summary": "minio-file-storage PR 5", "type": "История", "status": "DONE", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "TD-102", "summary": "minio-file-storage PR 4", "type": "История", "status": "DONE", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "TD-101", "summary": "trastpay-admin-front dev dagi oxirigi o'zgarishni prod ga deploy qilish kerak", "type": "Задача", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-100", "summary": "trastpay-admin-front PR-304", "type": "Задача", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-99", "summary": "trastpay-admin-front dev dagi oxirigi o'zgarishni exp ga deploy qilish kerak", "type": "Задача", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-98", "summary": "(Front) trastpay-admin-front reports branch dan devga push qilib, dev dan experimentalga deploy qilish kerak", "type": "Задача", "status": "DONE", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "TD-97", "summary": "trastpay-admin-front dev dagi oxirigi o'zgarishni prod ga deploy qilish kerak", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-96", "summary": "trastpay-admin-api (prod) нужно хадеплоить", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-95", "summary": "trastpay-admin-front dev dagi oxirigi o'zgarishni prod ga deploy qilish kerak", "type": "История", "status": "DONE", "done": true, "assignee": "Amanhojaev Nodirkhon"},
    {"key": "TD-94", "summary": "trustbank-eimzo-serivce prod, нужно проверить работоспособность. Сервис не отвечает", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-93", "summary": "ДБО: trustbank-(bank, middleware, profiles, auth, references)-back нужно добавить prometheus и grafana", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-92", "summary": "trustbank-bank-back нужно сделать разделение микросервиса на два pod. Один для api микросервиса, другой для обработки queue микросервиса", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-91", "summary": "trustbank-iabs-api test, нужны доступы к базе данных", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-90", "summary": "trastpay-admin-front dev dagi oxirigi o'zgarishni prod ga deploy qilish kerak", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-89", "summary": "trastpay-admin-front dev dagi oxirigi o'zgarishni prod ga deploy qilish kerak", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-86", "summary": "trastpay-admin-front dev dagi oxirigi o'zgarishni prod ga deploy qilish kerak", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-85", "summary": "trastpay-admin-front dev dagi oxirigi o'zgarishni prod ga deploy qilish kerak", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-84", "summary": "idsys-abs-scheduler-exp auto deploy ishlamaypti", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-83", "summary": "trastpay-client-api-exp dan Telecom anti fraud ga chiqishini tekshirib bera olasizlarmi", "type": "История", "status": "DONE", "done": true, "assignee": "Zokirov Bobur"},
    {"key": "TD-82", "summary": "Code togri tersam ham hato qaytarvati. 2FA o'chirib qo'yolimizmi uchotkam uchun?", "type": "История", "status": "DONE", "done": true, "assignee": "Zokirov Bobur"},
    {"key": "TD-81", "summary": "BM дан шу вакт оралигидаги шу транзакцияни ЛОГи керак", "type": "История", "status": "DONE", "done": true, "assignee": "Zokirov Bobur"},
    {"key": "TD-79", "summary": "Шу сервисда узилишла кузатилвотти(п2п да копрок) \"http://uzservice2.trustbank.uz/api/jsonrpc\": Read timed", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-78", "summary": "trastpay-client-api-exp. Token expire vaqtini 1 kunlik qilish kerak.", "type": "История", "status": "DONE", "done": true, "assignee": "Amanhojaev Nodirkhon"},
    {"key": "TD-77", "summary": "git.trastpay.uz ga kirolmayapman.", "type": "История", "status": "DONE", "done": true, "assignee": "Amanhojaev Nodirkhon"},
    {"key": "TD-76", "summary": "trastpay-admin-api Producationda deploy qilish kerak", "type": "История", "status": "DONE", "done": true, "assignee": "Amanhojaev Nodirkhon"},
    {"key": "TD-75", "summary": "Prodga trastpay-product-api ni deploy qivarish kerek", "type": "История", "status": "DONE", "done": true, "assignee": "Amanhojaev Nodirkhon"},
    {"key": "TD-74", "summary": "idsys-handler experimental da avto deploy ishlamayapti", "type": "История", "status": "DONE", "done": true, "assignee": "Amanhojaev Nodirkhon"},
    {"key": "TD-73", "summary": "idsys-client-api experimental avto deploy ishlamaypti", "type": "История", "status": "DONE", "done": true, "assignee": "Amanhojaev Nodirkhon"},
    {"key": "TD-72", "summary": "trastpay-payment-api trastpay-transaction-perform-service Production da deploy qilib bera olasizmi", "type": "История", "status": "DONE", "done": true, "assignee": "Amanhojaev Nodirkhon"},
    {"key": "TD-71", "summary": "Нужно дать правы в гитлаб", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-70", "summary": "idsys-handler деплой на прод", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-69", "summary": "IB Group бойича rabbitMQ га доступ", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-67", "summary": "Logs - описанияга кошганим бойича логлар кере", "type": "Задача", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-66", "summary": "Bmms Logs - for bug fix and optimisation", "type": "Задача", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-65", "summary": "trastpay-transaction-perform-service Prod deploy qilish kerak", "type": "История", "status": "DONE", "done": true, "assignee": "Amanhojaev Nodirkhon"},
    {"key": "TD-64", "summary": "trastpay-vendor-api PROD deploy qilish kerak", "type": "История", "status": "DONE", "done": true, "assignee": "Amanhojaev Nodirkhon"},
    {"key": "TD-63", "summary": "trastpay-payment-api PROD deploy qilish kerak", "type": "История", "status": "DONE", "done": true, "assignee": "Amanhojaev Nodirkhon"},
    {"key": "TD-62", "summary": "trastpay-product-handler PROD ga deploy va env failiga yangi parametrlarni qo'shish", "type": "История", "status": "DONE", "done": true, "assignee": "Amanhojaev Nodirkhon"},
    {"key": "TD-61", "summary": "identification-services-frontend: exp deploy", "type": "История", "status": "DONE", "done": true, "assignee": "Amanhojaev Nodirkhon"},
    {"key": "TD-60", "summary": "trastpay-card-api PROD deploy qilish kerak", "type": "История", "status": "DONE", "done": true, "assignee": "Amanhojaev Nodirkhon"},
    {"key": "TD-59", "summary": "indentification-service-frontend deploy-exp", "type": "История", "status": "DONE", "done": true, "assignee": "Amanhojaev Nodirkhon"},
    {"key": "TD-58", "summary": "trastpay-client-api deploy production", "type": "История", "status": "DONE", "done": true, "assignee": "Amanhojaev Nodirkhon"},
    {"key": "TD-57", "summary": "identification-services-api grafana надо добвить", "type": "История", "status": "DONE", "done": true, "assignee": "Amanhojaev Nodirkhon"},
    {"key": "TD-56", "summary": "Прошу открыть доступ к GitLab проекта Multicard.", "type": "История", "status": "DONE", "done": true, "assignee": "Zokirov Bobur"},
    {"key": "TD-55", "summary": "trastpay-product-handler Деплой на прод ", "type": "История", "status": "DONE", "done": true, "assignee": "Amanhojaev Nodirkhon"},
    {"key": "TD-54", "summary": "trastpay-card-api deploy qilish kerak", "type": "История", "status": "DONE", "done": true, "assignee": "Amanhojaev Nodirkhon"},
    {"key": "TD-53", "summary": "trastpay-admin-api-exp ishlamayapti", "type": "История", "status": "DONE", "done": true, "assignee": "Amanhojaev Nodirkhon"},
    {"key": "TD-52", "summary": "trastpay-transactions-perform-service надо сделать деплой на проде", "type": "История", "status": "DONE", "done": true, "assignee": "Amanhojaev Nodirkhon"},
    {"key": "TD-51", "summary": "trastpay-payment-api надо сделать деплой на проде", "type": "История", "status": "DONE", "done": true, "assignee": "Amanhojaev Nodirkhon"},
    {"key": "TD-50", "summary": "trastpay-transactions-perform-service надо сделать деплой на проде", "type": "История", "status": "DONE", "done": true, "assignee": "Amanhojaev Nodirkhon"},
    {"key": "TD-49", "summary": "object-storage-service deploy to production", "type": "История", "status": "DONE", "done": true, "assignee": "Zokirov Bobur"},
    {"key": "TD-48", "summary": "identification-services-api деплой на exp", "type": "История", "status": "DONE", "done": true, "assignee": "Amanhojaev Nodirkhon"},
    {"key": "TD-47", "summary": "trastpay-client-api va trastpay-payment-api deploy qilish kerak", "type": "История", "status": "DONE", "done": true, "assignee": "Amanhojaev Nodirkhon"},
    {"key": "TD-46", "summary": "trastpay-client-api-exp va trastpay-payment-api-exp deploy qilish kerak ", "type": "История", "status": "DONE", "done": true, "assignee": "Amanhojaev Nodirkhon"},
    {"key": "TD-45", "summary": "Продга деплой idsys-handler", "type": "История", "status": "DONE", "done": true, "assignee": "Amanhojaev Nodirkhon"},
    {"key": "TD-44", "summary": "trastpay-client-api deploy qilish kerak", "type": "История", "status": "DONE", "done": true, "assignee": "Abduvokhid"},
    {"key": "TD-43", "summary": "trastpay-payment-api deploy qilish kerak", "type": "История", "status": "DONE", "done": true, "assignee": "Amanhojaev Nodirkhon"},
    {"key": "TD-42", "summary": "3. trastpay-payment-api deploy qilish kerak", "type": "История", "status": "DONE", "done": true, "assignee": "Amanhojaev Nodirkhon"},
    {"key": "TD-41", "summary": "2. trastpay-client-api prodga deploy qilish kerak", "type": "История", "status": "DONE", "done": true, "assignee": "Amanhojaev Nodirkhon"},
    {"key": "TD-40", "summary": "1. trastpay-admin-api prodga deploy qilish kerak", "type": "История", "status": "DONE", "done": true, "assignee": "Amanhojaev Nodirkhon"},
    {"key": "TD-39", "summary": "Prodda trastpay-product-api deploy qilish kerek", "type": "История", "status": "DONE", "done": true, "assignee": "Amanhojaev Nodirkhon"},
    {"key": "TD-38", "summary": "trastpay-perform-abs-transactions-scheduler-exp auto deploy не работает", "type": "История", "status": "DONE", "done": true, "assignee": "Amanhojaev Nodirkhon"},
    {"key": "TD-37", "summary": "trastpay-notification-service-exp auto deploy не работает", "type": "История", "status": "DONE", "done": true, "assignee": "Amanhojaev Nodirkhon"},
    {"key": "TD-36", "summary": "trastpay-routine-schedulers-exp auto deploy не работает", "type": "История", "status": "DONE", "done": true, "assignee": "Amanhojaev Nodirkhon"},
    {"key": "TD-35", "summary": "trastpay-cashback-perform-scheduler-exp auto deploy не работает", "type": "История", "status": "DONE", "done": true, "assignee": "Amanhojaev Nodirkhon"},
    {"key": "TD-34", "summary": "trastpay-sync-merchants-scheduler-exp auto deploy не работает", "type": "История", "status": "DONE", "done": true, "assignee": "Amanhojaev Nodirkhon"},
    {"key": "TD-33", "summary": "trastpay-sync-bank-branch-scheduler-exp auto deploy не работает", "type": "История", "status": "DONE", "done": true, "assignee": "Amanhojaev Nodirkhon"},
    {"key": "TD-32", "summary": "Деплой на прод trastpay-product-api", "type": "История", "status": "DONE", "done": true, "assignee": "Amanhojaev Nodirkhon"},
    {"key": "TD-31", "summary": "Env parametrlarni trastpay-card-api-exp dan trastpay-product-handler-exp ga ko'chirib qo'yish", "type": "Задача", "status": "DONE", "done": true, "assignee": "Abduvokhid"},
    {"key": "TD-30", "summary": "Открыть доступ к новой gitlab", "type": "Задача", "status": "DONE", "done": true, "assignee": "Abduvokhid"},
    {"key": "TD-29", "summary": "trastpay-admin-api prodga deploy qivarish kerek", "type": "Задача", "status": "DONE", "done": true, "assignee": "Amanhojaev Nodirkhon"},
    {"key": "TD-28", "summary": "trastid-client-api-exp eski kod deploy bo'vati yangisi bo'maypti", "type": "Задача", "status": "DONE", "done": true, "assignee": "Abduvokhid"},
    {"key": "TD-27", "summary": "trastpay-identifications-check-scheduler-exp ni env faylidan IDENTIFICATION_SERVICE_ENDPOINT IDENTIFICATION_SERVICE_LOGIN IDENTIFICATION_SERVICE_PASSWORD qiymatlarini trastpay-admin-api-exp ni env siga qo'shvarish kerek", "type": "Задача", "status": "DONE", "done": true, "assignee": "Abduraxmonov Islom"},
    {"key": "TD-26", "summary": "trastpay-admin-api деплой прод", "type": "Задача", "status": "DONE", "done": true, "assignee": "Amanhojaev Nodirkhon"},
    {"key": "TD-25", "summary": "Нужно открыть доступ к Деко для уч. запись b.zokirov", "type": "История", "status": "DONE", "done": true, "assignee": "Zokirov Bobur"},
    {"key": "TD-23", "summary": "Деплой на прод trastpay-callback-receiver-api", "type": "Задача", "status": "DONE", "done": true, "assignee": "Amanhojaev Nodirkhon"},
    {"key": "TD-22", "summary": "Деплой на прод idsys-operator-api, idsys-handlaer idsys-abs-scheduler,", "type": "Задача", "status": "DONE", "done": true, "assignee": "Amanhojaev Nodirkhon"},
    {"key": "TD-20", "summary": "redis-commander [docker]", "type": "История", "status": "DONE", "done": true, "assignee": "Sunnatov Yaxyo"},
    {"key": "TD-19", "summary": "trastpay-vendor-api prod deploy qilish", "type": "Задача", "status": "DONE", "done": true, "assignee": "Amanhojaev Nodirkhon"},
    {"key": "TD-18", "summary": "Bonus loyihasini prod ga o'tqazish kerak", "type": "Задача", "status": "DONE", "done": true, "assignee": "Zokirov Bobur"},
    {"key": "TD-17", "summary": "[*.*.*16.5] test-server (open access to MyID, ABS, INTIS, PLAYMOBILE)", "type": "Задача", "status": "DONE", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "TD-16", "summary": "[service] private-cloud-storage (minio)", "type": "Задача", "status": "DONE", "done": true, "assignee": "Abduvokhid"},
    {"key": "TD-14", "summary": "[back] trastpay-card-api деплой на прод", "type": "Задача", "status": "DONE", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "TD-13", "summary": "Jar file upload for Bill Master", "type": "История", "status": "DONE", "done": true, "assignee": "Abduvokhid"},
    {"key": "TD-12", "summary": "[back] trastpay-vendor-api деплой на прод", "type": "Задача", "status": "DONE", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "TD-11", "summary": "[back] trastpay-card-api деплой на прод", "type": "История", "status": "DONE", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "TD-10", "summary": "[front] trastpay-admin-front деплой на прод", "type": "История", "status": "DONE", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "TD-9", "summary": "[back] trastpay-card-api деплой на прод", "type": "Задача", "status": "DONE", "done": true, "assignee": "Saidov Jamshid"},
    {"key": "TD-8", "summary": "Нужно задеплойит на проде trastpay-client-api", "type": "История", "status": "DONE", "done": true, "assignee": "Abduvokhid"},
    {"key": "TD-7", "summary": "Bonus proektni local git ga ulash", "type": "История", "status": "DONE", "done": true, "assignee": "Abduvokhid"},
    {"key": "TD-6", "summary": "Dev Server ochib berish kerak", "type": "История", "status": "DONE", "done": true, "assignee": "Abduvokhid"},
    {"key": "TD-5", "summary": "Javohir aka ga testoviy virtualka ochib berish kerak", "type": "Задача", "status": "DONE", "done": true, "assignee": "Zokirov Bobur"},
    {"key": "TD-4", "summary": "Shu ikkita servisni deploy qilish: trastpay-transactions-perform-service trastpay-transactions-check-scheduler", "type": "История", "status": "DONE", "done": true, "assignee": "Abduvokhid"},
    {"key": "TD-3", "summary": "эксперименталдаги проекталрни .env ларига данныйлар кошиб чикиш", "type": "История", "status": "DONE", "done": true, "assignee": "Abduvokhid"},
    {"key": "TD-2", "summary": "trastpay-product-api ni deploy qivarish kerek", "type": "Задача", "status": "DONE", "done": true, "assignee": "Abduvokhid"},
    {"key": "TD-1", "summary": "ElasticSearch тизим жорий килиш", "type": "История", "status": "DONE", "done": true, "assignee": "Zokirov Bobur"}
  ]
};
