// Jira issues pre-fetched per epic — generated 2026-06-23 (sync updated 2026-06-23)
window.TB_JIRA_ISSUES = {
  "FC-13": [
    {"key": "FC-3",  "summary": "Добавить поле - ФИО", "type": "История", "status": "Backlog", "done": false},
    {"key": "FC-9",  "summary": "Cancel - Пул возврати", "type": "Задание", "status": "Backlog", "done": false},
    {"key": "FC-11", "summary": "Detail page га файл прикрепления кошиш", "type": "Задание", "status": "Backlog", "done": false},
    {"key": "FC-23", "summary": "QR генерация хар бир объект учун", "type": "Задание", "status": "Backlog", "done": false},
  ],
  "FC-14": [
    {"key": "FC-8",  "summary": "Толовларга Rabbit кошиш", "type": "Задание", "status": "Backlog", "done": false},
    {"key": "FC-15", "summary": "Anorga интеграция", "type": "История", "status": "Backlog", "done": false},
    {"key": "FC-16", "summary": "Error handle", "type": "История", "status": "Backlog", "done": false},
  ],
  "FC-29": [
    {"key": "FC-1", "summary": "Соликга хисобод кетиши хар бир толов бойича", "type": "Задание", "status": "Готово", "done": true},
  ],
  "FC-30": [
    {"key": "FC-6",  "summary": "Auto Fill - толов вактида", "type": "История", "status": "Ready for dev", "done": false},
    {"key": "FC-17", "summary": "Company кушиш (динамик килиш бошка бозорла кошиш учун)", "type": "Задание", "status": "in dev", "done": false},
    {"key": "FC-18", "summary": "Tax-settings table кошилди", "type": "Задание", "status": "in dev", "done": false},
    {"key": "FC-19", "summary": "Role Base (permissions)", "type": "Задание", "status": "Ready for dev", "done": false},
  ],
  "FC-31": [
    {"key": "FC-24", "summary": "Анализ DSQ учун", "type": "История", "status": "Готово", "done": true},
  ],
  "FC-32": [
    {"key": "FC-33", "summary": "Видео Аналитика(AI)", "type": "Задание", "status": "Backlog", "done": false},
  ],
  "KT-25": [],
  "KT-26": [],
  "KT-27": [
    {"key": "KT-11", "summary": "Back: Push уведомления для платежных операции", "type": "История", "status": "Backlog", "done": false},
  ],
  "KT-28": [],
  "KT-29": [
    {"key": "KT-35",  "summary": "Mobile: Android da User ID yuborilmayapti", "type": "Баг", "status": "Blocked", "done": false},
    {"key": "KT-36",  "summary": "Back: API реализация для 2 метода malware", "type": "История", "status": "Готово", "done": true},
    {"key": "KT-37",  "summary": "Mobile: Malware API Integration", "type": "История", "status": "in dev", "done": false},
    {"key": "KT-135", "summary": "Front: Session_Id не отправляется", "type": "Баг", "status": "Готово", "done": true},
    {"key": "KT-136", "summary": "Mobile: Добавить тестовое приложение для проверки blacklist API", "type": "История", "status": "Готово", "done": true},
  ],
  "KT-30": [
    {"key": "KT-6", "summary": "FACEID ЦБ-ГЦИ", "type": "История", "status": "Blocked", "done": false},
  ],
  "KT-31": [],
  "KT-32": [],
  "KT-33": [],
  "KT-34": [
    {"key": "KT-10", "summary": "Back: В случае если проводка удалена нужно синхронизировать статус", "type": "История", "status": "Documentation", "done": false},
  ],
  "MW-2": [],
  "MW-3": [
    {"key": "MW-4", "summary": "Разработка API для перевода со счета на карту в рамках флоу X-GO (BM)", "type": "Задание", "status": "Ready for prod", "done": false},
    {"key": "MW-6", "summary": "X-GO: Интеграция с Uzcard/Humo для добавления карт (OTP/Verify)", "type": "Задание", "status": "В работе", "done": false},
  ],
  "MW-5": [],
  "MW-7": [],
  "SL-5": [
    {"key": "SL-31", "summary": "Not getting insurance amount", "type": "Задание", "status": "Готово", "done": true},
  ],
  "SL-6": [
    {"key": "SL-18",  "summary": "GET payment-info with deal_ID", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-20",  "summary": "Check status of transaction-id", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-35",  "summary": "Оплата по deal_ID", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-42",  "summary": "Add 'sender name' to BM request", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-43",  "summary": "change date format in BM request", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-201", "summary": "[flutter] last payment recomendation", "type": "История", "status": "Готово", "done": true},
  ],
  "SL-7": [
    {"key": "SL-22", "summary": "Get client info by Prestige", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-46", "summary": "[back] Create token API", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-52", "summary": "[back] Integrate with BM (Check, Pay)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-53", "summary": "[back] Send transaction status to Prestige with Callback URL", "type": "История", "status": "Готово", "done": true},
  ],
  "SL-9": [
    {"key": "SL-26",  "summary": "Проверка карты получателя", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-27",  "summary": "Совершения перевода", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-28",  "summary": "Получить статус транзакции", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-65",  "summary": "Инициализация перевода Visa Direct", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-69",  "summary": "Верстка", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-130", "summary": "Take payment info (Android)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-132", "summary": "Send payment detail to BM", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-230", "summary": "Moneysend > Tittle kelmayabti", "type": "Баг", "status": "Готово", "done": true},
  ],
  "SL-15": [
    {"key": "SL-29", "summary": "Клиент подает заявку на аннулирование карты", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-30", "summary": "Предоставить доступ сотрудникам", "type": "Задание", "status": "Готово", "done": true},
    {"key": "SL-32", "summary": "Add all IP's who accepts applications from users", "type": "Задание", "status": "Готово", "done": true},
    {"key": "SL-40", "summary": "Create login password for employees ПК", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-72", "summary": "Добавить в Админку, сортировку по дате", "type": "История", "status": "Готово", "done": true},
  ],
  "SL-16": [
    {"key": "SL-56",  "summary": "Добавить Момент карту (Android)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-82",  "summary": "Проверка сущности карты (меторд P2P info)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-83",  "summary": "Получение токена карты (метод cards.new.otp)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-84",  "summary": "Проверка ОТП и получение токена карты (card.new.verify)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-85",  "summary": "Запрос на регистрацию карты ( create-instant-card-app )", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-86",  "summary": "Вызов метода для установкиПИН-КОД (online.pin.set)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-87",  "summary": "Проверка статуса (get-status-card)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-88",  "summary": "Отправка об успешной установке", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-89",  "summary": "Добавить Момент карту (iOS)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-90",  "summary": "Добавить OTP (Android)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-91",  "summary": "Добавить OTP (iOS)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-92",  "summary": "Создать PIN (Android)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-93",  "summary": "Создать PIN (iOS)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-94",  "summary": "Успешно добавлена (Android)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-95",  "summary": "Успешно добавлена (iOS)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-125", "summary": "Открыть сайт Uzcard во webview внутри TrastPay. После ввода PIN-кода открыть страницу Car…", "type": "История", "status": "Готово", "done": true},
  ],
  "SL-71": [
    {"key": "SL-70", "summary": "Добавить проводку из бэкенда трастпей", "type": "История", "status": "Готово", "done": true},
  ],
  "SL-100": [
    {"key": "SL-99",  "summary": "Add comment in P2P (Android)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-106", "summary": "Trastpay > users can use only Mobile network, revoke the using wifi connections", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-115", "summary": "Add comment in P2P (iOS)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-120", "summary": "Trastpay > users can use only Mobile network, revoke the using wifi connections", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-121", "summary": "Trastpay > users can use only Mobile network, revoke the using wifi connections", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-122", "summary": "Add new comment to the P2P (Android)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-123", "summary": "Add new comment to the P2P (iOS)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-160", "summary": "20 - Zararli dastur yoki masofadan boshqaruv aniqlanganda SMS-xabarnoma yuborish", "type": "История", "status": "IN ANALYSIS", "done": false},
    {"key": "SL-164", "summary": "60 - Ilova ishga tushganda qurilma xavfsizligini tekshirish va salbiy holatda ilovani blo…", "type": "История", "status": "IN ANALYSIS", "done": false},
    {"key": "SL-176", "summary": "[back]  Проверка совпадения ПИНФЛ и номера телефона", "type": "История", "status": "К выполнению", "done": false},
    {"key": "SL-178", "summary": "[flutter]  Проверка совпадения ПИНФЛ и номера телефона", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-186", "summary": "ЦБ so'ragan ma'lumotlarni bazadan olib berish", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-256", "summary": "Интеграция с сервисом Xolis", "type": "История", "status": "IN ANALYSIS", "done": false},
    {"key": "SL-257", "summary": "Льготная ипотека «Мой дом» (Mening Uyim ТСЧЖ)", "type": "История", "status": "IN ANALYSIS", "done": false},
    {"key": "SL-258", "summary": "Валютный Вклад \"Qulay sarmoya\"", "type": "История", "status": "К выполнению", "done": false},
    {"key": "SL-259", "summary": "возврат платежа МУНИС", "type": "История", "status": "К выполнению", "done": false},
    {"key": "SL-262", "summary": "dinamic QR не притягивает сумму", "type": "История", "status": "IN QA", "done": false},
  ],
  "SL-103": [
    {"key": "SL-102", "summary": "Add check-request to Create-customer", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-143", "summary": "Flutter | Bug Fixing", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-179", "summary": "[flutter] FIX client auth header. user-agent", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-182", "summary": "40,90 statusi tori kelmayabti karta qoshvotganda", "type": "Баг", "status": "К выполнению", "done": false},
    {"key": "SL-183", "summary": "эксп ва прод-да ассетсни жавоби хархил", "type": "Баг", "status": "Готово", "done": true},
    {"key": "SL-184", "summary": "Картани пин-кодини сет клиш методини кошиб бериш (Момент кард)", "type": "Баг", "status": "К выполнению", "done": false},
    {"key": "SL-190", "summary": "Notification bormasligini tekshirish, testiviy accountga. Phone: 909756057", "type": "История", "status": "К выполнению", "done": false},
    {"key": "SL-200", "summary": "add card images", "type": "История", "status": "К выполнению", "done": false},
    {"key": "SL-202", "summary": "Правильно отображать погашения по графику и еж.месячный платеж", "type": "Баг", "status": "Готово", "done": true},
    {"key": "SL-206", "summary": "Правильно отображать на главном списке кредитов сумму просроченного платежа", "type": "Баг", "status": "К выполнению", "done": false},
    {"key": "SL-207", "summary": "Отобразить сумму следующего месяца платежа на окне \"Детали кредита\"", "type": "Баг", "status": "К выполнению", "done": false},
    {"key": "SL-209", "summary": "Уведомления приходит на английском языке", "type": "Баг", "status": "К выполнению", "done": false},
    {"key": "SL-211", "summary": "в погашении кредита не приходит typePay и Tranzit", "type": "Баг", "status": "К выполнению", "done": false},
    {"key": "SL-217", "summary": "Icon image'lar cashirovanie qilish kerak", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-219", "summary": "[Flutter] Avto rassrochka", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-224", "summary": "Identification > case: Error message chiqarish kerak", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-225", "summary": "\"Exchange\" при обмене на визу карту, не передается \"pan\" карты VISA", "type": "Баг", "status": "К выполнению", "done": false},
    {"key": "SL-226", "summary": "Omonot > History ko'rinmayapti", "type": "Баг", "status": "Готово", "done": true},
    {"key": "SL-229", "summary": "В чеке оплаты по Budget показывает некорректную сумму", "type": "Баг", "status": "Готово", "done": true},
    {"key": "SL-231", "summary": "\"Anti-fraud\" - внедрить алгоритм для обхода 1-минутной ошибки", "type": "Задание", "status": "К выполнению", "done": false},
    {"key": "SL-232", "summary": "Operation not faund ошибка при попытке перевести между счетами", "type": "Баг", "status": "К выполнению", "done": false},
    {"key": "SL-233", "summary": "Добавить апи для смены пин-кода", "type": "Задание", "status": "К выполнению", "done": false},
    {"key": "SL-234", "summary": "Подготовка к релизу платформы Андроид \"3.0.37\"", "type": "Задание", "status": "Готово", "done": true},
    {"key": "SL-235", "summary": "История платежей статусы платежей не обновляются", "type": "Баг", "status": "К выполнению", "done": false},
    {"key": "SL-236", "summary": "Чеклардеги, вахтни тогри такдиг этиш", "type": "Баг", "status": "К выполнению", "done": false},
    {"key": "SL-238", "summary": "A2A > Text UX ga to'ri holatda mobilkaga berilishi kerak", "type": "Баг", "status": "Готово", "done": true},
    {"key": "SL-240", "summary": "Virtual kartadan > koshelekga pul o'tmayapti", "type": "Баг", "status": "Готово", "done": true},
    {"key": "SL-241", "summary": "Chekda 'komissiya miqdori' xato ko'rsatvotti", "type": "Баг", "status": "Готово", "done": true},
    {"key": "SL-248", "summary": "SMS shablon qo'shish", "type": "Задание", "status": "Готово", "done": true},
    {"key": "SL-260", "summary": "notificationda broadcast-notification paytida microservice qotbqovotti", "type": "Баг", "status": "IN DEV", "done": false},
    {"key": "SL-261", "summary": "Chekda 'komissiya miqdori' xato ko'rsatvotti [budget tolov]", "type": "Баг", "status": "Готово", "done": true},
    {"key": "SL-265", "summary": "A2A > bind qilishda filtr olib tashlash kerak", "type": "Задание", "status": "IN QA", "done": false},
    {"key": "SL-266", "summary": "A2A > bind check ishlamayapti", "type": "Баг", "status": "IN QA", "done": false},
    {"key": "SL-267", "summary": "trastpaydan iABS ga, transaction metodiga cheksiz zapros tashalvotti har kuni. Loop ni to'xtatish kerak", "type": "Задание", "status": "К выполнению", "done": false},
    {"key": "SL-268", "summary": "A2A > poluchatel kartasida select button'ni FIX qilib qo'yish kerak", "type": "История", "status": "IN QA", "done": false},
    {"key": "SL-271", "summary": "При сканере QR-кода не переходит на следующий page", "type": "Баг", "status": "Готово", "done": true},
    {"key": "SL-272", "summary": "Иловага виртуал картасини кушомиетти", "type": "Задание", "status": "IN DEV", "done": false},
  ],
  "SL-104": [
    {"key": "SL-101", "summary": "Release Group-IB", "type": "История", "status": "Готово", "done": true},
  ],
  "SL-107": [
    {"key": "SL-109", "summary": "Get access token", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-110", "summary": "Create session", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-111", "summary": "Get data with code", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-112", "summary": "Initialize SDK with session_ID (Android)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-114", "summary": "Integrate with iABS", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-142", "summary": "Verification MyID", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-175", "summary": "Identification > Adminka > List page'dan inner page ochganda Telefon raqam UX formatda tu…", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-187", "summary": "MyID: ЦБ district, mahalla code mapping. Convert to mongDB", "type": "История", "status": "Готово", "done": true},
  ],
  "SL-119": [
    {"key": "SL-116", "summary": "Настроить получение и обновление данных о налоговых задолженностях (BackEnd)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-117", "summary": "Реализовать отображение баннера на главном экране приложения (Mobile)(Android)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-197", "summary": "[Backend] Интеграция API для мобилки", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-198", "summary": "[Frontend] Сделать раздел для Push Soliq Qarzi", "type": "История", "status": "Готово", "done": true},
  ],
  "SL-128": [
    {"key": "SL-127", "summary": "Payment UzRTSB (Android)", "type": "История", "status": "Готово", "done": true},
  ],
  "SL-134": [
    {"key": "SL-135", "summary": "Add new list for 'p2p white-list'", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-136", "summary": "Add 'p2p white-list' for adminka", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-137", "summary": "Integrate 'white-list' to client API", "type": "История", "status": "Готово", "done": true},
  ],
  "SL-144": [
    {"key": "SL-145", "summary": "Telefon raqami va JSHSHIR mosligini tekshirish (ro'yxatdan o'tish va karta biriktirishda)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-146", "summary": "Ro'yxatdan o'tgandan so'ng foydalanuvchini login, parol va OTP orqali autentifikatsiyadan…", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-147", "summary": "Ro'yxatdan o'tgandan so'ng sessiyani yakunlash va kartani OTP + biometrik tasdiqlash orqa…", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-148", "summary": "Telefon raqami mos kelmaganda karta biriktirishni bloklash va PUSH-xabar yuborish", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-149", "summary": "OTP kodga qo'yiladigan talablarni joriy etish", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-150", "summary": "OTP 3 marta noto'g'ri kiritilganda foydalanuvchini vaqtincha bloklash va SMS-xabarnoma yuborish", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-152", "summary": "8 - Masofaviy biometrik identifikatsiyada liveness detection funksiyasini joriy etish", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-153", "summary": "9 - Biometrik identifikatsiya xizmat provayderi bilan shartnomaga javobgarlik bandlarini kiritish", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-154", "summary": "10 - Foydalanuvchi akkauntiga faqat tegishli (va yaqin qarindoshlar) hisoblarini biriktirish va P2P o'tkazmalarni cheklash", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-155", "summary": "12 - OTP kodni qurilmaga bog'lash (device binding) va boshqa qurilmalarda ishlatilishini cheklash", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-156", "summary": "14 - Yangi qurilmadan kirish yoki parol tiklanganda kartalarni unlink qilish va tranzaksiya tarixini tozalash", "type": "История", "status": "Готово", "done": true},
  ],
  "SL-151": [
    {"key": "SL-157", "summary": "15 - mobil qurilmaning texnik identifikatsiya va dasturiy parametrlari avtomatik tarzda a…", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-158", "summary": "16 - Ro'yxatdan o'tmagan qurilmadan akkauntga kirish urinishida SMS-xabarnoma yuborish", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-159", "summary": "18 - Foydalanuvchi sessiyasi uchun inactivity timeout (3 daqiqa) joriy etish", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-161", "summary": "26 - Moliyaviy operatsiyalar oldidan foydalanuvchidan qo'shimcha tasdiq (anti-fraud warni…", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-162", "summary": "27 - Mobil ilovada 'Firibgarlik haqida xabar berish' bo'limini joriy etish", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-163", "summary": "59 - Root/Jailbreak aniqlanganda mobil ilova funksionalligini cheklash", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-165", "summary": "61 - Mobil ilova kodini reverse engineering va dekompilyatsiyadan himoyalash", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-166", "summary": "62 - Mobil ilovaga antivirus va antifraud funksiyalariga ega xavfsizlik SDK integratsiyasi", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-167", "summary": "64 - Mobil ilovadagi akkauntga 1 daqiqa mobaynida 1 ta IP manzildan 2 va undan ortiq quri…", "type": "История", "status": "Готово", "done": true},
  ],
  "SL-194": [
    {"key": "SL-195", "summary": "[Flutter] Draw UI for full flow", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-196", "summary": "[flutter] Integrate with backend API", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-212", "summary": "Привязка номера телефона к кошелку счет (22616)", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-213", "summary": "[back] BM > p2p/info", "type": "История", "status": "Готово", "done": true},
    {"key": "SL-214", "summary": "[back] BM > p2p/pay", "type": "История", "status": "Готово", "done": true},
  ],
  "SL-203": [
    {"key": "SL-138", "summary": "Drag Metal (Oltin depozit)", "type": "История", "status": "К выполнению", "done": false},
    {"key": "SL-140", "summary": "Add card - analogue: ANOR", "type": "История", "status": "К выполнению", "done": false},
    {"key": "SL-168", "summary": "Visa direct", "type": "История", "status": "К выполнению", "done": false},
    {"key": "SL-170", "summary": "Paynet > Кредит погашение", "type": "История", "status": "К выполнению", "done": false},
    {"key": "SL-171", "summary": "Urban drive", "type": "История", "status": "К выполнению", "done": false},
    {"key": "SL-174", "summary": "Remove 1 hour block for adding virtual Visa/Mastercard", "type": "История", "status": "К выполнению", "done": false},
    {"key": "SL-204", "summary": "Humo moment card", "type": "История", "status": "К выполнению", "done": false},
    {"key": "SL-208", "summary": "Tez QR", "type": "История", "status": "К выполнению", "done": false},
    {"key": "SL-218", "summary": "Humo / Visa cobadge kartalarda cvv ko'rsatish", "type": "История", "status": "К выполнению", "done": false},
    {"key": "SL-242", "summary": "AFIN card", "type": "История", "status": "К выполнению", "done": false},
    {"key": "SL-244", "summary": "EWA (Earned wage success)", "type": "История", "status": "К выполнению", "done": false},
    {"key": "SL-245", "summary": "Оплата на места", "type": "История", "status": "К выполнению", "done": false},
    {"key": "SL-246", "summary": "Емиссия ПК через трастпаи", "type": "История", "status": "К выполнению", "done": false},
    {"key": "SL-247", "summary": "Steam оплата", "type": "История", "status": "К выполнению", "done": false},
    {"key": "SL-249", "summary": "Camera card scan", "type": "История", "status": "К выполнению", "done": false},
    {"key": "SL-250", "summary": "Буквенно-цифровой OTP-код", "type": "История", "status": "К выполнению", "done": false},
    {"key": "SL-251", "summary": "Изучение системы Alipay", "type": "История", "status": "К выполнению", "done": false},
    {"key": "SL-254", "summary": "Проверка владельца номера телефона", "type": "История", "status": "К выполнению", "done": false},
  ],
  "SL-222": [
    {"key": "SL-223", "summary": "Identifikatsiya rasm olishga retry button", "type": "История", "status": "Готово", "done": true},
  ],
  "SL-243": [],
  "SL-252": [],
  "SL-253": [],
};
