/* ============================================================
   AI BI Navigator — Mock data + i18n
   Attached to window.DATA / window.I18N
   ============================================================ */
(function () {
  const REGIONS = [
    { id: 'tashkent',  name: 'Tashkent',  rev: 184.2, plan: 178.0, growth: 8.4,  share: 31 },
    { id: 'samarkand', name: 'Samarkand', rev: 92.6,  plan: 95.0,  growth: 3.1,  share: 16 },
    { id: 'fergana',   name: 'Fergana',   rev: 61.3,  plan: 74.8,  growth: -18.0, share: 10 },
    { id: 'andijan',   name: 'Andijan',   rev: 70.1,  plan: 68.0,  growth: 5.7,  share: 12 },
    { id: 'bukhara',   name: 'Bukhara',   rev: 54.8,  plan: 52.0,  growth: 6.2,  share: 9 },
    { id: 'namangan',  name: 'Namangan',  rev: 63.9,  plan: 60.5,  growth: 4.4,  share: 11 },
    { id: 'khorezm',   name: 'Khorezm',   rev: 41.2,  plan: 43.0,  growth: -2.1, share: 7 },
  ];

  // 12 months revenue (UZS bn) actual + plan
  const MONTHS = ['Jul','Aug','Sep','Oct','Nov','Dec','Jan','Feb','Mar','Apr','May','Jun'];
  const REV_TREND  = [402, 418, 435, 441, 466, 522, 470, 458, 489, 512, 548, 568];
  const PLAN_TREND = [410, 420, 430, 445, 460, 500, 480, 470, 485, 505, 530, 560];

  const KPIS = [
    { id:'revenue', label:'Revenue',         value:'568.1', unit:'bn UZS', delta:+6.8, spark:[440,458,489,512,548,568], icon:'cash', trend:'up', target:560 },
    { id:'profit',  label:'Net profit',      value:'132.4', unit:'bn UZS', delta:+4.2, spark:[112,118,121,126,129,132], icon:'trending', trend:'up', target:128 },
    { id:'volume',  label:'Sales volume',    value:'1.84',  unit:'M units',delta:+2.1, spark:[1.71,1.74,1.77,1.79,1.82,1.84], icon:'box', trend:'up', target:1.9 },
    { id:'plan',    label:'Plan vs Fact',    value:'101.4', unit:'%',      delta:+1.4, spark:[97,98,99,100,101,101.4], icon:'target', trend:'up', target:100 },
    { id:'conv',    label:'Conversion',      value:'4.62',  unit:'%',      delta:-0.5, spark:[5.1,5.0,4.9,4.8,4.7,4.62], icon:'funnel', trend:'down', target:5.0 },
    { id:'growth',  label:'Customer growth', value:'+18.2', unit:'K',      delta:+12.0,spark:[9,11,12,14,16,18.2], icon:'users', trend:'up', target:16 },
    { id:'risk',    label:'Risk alerts',     value:'7',     unit:'active', delta:+3,   spark:[2,3,3,4,5,7], icon:'alert', trend:'down', target:3, danger:true },
    { id:'eff',     label:'Op. efficiency',  value:'87.5',  unit:'%',      delta:+0.9, spark:[84,85,85,86,87,87.5], icon:'gauge', trend:'up', target:90 },
  ];

  const PRODUCTS = [
    { name:'Consumer loans',     rev:148, plan:140, growth:9.1 },
    { name:'POS terminals',      rev:96,  plan:102, growth:-4.2 },
    { name:'Card issuance',      rev:124, plan:118, growth:7.4 },
    { name:'Merchant acquiring', rev:88,  plan:84,  growth:5.3 },
    { name:'Mobile transfers',   rev:112, plan:96,  growth:14.6 },
  ];

  const INSIGHTS = [
    { tone:'neg', text:'Fergana revenue is 18% below plan, driven mainly by a 22% traffic decline and stock-outs in 3 flagship branches.', action:'Run factor analysis' },
    { tone:'pos', text:'Mobile transfers grew 14.6% MoM — the fastest of any product line and 17% ahead of plan.', action:'View product report' },
    { tone:'warn',text:'Conversion slipped to 4.62% (−0.5pp). 12 branches show abnormal drops concentrated in the Fergana valley.', action:'Open alert' },
  ];

  const METRICS = [
    { id:1, name:'Net Revenue', def:'Total recognized revenue net of returns and discounts.', formula:'Σ(gross_sales) − returns − discounts', owner:'Finance', source:'Banking core', freq:'Hourly', trust:98, industry:'Banking', dept:'Finance', fav:true },
    { id:2, name:'Net Promoter Score', def:'Likelihood of customers to recommend, surveyed monthly.', formula:'%promoters − %detractors', owner:'CX', source:'CRM', freq:'Monthly', trust:84, industry:'Retail', dept:'Marketing' },
    { id:3, name:'Conversion Rate', def:'Share of visits resulting in a completed transaction.', formula:'transactions / unique_visits × 100', owner:'Analytics', source:'Retail POS', freq:'Hourly', trust:91, industry:'Retail', dept:'Sales' },
    { id:4, name:'Cost of Risk', def:'Provisions for credit losses as a share of the loan book.', formula:'provisions / avg_loan_portfolio', owner:'Risk', source:'Banking core', freq:'Daily', trust:95, industry:'Banking', dept:'Risk' },
    { id:5, name:'Average Ticket', def:'Mean transaction value per completed sale.', formula:'revenue / transaction_count', owner:'Analytics', source:'Retail POS', freq:'Hourly', trust:93, industry:'Retail', dept:'Sales' },
    { id:6, name:'Active Merchants', def:'Merchants with ≥1 transaction in trailing 30 days.', formula:'distinct(merchant_id) where txn_30d ≥ 1', owner:'Product', source:'Payment processing', freq:'Daily', trust:89, industry:'Fintech', dept:'Product' },
    { id:7, name:'Loan Approval Time', def:'Median hours from application to credit decision.', formula:'median(decision_ts − apply_ts)', owner:'Operations', source:'Banking core', freq:'Daily', trust:90, industry:'Banking', dept:'Operations' },
    { id:8, name:'Plan Fulfillment', def:'Actual revenue vs the approved monthly plan.', formula:'actual / plan × 100', owner:'Finance', source:'1C', freq:'Daily', trust:96, industry:'All', dept:'Finance', fav:true },
    { id:9, name:'Cash Conversion Cycle', def:'Days to convert inventory and receivables into cash.', formula:'DIO + DSO − DPO', owner:'Finance', source:'1C', freq:'Weekly', trust:88, industry:'Construction', dept:'Finance' },
    { id:10, name:'Table Turnover', def:'Average number of guest seatings per table per day.', formula:'covers / (tables × open_days)', owner:'Operations', source:'POS', freq:'Daily', trust:82, industry:'HoReCa', dept:'Operations' },
    { id:11, name:'Churn Rate', def:'Share of customers lost over the period.', formula:'lost_customers / start_customers', owner:'CX', source:'CRM', freq:'Weekly', trust:86, industry:'Fintech', dept:'Marketing' },
    { id:12, name:'Gross Margin', def:'Gross profit as a percentage of net revenue.', formula:'(revenue − COGS) / revenue', owner:'Finance', source:'1C', freq:'Daily', trust:94, industry:'Retail', dept:'Finance' },
  ];

  const DASHBOARDS = [
    { id:'ceo', name:'CEO Cockpit', owner:'Bobur Zokirov', updated:'12 min ago', widgets:14, access:'Executive', accent:'#3b82f6', tag:'Executive' },
    { id:'retail', name:'Retail Sales Dashboard', owner:'Nodira Yusupova', updated:'1 hour ago', widgets:18, access:'Department', accent:'#22d3ee', tag:'Retail' },
    { id:'bank', name:'Bank Portfolio Dashboard', owner:'Risk Office', updated:'34 min ago', widgets:22, access:'Restricted', accent:'#a78bfa', tag:'Banking' },
    { id:'fintech', name:'Fintech Transactions', owner:'Sardor Aliyev', updated:'4 min ago', widgets:16, access:'Department', accent:'#34d399', tag:'Fintech' },
    { id:'region', name:'Regional Performance', owner:'Bobur Zokirov', updated:'22 min ago', widgets:11, access:'Company', accent:'#f59e0b', tag:'Regional' },
    { id:'construction', name:'Construction Projects', owner:'Jasur Toshev', updated:'2 hours ago', widgets:9, access:'Department', accent:'#fb7185', tag:'Construction' },
    { id:'horeca', name:'HoReCa Operations', owner:'Kamola Rashidova', updated:'48 min ago', widgets:13, access:'Department', accent:'#60a5fa', tag:'HoReCa' },
  ];

  const ALERTS = [
    { id:1, title:'Fergana sales dropped by 18%', sev:'High', impact:'−13.5 bn UZS', cause:'Traffic decline + stock-outs in 3 branches', owner:'Nodira Yusupova', status:'New', when:'2h ago', metric:'Net Revenue', region:'Fergana' },
    { id:2, title:'Conversion decreased in 12 branches', sev:'High', impact:'−2.1 bn UZS', cause:'Checkout abandonment spike on mobile', owner:'Analytics', status:'In progress', when:'5h ago', metric:'Conversion Rate', region:'Multiple' },
    { id:3, title:'Cash flow plan is below target', sev:'Medium', impact:'−8.0 bn UZS', cause:'Delayed receivables from 2 large merchants', owner:'Finance', status:'In progress', when:'1d ago', metric:'Plan Fulfillment', region:'Tashkent' },
    { id:4, title:'Loan approval time increased', sev:'Medium', impact:'+9 hrs median', cause:'Manual review queue backlog', owner:'Operations', status:'New', when:'1d ago', metric:'Loan Approval Time', region:'All' },
    { id:5, title:'POS terminal revenue 4% under plan', sev:'Low', impact:'−6.0 bn UZS', cause:'Slower merchant onboarding', owner:'Sardor Aliyev', status:'Resolved', when:'3d ago', metric:'Active Merchants', region:'Samarkand' },
    { id:6, title:'Cost of risk above threshold', sev:'High', impact:'+0.6pp', cause:'Rising delinquency in consumer loans', owner:'Risk Office', status:'New', when:'6h ago', metric:'Cost of Risk', region:'Andijan' },
  ];

  const FACTORS = [
    { id:'traffic', name:'Lower foot traffic', contrib:38, delta:-22, trend:'down', note:'Visits fell 22% YoY across valley branches.' },
    { id:'stock',   name:'Product stock-outs', contrib:27, delta:-31, trend:'down', note:'3 flagship branches out of top-5 SKUs for 9 days.' },
    { id:'conv',    name:'Lower conversion',   contrib:18, delta:-0.7, trend:'down', note:'Checkout completion dropped 0.7pp on mobile.' },
    { id:'comp',    name:'Competitor campaign',contrib:11, delta:-9,  trend:'down', note:'New rival promo launched in Fergana on Apr 14.' },
    { id:'staff',   name:'Staff performance',  contrib:6,  delta:-4,  trend:'down', note:'Two senior reps on leave; ramp gap on floor.' },
  ];

  const DOCS = [
    { id:1, name:'Q2 Board Report 2026', type:'pdf', size:'4.2 MB', folder:'Board', date:'Jun 5', pages:38 },
    { id:2, name:'Retail Strategy Deck', type:'ppt', size:'12.8 MB', folder:'Strategy', date:'Jun 2', pages:42 },
    { id:3, name:'Fergana Branch Audit', type:'pdf', size:'1.9 MB', folder:'Audit', date:'May 28', pages:16 },
    { id:4, name:'Loan Portfolio Model', type:'xls', size:'8.1 MB', folder:'Finance', date:'May 26', pages:null },
    { id:5, name:'Merchant Onboarding SLA', type:'pdf', size:'820 KB', folder:'Operations', date:'May 22', pages:9 },
    { id:6, name:'2026 Annual Plan', type:'xls', size:'5.4 MB', folder:'Finance', date:'May 19', pages:null },
    { id:7, name:'Risk Committee Minutes', type:'pdf', size:'640 KB', folder:'Board', date:'May 15', pages:6 },
    { id:8, name:'POS Network Map', type:'ppt', size:'9.3 MB', folder:'Operations', date:'May 12', pages:24 },
  ];

  const CONNECTORS = [
    { id:'postgres', name:'PostgreSQL', cat:'Database', status:'connected', sync:'2 min ago', vol:'1.4 TB', owner:'Data Eng', sec:'High' },
    { id:'clickhouse', name:'ClickHouse', cat:'Database', status:'connected', sync:'1 min ago', vol:'6.2 TB', owner:'Data Eng', sec:'High' },
    { id:'mssql', name:'MS SQL Server', cat:'Database', status:'connected', sync:'8 min ago', vol:'920 GB', owner:'IT Admin', sec:'High' },
    { id:'mysql', name:'MySQL', cat:'Database', status:'syncing', sync:'now', vol:'340 GB', owner:'Data Eng', sec:'Medium' },
    { id:'oracle', name:'Oracle', cat:'Database', status:'connected', sync:'15 min ago', vol:'2.1 TB', owner:'IT Admin', sec:'High' },
    { id:'excel', name:'Excel', cat:'File', status:'connected', sync:'1 day ago', vol:'48 MB', owner:'Finance', sec:'Low' },
    { id:'csv', name:'CSV', cat:'File', status:'connected', sync:'3 hrs ago', vol:'120 MB', owner:'Analytics', sec:'Low' },
    { id:'json', name:'JSON', cat:'File', status:'idle', sync:'2 days ago', vol:'8 MB', owner:'Data Eng', sec:'Low' },
    { id:'xml', name:'XML', cat:'File', status:'idle', sync:'5 days ago', vol:'14 MB', owner:'IT Admin', sec:'Low' },
    { id:'gsheets', name:'Google Sheets', cat:'Cloud', status:'connected', sync:'20 min ago', vol:'22 MB', owner:'Marketing', sec:'Medium' },
    { id:'1c', name:'1C:Enterprise', cat:'ERP', status:'connected', sync:'12 min ago', vol:'410 GB', owner:'Finance', sec:'High' },
    { id:'bitrix', name:'Bitrix24', cat:'CRM', status:'connected', sync:'30 min ago', vol:'180 GB', owner:'Sales', sec:'Medium' },
    { id:'crm', name:'CRM System', cat:'CRM', status:'error', sync:'failed', vol:'260 GB', owner:'Sales', sec:'Medium' },
    { id:'core', name:'Banking Core', cat:'Core', status:'connected', sync:'1 min ago', vol:'9.8 TB', owner:'IT Admin', sec:'Critical' },
    { id:'payments', name:'Payment Processing', cat:'Core', status:'connected', sync:'1 min ago', vol:'3.3 TB', owner:'IT Admin', sec:'Critical' },
    { id:'pos', name:'Retail POS', cat:'Core', status:'connected', sync:'4 min ago', vol:'1.1 TB', owner:'Retail', sec:'High' },
  ];

  const TEMPLATES = [
    { id:'bank', name:'Bank', accent:'#3b82f6', kpis:['Cost of Risk','Net Interest Margin','Loan Approval Time','Capital Adequacy'], dashboards:['Portfolio','Risk Cockpit','Branch Network'], sources:['Banking Core','1C','CRM'], alerts:['Delinquency spike','NIM compression'] },
    { id:'fintech', name:'Payment / Fintech', accent:'#34d399', kpis:['Active Merchants','TPV','Auth Rate','Churn Rate'], dashboards:['Transactions','Merchant Health','Fraud Monitor'], sources:['Payment Processing','PostgreSQL','ClickHouse'], alerts:['Auth-rate drop','Fraud anomaly'] },
    { id:'retail', name:'Retail Electronics', accent:'#22d3ee', kpis:['Conversion Rate','Average Ticket','Gross Margin','Stock Cover'], dashboards:['Sales','Inventory','Store Performance'], sources:['Retail POS','1C','Google Sheets'], alerts:['Stock-out risk','Conversion drop'] },
    { id:'construction', name:'Construction', accent:'#f59e0b', kpis:['Cash Conversion Cycle','Project Margin','Schedule Variance','Cost Variance'], dashboards:['Project Control','Cash Flow','Procurement'], sources:['1C','Excel','MS SQL'], alerts:['Budget overrun','Schedule slip'] },
    { id:'gov', name:'Government Org', accent:'#a78bfa', kpis:['Service SLA','Budget Execution','Citizen Requests','Resolution Time'], dashboards:['Service Delivery','Budget','Regional KPIs'], sources:['PostgreSQL','Oracle','XML'], alerts:['SLA breach','Budget underuse'] },
    { id:'horeca', name:'HoReCa', accent:'#60a5fa', kpis:['Table Turnover','Average Check','Food Cost %','Labor Cost %'], dashboards:['Operations','Menu Performance','Staffing'], sources:['POS','Excel','Google Sheets'], alerts:['Food cost spike','Low turnover'] },
    { id:'edu', name:'Education', accent:'#f472b6', kpis:['Enrollment','Retention','Completion Rate','Revenue per Student'], dashboards:['Admissions','Academic','Finance'], sources:['MySQL','CSV','Google Sheets'], alerts:['Dropout risk','Enrollment dip'] },
    { id:'logistics', name:'Logistics', accent:'#2dd4bf', kpis:['On-time Delivery','Cost per KM','Fleet Utilization','Order Cycle Time'], dashboards:['Fleet','Delivery','Warehouse'], sources:['PostgreSQL','1C','Bitrix24'], alerts:['Delivery delay','Idle fleet'] },
  ];

  const USERS = [
    { id:1, name:'Bobur Zokirov', email:'b.zokirov@navigator.uz', role:'CEO', dept:'Executive', status:'Active', color:'#3b82f6', mfa:true },
    { id:2, name:'Nodira Yusupova', email:'n.yusupova@navigator.uz', role:'Department Head', dept:'Retail', status:'Active', color:'#22d3ee', mfa:true },
    { id:3, name:'Sardor Aliyev', email:'s.aliyev@navigator.uz', role:'Business Analyst', dept:'Fintech', status:'Active', color:'#34d399', mfa:false },
    { id:4, name:'Kamola Rashidova', email:'k.rashidova@navigator.uz', role:'Data Analyst', dept:'Analytics', status:'Active', color:'#a78bfa', mfa:true },
    { id:5, name:'Jasur Toshev', email:'j.toshev@navigator.uz', role:'Regional Manager', dept:'Construction', status:'Active', color:'#f59e0b', mfa:true },
    { id:6, name:'Dilshod Umarov', email:'d.umarov@navigator.uz', role:'Data Admin', dept:'IT', status:'Active', color:'#fb7185', mfa:true },
    { id:7, name:'Malika Tursunova', email:'m.tursunova@navigator.uz', role:'Finance Manager', dept:'Finance', status:'Invited', color:'#60a5fa', mfa:false },
  ];

  const PERMISSIONS = ['View dashboards','Build widgets','Manage connectors','Export reports','Admin access','Row-level data'];
  const ROLE_MATRIX = {
    'CEO':            [true,true,false,true,false,true],
    'Department Head':[true,true,false,true,false,true],
    'Business Analyst':[true,true,false,true,false,false],
    'Data Analyst':   [true,true,true,true,false,false],
    'Data Admin':     [true,true,true,true,true,true],
    'Regional Manager':[true,false,false,true,false,true],
    'Finance Manager':[true,true,false,true,false,true],
  };

  const AUDIT = [
    { id:1, user:'Dilshod Umarov', action:'Granted admin role', target:'Malika Tursunova', when:'Today 14:22', type:'security', ip:'10.4.2.18' },
    { id:2, user:'Bobur Zokirov', action:'Exported report', target:'Q2 Board Report', when:'Today 11:08', type:'export', ip:'10.4.1.4' },
    { id:3, user:'Sardor Aliyev', action:'Connected source', target:'ClickHouse', when:'Today 09:41', type:'data', ip:'10.4.3.22' },
    { id:4, user:'System', action:'Sync completed', target:'Banking Core', when:'Today 09:40', type:'system', ip:'—' },
    { id:5, user:'Nodira Yusupova', action:'Shared dashboard', target:'Retail Sales', when:'Yesterday 17:55', type:'access', ip:'10.4.2.7' },
    { id:6, user:'Kamola Rashidova', action:'Edited metric', target:'Conversion Rate', when:'Yesterday 16:30', type:'data', ip:'10.4.3.19' },
    { id:7, user:'CRM System', action:'Sync failed', target:'CRM System', when:'Yesterday 15:12', type:'error', ip:'—' },
    { id:8, user:'Dilshod Umarov', action:'Updated RLS policy', target:'Regional data', when:'Yesterday 10:02', type:'security', ip:'10.4.2.18' },
  ];

  const REPORTS = [
    { id:'weekly', name:'Weekly CEO Summary', cadence:'Every Monday 08:00', recipients:6, format:'PDF', last:'Jun 3', icon:'crown' },
    { id:'board', name:'Monthly Board Report', cadence:'1st of month', recipients:12, format:'PDF', last:'Jun 1', icon:'building' },
    { id:'dept', name:'Department Report', cadence:'Weekly', recipients:18, format:'PDF + XLS', last:'Jun 5', icon:'layers' },
    { id:'risk', name:'Risk Report', cadence:'Daily', recipients:8, format:'PDF', last:'Today', icon:'alert' },
    { id:'sales', name:'Sales Report', cadence:'Daily', recipients:22, format:'XLS', last:'Today', icon:'cash' },
  ];

  const AI_PROMPTS = [
    'Show sales decline reasons in Fergana',
    'Compare revenue by region for the last 6 months',
    'Find products below plan',
    'Generate CEO summary for this week',
    'Which branches have abnormal conversion drop?',
  ];

  // role configs
  const ROLES = {
    CEO:           { title:'Chief Executive', greeting:'Executive overview', color:'#3b82f6', home:'dashboard' },
    Analyst:       { title:'Business Analyst', greeting:'Analytics workspace', color:'#22d3ee', home:'ai' },
    'Department Head': { title:'Department Head', greeting:'Department performance', color:'#34d399', home:'dashboard' },
    'Data Admin':  { title:'Data Administrator', greeting:'Platform administration', color:'#a78bfa', home:'connectors' },
  };

  window.DATA = { REGIONS, MONTHS, REV_TREND, PLAN_TREND, KPIS, PRODUCTS, INSIGHTS, METRICS,
    DASHBOARDS, ALERTS, FACTORS, DOCS, CONNECTORS, TEMPLATES, USERS, PERMISSIONS, ROLE_MATRIX,
    AUDIT, REPORTS, AI_PROMPTS, ROLES };

  /* ---------------- i18n ---------------- */
  const I18N = {
    en: {
      // nav
      nav_dashboard:'Executive Dashboard', nav_ai:'AI Analyst', nav_metrics:'Metrics Catalog',
      nav_library:'Dashboard Library', nav_widget:'Widget Builder', nav_alerts:'Alerts & Deviations',
      nav_factor:'Factor Analysis', nav_docs:'Document Library', nav_connectors:'Data Sources',
      nav_templates:'Industry Templates', nav_reports:'Reports', nav_admin:'Admin & Access',
      nav_audit:'Audit Log', nav_settings:'Settings',
      search:'Search metrics, dashboards, documents…', ask_ai:'Ask AI', enter_demo:'Enter demo',
      grp_analyze:'Analyze', grp_build:'Build', grp_govern:'Govern',
      // common
      close:'Close', cancel:'Cancel', save:'Save', reset:'Reset', details:'Details',
      view_all:'View all', export:'Export', open:'Open', share:'Share', copy:'Copy',
      duplicate:'Duplicate', assign:'Assign', generate:'Generate', finish:'Finish',
      continue_:'Continue', back:'Back', save_changes:'Save changes', upload:'Upload',
      // login
      login_title:'Enter the demo',
      login_sub:'Choose a role to preview a tailored experience.',
      login_lang_label:'Language',
      login_enter_as:'Enter demo as',
      login_note:'Demo environment · mock data only · no authentication',
      login_brand_tag:'AI-native Business Intelligence',
      login_hero1:'Decisions, driven by',
      login_hero2:'data you can trust.',
      login_hero_desc:'Connect every source, ask questions in plain language, detect deviations before they cost you, and brief your board in seconds — built for banks, retail, fintech and government across Uzbekistan.',
      login_stat_connectors:'Data connectors',
      login_stat_templates:'Industry templates',
      login_stat_ai:'AI answers',
      login_onprem:'On-premise ready',
      login_residency:'Data residency in UZ',
      login_audit_trail:'Full audit trail',
      role_ceo_desc:'Chairman / Top manager',
      role_analyst_desc:'Business & data analyst',
      role_dhead_desc:'Regional & finance lead',
      role_dadmin_desc:'IT & platform admin',
      // dashboard
      dash_sub:'Company performance · Updated 12 min ago',
      dash_welcome:'Welcome back,',
      dash_period_changed:'Period changed',
      dash_exported:'Dashboard exported',
      dash_layout_saved:'Dashboard layout saved',
      btn_export:'Export', btn_customize:'Customize', btn_ask_ai:'Ask AI',
      dash_rev_trend:'Revenue trend',
      dash_rev_sub:'Actual vs plan · bn UZS · 12 months',
      legend_actual:'Actual', legend_plan:'Plan',
      ai_insights:'AI Insights',
      lbl_new:'new',
      regional_perf:'Regional performance',
      plan_vs_fact:'Plan vs Fact',
      pvf_sub:'By product line · bn UZS',
      op_efficiency:'Operational efficiency',
      eff_target:'vs 90% target',
      label_conv:'Conversion', label_alerts:'Alerts',
      prod_perf:'Product / category performance',
      open_report:'Open report',
      tbl_product:'Product line', tbl_revenue:'Revenue', tbl_plan:'Plan',
      tbl_vs_plan:'vs Plan', tbl_growth:'Growth',
      active_alerts_title:'Active alerts',
      drill_sub:'Drill-down detail · mock data',
      this_period:'This period', last_period:'Last period',
      forecast:'Forecast', trend_breakdown:'Trend breakdown',
      ai_interpretation:'AI interpretation',
      ai_drill_text:'Performance is 1.4% ahead of plan, led by mobile transfers and card issuance. Fergana remains the single largest drag; recovering it would add ~13.5 bn UZS this quarter.',
      ask_ai_this:'Ask AI about this',
      customize_title:'Customize dashboard',
      customize_sub:'Toggle KPI cards and widgets',
      lbl_kpi_cards:'KPI cards',
      save_layout:'Save layout',
      lbl_filtered:'Filtered:',
      // kpi labels
      kpi_revenue:'Revenue', kpi_profit:'Net profit', kpi_volume:'Sales volume',
      kpi_plan:'Plan vs Fact', kpi_conv:'Conversion', kpi_growth:'Customer growth',
      kpi_risk:'Risk alerts', kpi_eff:'Op. efficiency',
      // alerts
      alerts_sub:'Automatic deviation detection across all metrics',
      detection_rules:'Detection rules',
      high_sev_open:'High-severity open',
      total_open:'Total open',
      est_impact:'Est. business impact',
      tab_all:'All', tab_new:'New', tab_inprogress:'In progress', tab_resolved:'Resolved',
      lbl_n_alerts:'alerts',
      create_task:'Create task', analyze_reason:'Analyze reason',
      lbl_biz_impact:'Business impact', lbl_responsible:'Responsible',
      lbl_metric:'Metric', lbl_region:'Region',
      deviation_timeline:'Deviation timeline',
      root_cause_preview:'Root cause preview',
      root_cause_cta:'Run factor analysis to decompose the contribution of each driver and get recommended actions.',
      task_title_lbl:'Task title',
      lbl_assignee:'Assignee', lbl_priority:'Priority', lbl_due_date:'Due date', lbl_notes:'Notes',
      investigate_prefix:'Investigate:',
      default_notes:'Investigate the deviation and propose corrective actions.',
      task_created:'Task created & assigned',
      // metrics
      metrics_sub_1:'governed indicators · single source of truth',
      btn_new_metric:'New metric',
      search_metrics:'Search metrics…',
      more_filters:'More filters',
      trust_score:'Trust score',
      high_confidence:'High confidence · validated lineage',
      review_recommended:'Review recommended',
      lbl_definition:'Definition', lbl_formula:'Formula',
      lbl_data_owner:'Data owner', lbl_source_system:'Source system',
      lbl_update_freq:'Update frequency', lbl_department:'Department',
      use_in_dashboard:'Use in dashboard', add_to_builder:'Add to builder',
      ask_ai_metric:'Ask AI about this metric',
      metric_draft_created:'New metric draft created',
      metric_added_widget:'Metric added to widget builder',
      // factor
      factor_sub:'Root-cause decomposition · AI-assisted',
      mgmt_summary:'Management summary',
      export_to_report:'Export to report',
      sel_problem:'Selected problem',
      lbl_deviation:'Deviation', lbl_impact:'Impact',
      contribution_ranking:'Contribution ranking',
      segment_comparison:'Segment comparison',
      ai_explanation:'AI explanation',
      ai_explanation_text:'Lower foot traffic and stock-outs together explain 65% of the Fergana shortfall. The decline accelerated after a competitor campaign on Apr 14.',
      recommended_actions:'Recommended actions',
      factor_action1:'Replenish top-5 SKUs in 3 flagship branches within 48h',
      factor_action2:'Launch counter-promotion in Fergana valley',
      factor_action3:'Add 2 floor staff during peak hours for 2 weeks',
      mgmt_summary_sub:'AI-generated · Fergana sales decline',
      mgmt_summary_badge:'Generated in 1.4s',
      mgmt_summary_text:'Fergana revenue is 18% below plan (−13.5 bn UZS this quarter). Decomposition shows 65% of the gap comes from lower foot traffic (−22%) and stock-outs in 3 flagship branches, amplified by a competitor campaign from Apr 14.',
      mgmt_rec_title:'Recommended decisions',
      mgmt_rec1:'Emergency SKU replenishment (48h)',
      mgmt_rec2:'Fergana counter-promotion budget approval',
      mgmt_rec3:'Temporary staffing reinforcement',
      mgmt_recovery:'Expected recovery: ~9–11 bn UZS over the next two months if actions are taken this week.',
      problem_title:'Sales dropped in Fergana',
      added_to_report:'Added to report builder',
      // library
      btn_new_dashboard:'New dashboard',
      share_dashboard:'Share dashboard',
      invite_people:'Invite people',
      access_level:'Access level',
      can_view:'Can view', can_edit:'Can edit', full_access:'Full access',
      people_access:'People with access',
      tbl_dashboard:'Dashboard', tbl_owner:'Owner', tbl_access:'Access',
      tbl_widgets:'Widgets', tbl_updated:'Updated',
      menu_open:'Open', menu_duplicate:'Duplicate', menu_share:'Share', menu_export_pdf:'Export PDF',
      link_copied:'Link copied',
      dashboard_shared:'Dashboard shared',
      dashboard_duplicated:'Dashboard duplicated',
      // widget
      widget_sub:'No-code widget constructor · drag-free configuration',
      lbl_data_source:'Data source', lbl_dimension:'Dimension', lbl_chart_type:'Chart type',
      lbl_filters:'Filters', add_filter:'Add filter',
      ai_suggestion:'AI suggestion', save_widget:'Save widget',
      preview_label:'Preview', live_hourly:'Live · hourly',
      ai_recommends_bar:'AI recommends Bar for this data',
      widget_saved:'Widget saved to dashboard',
      ai_suggested:'AI suggested: Bar chart by region',
      by_label:'by',
      // templates
      templates_sub:'Pre-built KPI sets, dashboards and alerts — adapted for Uzbekistan',
      rec_kpis:'Recommended KPIs',
      req_sources:'Required sources',
      example_alerts:'Example alerts',
      use_template:'Use template',
      rec_config:'Recommended configuration',
      template_created:'dashboard created',
      // reports
      reports_sub:'Automated reporting with AI summaries',
      btn_new_report:'New report',
      new_report_opened:'New report builder opened',
      btn_generate:'Generate', btn_schedule_report:'Schedule',
      generating_prefix:'Generating',
      agg_metrics:'Aggregating metrics',
      detecting_devs:'Detecting deviations',
      writing_summary:'Writing AI summary',
      report_preview:'Report preview',
      ai_summary_incl:'AI summary included',
      exec_summary:'Executive summary',
      exec_summary_text:'Revenue reached 568 bn UZS (+6.8% MoM), 1.4% ahead of plan. Net profit grew 4.2%. The key risk is Fergana (−18%); 7 alerts are active with 1 high-severity item unresolved.',
      export_pdf:'Export PDF',
      schedule_delivery:'Schedule delivery',
      lbl_frequency:'Frequency', lbl_day:'Day', lbl_time_field:'Time',
      lbl_recipients_field:'Recipients',
      sched_note:'Delivered as PDF with embedded AI summary every Monday at 08:00.',
      report_exported:'Report exported as PDF',
      email_scheduled:'Email delivery scheduled',
      // connectors
      btn_add_connector:'Add connector',
      status_connected:'Connected', status_syncing:'Syncing',
      status_idle:'Idle', status_errors:'Errors',
      lbl_last_sync:'Last sync', lbl_volume:'Volume', lbl_security:'Security',
      btn_sync_now:'Sync now', syncing_label:'Syncing…',
      connect_prefix:'Connect',
      step_credentials:'Credentials', step_tables:'Tables', step_permissions:'Permissions',
      step_schedule:'Schedule', step_test:'Test', step_label:'Step',
      lbl_host:'Host', lbl_port:'Port', lbl_database:'Database',
      lbl_username:'Username', lbl_password:'Password',
      select_tables:'Select tables to sync',
      rls_title:'Row-level security',
      apply_regional:'Apply regional data restrictions',
      lbl_access_role:'Access role',
      analytics_read:'Analytics (read-only)', admin_full:'Admin (full)',
      sync_freq:'Sync frequency',
      conn_success:'Connection successful',
      conn_tested:'Tested in 0.4s · 3 tables · 1.2M rows ready to sync',
      conn_configured:'Connector configured & connected',
      sync_completed:'Sync completed',
      incremental_note:'Incremental sync every hour, full refresh nightly at 02:00.',
      // documents
      docs_sub:'AI document intelligence · summarize, query, extract',
      mode_summary:'Summarize', mode_ask:'Ask', mode_extract:'Extract', mode_brief:'Brief',
      reading_doc:'Reading document…',
      ai_summary_label:'AI summary',
      ai_summary_doc_text:'This report covers Q2 performance. Revenue is ahead of plan but the Fergana region underperforms by 18%. It recommends emergency replenishment and a regional promotion. Cost of risk is rising and warrants monitoring.',
      meeting_brief:'Meeting brief',
      add_to_catalog:'Add to Metrics Catalog',
      metrics_suggested:'Metrics suggested for catalog',
      upload_opened:'Upload dialog opened',
      brief_item1:'Revenue +6.8%, ahead of plan',
      brief_item2:'Fergana −18% — decision needed on recovery plan',
      brief_item3:'Approve emergency SKU replenishment budget',
      brief_item4:'Review rising cost of risk',
      // admin
      btn_add_user:'Add user',
      on_premise:'On-premise deployment',
      on_premise_desc:'Self-hosted in client datacenter · air-gap option available',
      data_residency:'Data residency: Uzbekistan',
      data_residency_desc:'All data stored within national borders · compliant',
      tab_users:'Users', tab_roles:'Roles', tab_access_matrix:'Access Matrix', tab_workflow:'Workflow',
      tbl_user:'User', tbl_role:'Role', tbl_dept:'Department', tbl_mfa:'MFA', tbl_status:'Status',
      mfa_on:'On', mfa_off:'Off', lbl_n_users:'users',
      add_user_title:'Add user', add_user_sub:'Invite a team member',
      lbl_full_name:'Full name', lbl_email:'Email',
      lbl_role_label:'Role', lbl_dept_label:'Department',
      require_mfa:'Require multi-factor authentication',
      send_invite:'Send invite', invite_sent:'Invitation sent',
      approver_label:'Approver:',
      workflow_active:'Active',
      // audit
      audit_sub:'Immutable record of all platform activity',
      tbl_event:'Event', tbl_user_col:'User', tbl_target:'Target', tbl_ip:'IP', tbl_time:'Time',
      // settings
      settings_sub:'Configure your workspace',
      tab_company:'Company', tab_appearance:'Appearance', tab_notifications:'Notifications',
      tab_ai_asst:'AI Assistant', tab_data:'Data', tab_security_tab:'Security',
      company_profile:'Company profile',
      lbl_company_name:'Company name', lbl_industry:'Industry',
      lbl_country:'Country', lbl_currency:'Base currency', lbl_fiscal:'Fiscal year start',
      appearance_title:'Appearance',
      lbl_theme:'Theme', theme_dark:'Dark', theme_light:'Light', lbl_language:'Language',
      notif_title:'Notifications',
      notif_alerts_lbl:'High-severity alerts', notif_alerts_desc:'Instant push + email',
      notif_reports_lbl:'Scheduled reports', notif_reports_desc:'When a report is delivered',
      notif_weekly_lbl:'Weekly digest', notif_weekly_desc:'Monday morning summary',
      ai_asst_title:'AI Assistant',
      lbl_response_style:'Response style',
      style_concise:'Concise', style_balanced:'Balanced', style_detailed:'Detailed',
      voice_input:'Voice input', voice_input_desc:'Enable microphone for questions',
      proactive_insights:'Proactive insights', proactive_insights_desc:'Surface anomalies automatically',
      lbl_data_scope:'Data scope',
      scope_company:'Company-wide (respecting permissions)', scope_dept:'My department only',
      data_refresh_title:'Data refresh',
      lbl_refresh:'Default refresh interval',
      lbl_cache:'Cache duration',
      cache_5m:'5 minutes', cache_15m:'15 minutes', cache_1h:'1 hour',
      lower_intervals_note:'Lower intervals increase load on source systems.',
      security_title:'Security',
      sso_label:'Single sign-on (SSO)', sso_desc:'SAML 2.0 / OIDC',
      masking_label:'Data masking', masking_desc:'Mask sensitive fields for non-admins',
      session_timeout:'Session timeout',
      timeout_30m:'30 minutes', timeout_1h:'1 hour', timeout_8h:'8 hours',
      settings_saved:'Settings saved',
      // notifications panel
      notif_header:'Notifications', notif_n_new:'new',
      notif1_title:'Fergana sales dropped 18%',
      notif2_title:'Weekly CEO summary is ready',
      notif3_title:'CRM sync failed',
      notif4_title:'Banking Core synced',
      // profile menu
      profile_sign_out:'Sign out & switch role',
      profile_admin_access:'Admin & Access',
      // mobile
      mobile_greeting:'Good morning,',
      company_overview:'Company overview',
      ai_brief:'AI brief',
      ai_brief_text:'Revenue 568 bn UZS (+6.8%), 1.4% ahead of plan. Fergana −18% is the main risk this week.',
      mobile_ask_ai:'Ask AI a question',
      mobile_home:'Home', mobile_ai_label:'AI', mobile_alerts_label:'Alerts',
      mobile_boards:'Boards', mobile_data_label:'Data',
      close_preview:'Close preview',
      mobile_preview_label:'Mobile preview · responsive layout',
      // ai screen
      ai_screen_sub:'Ask business questions in natural language — GenBI generates charts, insights and actions.',
      new_chat:'New chat',
      // coming soon
      coming_soon_sub:'This screen is being assembled.',
      // detection rules opened
      detection_rules_opened:'Detection rules opened',
    },

    ru: {
      // nav
      nav_dashboard:'Дашборд руководителя', nav_ai:'AI-аналитик', nav_metrics:'Каталог метрик',
      nav_library:'Библиотека дашбордов', nav_widget:'Конструктор виджетов', nav_alerts:'Оповещения',
      nav_factor:'Факторный анализ', nav_docs:'Библиотека документов', nav_connectors:'Источники данных',
      nav_templates:'Отраслевые шаблоны', nav_reports:'Отчёты', nav_admin:'Администрирование',
      nav_audit:'Журнал аудита', nav_settings:'Настройки',
      search:'Поиск метрик, дашбордов, документов…', ask_ai:'Спросить ИИ', enter_demo:'Войти в демо',
      grp_analyze:'Анализ', grp_build:'Создание', grp_govern:'Управление',
      // common
      close:'Закрыть', cancel:'Отмена', save:'Сохранить', reset:'Сбросить', details:'Детали',
      view_all:'Показать все', export:'Экспорт', open:'Открыть', share:'Поделиться', copy:'Копировать',
      duplicate:'Дублировать', assign:'Назначить', generate:'Сформировать', finish:'Завершить',
      continue_:'Продолжить', back:'Назад', save_changes:'Сохранить изменения', upload:'Загрузить',
      // login
      login_title:'Войти в демо',
      login_sub:'Выберите роль для персонализированного демо-просмотра.',
      login_lang_label:'Язык',
      login_enter_as:'Войти как',
      login_note:'Демо-среда · только тестовые данные · без аутентификации',
      login_brand_tag:'AI-нативная бизнес-аналитика',
      login_hero1:'Решения, основанные на',
      login_hero2:'данных, которым вы доверяете.',
      login_hero_desc:'Подключайте любые источники, задавайте вопросы на естественном языке, обнаруживайте отклонения до того, как они станут убытками, и готовьте отчёты для совета директоров за секунды — решение для банков, ритейла, финтеха и государственных организаций Узбекистана.',
      login_stat_connectors:'Коннекторов данных',
      login_stat_templates:'Отраслевых шаблонов',
      login_stat_ai:'Ответы ИИ',
      login_onprem:'Поддержка on-premise',
      login_residency:'Хранение данных в UZ',
      login_audit_trail:'Полный журнал аудита',
      role_ceo_desc:'Председатель / Топ-менеджер',
      role_analyst_desc:'Бизнес и дата-аналитик',
      role_dhead_desc:'Региональный и финансовый руководитель',
      role_dadmin_desc:'IT и платформенный администратор',
      // dashboard
      dash_sub:'Показатели компании · Обновлено 12 мин назад',
      dash_welcome:'С возвращением,',
      dash_period_changed:'Период изменён',
      dash_exported:'Дашборд экспортирован',
      dash_layout_saved:'Макет дашборда сохранён',
      btn_export:'Экспорт', btn_customize:'Настроить', btn_ask_ai:'Спросить ИИ',
      dash_rev_trend:'Тренд выручки',
      dash_rev_sub:'Факт vs план · млрд UZS · 12 месяцев',
      legend_actual:'Факт', legend_plan:'План',
      ai_insights:'AI-инсайты',
      lbl_new:'новых',
      regional_perf:'Региональные показатели',
      plan_vs_fact:'План vs Факт',
      pvf_sub:'По продуктам · млрд UZS',
      op_efficiency:'Операционная эффективность',
      eff_target:'vs цель 90%',
      label_conv:'Конверсия', label_alerts:'Оповещения',
      prod_perf:'Эффективность по продуктам / категориям',
      open_report:'Открыть отчёт',
      tbl_product:'Продуктовая линия', tbl_revenue:'Выручка', tbl_plan:'План',
      tbl_vs_plan:'vs План', tbl_growth:'Рост',
      active_alerts_title:'Активные оповещения',
      drill_sub:'Детализация · тестовые данные',
      this_period:'Текущий период', last_period:'Прошлый период',
      forecast:'Прогноз', trend_breakdown:'Анализ тренда',
      ai_interpretation:'Интерпретация ИИ',
      ai_drill_text:'Выполнение плана на 1,4% выше, за счёт мобильных переводов и выпуска карт. Фергана остаётся главным тормозом; восстановление добавит ~13,5 млрд UZS в квартале.',
      ask_ai_this:'Спросить ИИ об этом',
      customize_title:'Настройка дашборда',
      customize_sub:'Включайте/выключайте KPI-карточки и виджеты',
      lbl_kpi_cards:'KPI-карточки',
      save_layout:'Сохранить макет',
      lbl_filtered:'Фильтр:',
      // kpi labels
      kpi_revenue:'Выручка', kpi_profit:'Чистая прибыль', kpi_volume:'Объём продаж',
      kpi_plan:'План vs Факт', kpi_conv:'Конверсия', kpi_growth:'Рост клиентов',
      kpi_risk:'Активные риски', kpi_eff:'Опер. эффективность',
      // alerts
      alerts_sub:'Автоматическое выявление отклонений по всем метрикам',
      detection_rules:'Правила обнаружения',
      high_sev_open:'Критических (открытых)',
      total_open:'Всего открытых',
      est_impact:'Ожидаемый бизнес-эффект',
      tab_all:'Все', tab_new:'Новые', tab_inprogress:'В работе', tab_resolved:'Решённые',
      lbl_n_alerts:'оповещений',
      create_task:'Создать задачу', analyze_reason:'Анализ причины',
      lbl_biz_impact:'Бизнес-эффект', lbl_responsible:'Ответственный',
      lbl_metric:'Метрика', lbl_region:'Регион',
      deviation_timeline:'Временная шкала отклонений',
      root_cause_preview:'Предварительный анализ причин',
      root_cause_cta:'Запустите факторный анализ для декомпозиции вкладов каждого драйвера и получения рекомендаций.',
      task_title_lbl:'Название задачи',
      lbl_assignee:'Исполнитель', lbl_priority:'Приоритет', lbl_due_date:'Срок', lbl_notes:'Заметки',
      investigate_prefix:'Расследовать:',
      default_notes:'Расследовать отклонение и предложить корректирующие меры.',
      task_created:'Задача создана и назначена',
      // metrics
      metrics_sub_1:'управляемых показателей · единый источник истины',
      btn_new_metric:'Новая метрика',
      search_metrics:'Поиск метрик…',
      more_filters:'Ещё фильтры',
      trust_score:'Уровень доверия',
      high_confidence:'Высокая достоверность · подтверждённая родословная',
      review_recommended:'Рекомендуется проверка',
      lbl_definition:'Определение', lbl_formula:'Формула',
      lbl_data_owner:'Владелец данных', lbl_source_system:'Система-источник',
      lbl_update_freq:'Частота обновления', lbl_department:'Отдел',
      use_in_dashboard:'В дашборд', add_to_builder:'Добавить в конструктор',
      ask_ai_metric:'Спросить ИИ об этой метрике',
      metric_draft_created:'Черновик метрики создан',
      metric_added_widget:'Метрика добавлена в конструктор',
      // factor
      factor_sub:'Декомпозиция первопричин · ИИ-помощь',
      mgmt_summary:'Резюме для руководства',
      export_to_report:'Экспорт в отчёт',
      sel_problem:'Выбранная проблема',
      lbl_deviation:'Отклонение', lbl_impact:'Эффект',
      contribution_ranking:'Рейтинг вкладов',
      segment_comparison:'Сравнение сегментов',
      ai_explanation:'Объяснение ИИ',
      ai_explanation_text:'Снижение трафика и дефицит товаров вместе объясняют 65% разрыва в Фергане. Спад ускорился после рекламной кампании конкурента 14 апреля.',
      recommended_actions:'Рекомендуемые действия',
      factor_action1:'Пополнить топ-5 SKU в 3 флагманских филиалах в течение 48 ч',
      factor_action2:'Запустить контракцию в Ферганской долине',
      factor_action3:'Добавить 2 сотрудника в часы пик на 2 недели',
      mgmt_summary_sub:'Создано ИИ · падение продаж в Фергане',
      mgmt_summary_badge:'Создано за 1,4 сек',
      mgmt_summary_text:'Выручка Ферганы на 18% ниже плана (−13,5 млрд UZS в квартале). Декомпозиция показывает: 65% разрыва — снижение трафика (−22%) и дефицит товаров в 3 флагманских филиалах, усиленные кампанией конкурента с 14 апреля.',
      mgmt_rec_title:'Рекомендуемые решения',
      mgmt_rec1:'Экстренное пополнение SKU (48 ч)',
      mgmt_rec2:'Утверждение бюджета на контракцию в Фергане',
      mgmt_rec3:'Временное усиление персонала',
      mgmt_recovery:'Ожидаемое восстановление: ~9–11 млрд UZS за два месяца при принятии мер на этой неделе.',
      problem_title:'Продажи упали в Фергане',
      added_to_report:'Добавлено в конструктор отчётов',
      // library
      btn_new_dashboard:'Новый дашборд',
      share_dashboard:'Поделиться дашбордом',
      invite_people:'Пригласить',
      access_level:'Уровень доступа',
      can_view:'Только просмотр', can_edit:'Редактирование', full_access:'Полный доступ',
      people_access:'Пользователи с доступом',
      tbl_dashboard:'Дашборд', tbl_owner:'Владелец', tbl_access:'Доступ',
      tbl_widgets:'Виджеты', tbl_updated:'Обновлено',
      menu_open:'Открыть', menu_duplicate:'Дублировать', menu_share:'Поделиться', menu_export_pdf:'Экспорт PDF',
      link_copied:'Ссылка скопирована',
      dashboard_shared:'Дашборд опубликован',
      dashboard_duplicated:'Дашборд дублирован',
      // widget
      widget_sub:'Конструктор виджетов без кода · настройка без перетаскивания',
      lbl_data_source:'Источник данных', lbl_dimension:'Измерение', lbl_chart_type:'Тип графика',
      lbl_filters:'Фильтры', add_filter:'Добавить фильтр',
      ai_suggestion:'Предложение ИИ', save_widget:'Сохранить виджет',
      preview_label:'Предпросмотр', live_hourly:'В прямом эфире · ежечасно',
      ai_recommends_bar:'ИИ рекомендует столбчатый для этих данных',
      widget_saved:'Виджет сохранён в дашборд',
      ai_suggested:'ИИ предложил: столбчатый по регионам',
      by_label:'по',
      // templates
      templates_sub:'Готовые KPI, дашборды и оповещения — адаптированы для Узбекистана',
      rec_kpis:'Рекомендуемые KPI',
      req_sources:'Необходимые источники',
      example_alerts:'Примеры оповещений',
      use_template:'Использовать шаблон',
      rec_config:'Рекомендуемая конфигурация',
      template_created:'дашборд создан',
      // reports
      reports_sub:'Автоматическая отчётность с AI-резюме',
      btn_new_report:'Новый отчёт',
      new_report_opened:'Открыт конструктор отчётов',
      btn_generate:'Сформировать', btn_schedule_report:'Расписание',
      generating_prefix:'Формирование',
      agg_metrics:'Агрегация метрик',
      detecting_devs:'Обнаружение отклонений',
      writing_summary:'Написание AI-резюме',
      report_preview:'Предпросмотр отчёта',
      ai_summary_incl:'AI-резюме включено',
      exec_summary:'Краткое резюме',
      exec_summary_text:'Выручка достигла 568 млрд UZS (+6,8% MoM), план выполнен на 101,4%. Чистая прибыль выросла на 4,2%. Главный риск — Фергана (−18%); 7 оповещений активны, 1 критическое не решено.',
      export_pdf:'Экспорт PDF',
      schedule_delivery:'Настроить доставку',
      lbl_frequency:'Периодичность', lbl_day:'День', lbl_time_field:'Время',
      lbl_recipients_field:'Получатели',
      sched_note:'Доставляется в формате PDF с AI-резюме каждый понедельник в 08:00.',
      report_exported:'Отчёт экспортирован как PDF',
      email_scheduled:'Доставка по email настроена',
      // connectors
      btn_add_connector:'Добавить коннектор',
      status_connected:'Подключено', status_syncing:'Синхронизация',
      status_idle:'Неактивно', status_errors:'Ошибки',
      lbl_last_sync:'Последняя синхр.', lbl_volume:'Объём', lbl_security:'Безопасность',
      btn_sync_now:'Синхронизировать', syncing_label:'Синхронизация…',
      connect_prefix:'Подключить',
      step_credentials:'Учётные данные', step_tables:'Таблицы', step_permissions:'Разрешения',
      step_schedule:'Расписание', step_test:'Тест', step_label:'Шаг',
      lbl_host:'Хост', lbl_port:'Порт', lbl_database:'База данных',
      lbl_username:'Имя пользователя', lbl_password:'Пароль',
      select_tables:'Выберите таблицы для синхронизации',
      rls_title:'Безопасность на уровне строк',
      apply_regional:'Применить региональные ограничения данных',
      lbl_access_role:'Роль доступа',
      analytics_read:'Аналитика (только чтение)', admin_full:'Администратор (полный)',
      sync_freq:'Частота синхронизации',
      conn_success:'Подключение успешно',
      conn_tested:'Проверено за 0,4 сек · 3 таблицы · 1,2 млн строк готовы к синхронизации',
      conn_configured:'Коннектор настроен и подключён',
      sync_completed:'Синхронизация завершена',
      incremental_note:'Инкрементальная синхронизация каждый час, полное обновление ночью в 02:00.',
      // documents
      docs_sub:'ИИ-обработка документов · резюмирование, запросы, извлечение данных',
      mode_summary:'Резюмировать', mode_ask:'Спросить', mode_extract:'Извлечь', mode_brief:'Конспект',
      reading_doc:'Читаю документ…',
      ai_summary_label:'AI-резюме',
      ai_summary_doc_text:'Этот отчёт охватывает результаты 2-го квартала. Выручка выше плана, но Ферганский регион отстаёт на 18%. Рекомендуется экстренное пополнение товаров и региональная акция. Стоимость риска растёт и требует мониторинга.',
      meeting_brief:'Конспект встречи',
      add_to_catalog:'Добавить в каталог метрик',
      metrics_suggested:'Метрики предложены для каталога',
      upload_opened:'Открыт диалог загрузки',
      brief_item1:'Выручка +6,8%, выше плана',
      brief_item2:'Фергана −18% — нужно решение по плану восстановления',
      brief_item3:'Утвердить бюджет на экстренное пополнение SKU',
      brief_item4:'Контролировать рост стоимости риска',
      // admin
      btn_add_user:'Добавить пользователя',
      on_premise:'Развёртывание on-premise',
      on_premise_desc:'Размещение на серверах клиента · опция air-gap доступна',
      data_residency:'Хранение данных: Узбекистан',
      data_residency_desc:'Все данные хранятся в пределах страны · compliant',
      tab_users:'Пользователи', tab_roles:'Роли', tab_access_matrix:'Матрица доступа', tab_workflow:'Рабочий процесс',
      tbl_user:'Пользователь', tbl_role:'Роль', tbl_dept:'Отдел', tbl_mfa:'МФА', tbl_status:'Статус',
      mfa_on:'Вкл', mfa_off:'Выкл', lbl_n_users:'пользователей',
      add_user_title:'Добавить пользователя', add_user_sub:'Пригласить участника команды',
      lbl_full_name:'Полное имя', lbl_email:'Email',
      lbl_role_label:'Роль', lbl_dept_label:'Отдел',
      require_mfa:'Требовать многофакторную аутентификацию',
      send_invite:'Отправить приглашение', invite_sent:'Приглашение отправлено',
      approver_label:'Согласующий:',
      workflow_active:'Активно',
      // audit
      audit_sub:'Неизменяемый журнал всей активности платформы',
      tbl_event:'Событие', tbl_user_col:'Пользователь', tbl_target:'Объект', tbl_ip:'IP', tbl_time:'Время',
      // settings
      settings_sub:'Настройте рабочее пространство',
      tab_company:'Компания', tab_appearance:'Внешний вид', tab_notifications:'Уведомления',
      tab_ai_asst:'ИИ-помощник', tab_data:'Данные', tab_security_tab:'Безопасность',
      company_profile:'Профиль компании',
      lbl_company_name:'Название компании', lbl_industry:'Отрасль',
      lbl_country:'Страна', lbl_currency:'Базовая валюта', lbl_fiscal:'Начало финансового года',
      appearance_title:'Внешний вид',
      lbl_theme:'Тема', theme_dark:'Тёмная', theme_light:'Светлая', lbl_language:'Язык',
      notif_title:'Уведомления',
      notif_alerts_lbl:'Критические оповещения', notif_alerts_desc:'Мгновенный push + email',
      notif_reports_lbl:'Плановые отчёты', notif_reports_desc:'При доставке отчёта',
      notif_weekly_lbl:'Еженедельный дайджест', notif_weekly_desc:'Сводка в понедельник утром',
      ai_asst_title:'ИИ-помощник',
      lbl_response_style:'Стиль ответа',
      style_concise:'Кратко', style_balanced:'Сбалансированно', style_detailed:'Подробно',
      voice_input:'Голосовой ввод', voice_input_desc:'Включить микрофон для вопросов',
      proactive_insights:'Проактивные инсайты', proactive_insights_desc:'Автоматически выявлять аномалии',
      lbl_data_scope:'Область данных',
      scope_company:'По всей компании (с учётом прав)', scope_dept:'Только мой отдел',
      data_refresh_title:'Обновление данных',
      lbl_refresh:'Интервал обновления по умолчанию',
      lbl_cache:'Продолжительность кеша',
      cache_5m:'5 минут', cache_15m:'15 минут', cache_1h:'1 час',
      lower_intervals_note:'Меньшие интервалы увеличивают нагрузку на источники данных.',
      security_title:'Безопасность',
      sso_label:'Единый вход (SSO)', sso_desc:'SAML 2.0 / OIDC',
      masking_label:'Маскирование данных', masking_desc:'Скрывать чувствительные поля для не-администраторов',
      session_timeout:'Тайм-аут сессии',
      timeout_30m:'30 минут', timeout_1h:'1 час', timeout_8h:'8 часов',
      settings_saved:'Настройки сохранены',
      // notifications panel
      notif_header:'Уведомления', notif_n_new:'новых',
      notif1_title:'Продажи в Фергане упали на 18%',
      notif2_title:'Еженедельное резюме CEO готово',
      notif3_title:'Синхронизация CRM не удалась',
      notif4_title:'Banking Core синхронизирован',
      // profile menu
      profile_sign_out:'Выйти и сменить роль',
      profile_admin_access:'Администрирование',
      // mobile
      mobile_greeting:'Доброе утро,',
      company_overview:'Обзор компании',
      ai_brief:'AI-инфо',
      ai_brief_text:'Выручка 568 млрд UZS (+6,8%), план выполнен на 101,4%. Фергана −18% — главный риск этой недели.',
      mobile_ask_ai:'Задать вопрос ИИ',
      mobile_home:'Главная', mobile_ai_label:'ИИ', mobile_alerts_label:'Оповещения',
      mobile_boards:'Дашборды', mobile_data_label:'Данные',
      close_preview:'Закрыть',
      mobile_preview_label:'Мобильный предпросмотр · адаптивный макет',
      // ai screen
      ai_screen_sub:'Задавайте бизнес-вопросы на естественном языке — GenBI строит графики, инсайты и действия.',
      new_chat:'Новый чат',
      // coming soon
      coming_soon_sub:'Этот экран собирается.',
      detection_rules_opened:'Открыты правила обнаружения',
    },

    uz: {
      // nav
      nav_dashboard:'Rahbar paneli', nav_ai:'AI tahlilchi', nav_metrics:'Metrikalar katalogi',
      nav_library:'Dashboard kutubxonasi', nav_widget:'Vidjet konstruktori', nav_alerts:'Ogohlantirishlar',
      nav_factor:'Omil tahlili', nav_docs:'Hujjatlar kutubxonasi', nav_connectors:'Maʼlumot manbalari',
      nav_templates:'Soha shablonlari', nav_reports:'Hisobotlar', nav_admin:'Boshqaruv va kirish',
      nav_audit:'Audit jurnali', nav_settings:'Sozlamalar',
      search:'Metrikalar, dashboardlar, hujjatlarni qidirish…', ask_ai:'AI dan soʻrash', enter_demo:'Demoga kirish',
      grp_analyze:'Tahlil', grp_build:'Yaratish', grp_govern:'Boshqaruv',
      // common
      close:'Yopish', cancel:'Bekor qilish', save:'Saqlash', reset:'Tiklash', details:'Tafsilotlar',
      view_all:'Barchasini koʻrish', export:'Eksport', open:'Ochish', share:'Ulashish', copy:'Nusxa',
      duplicate:'Nusxa olish', assign:'Tayinlash', generate:'Yaratish', finish:'Tugatish',
      continue_:'Davom etish', back:'Orqaga', save_changes:'Oʻzgarishlarni saqlash', upload:'Yuklash',
      // login
      login_title:'Demoga kirish',
      login_sub:'Shaxsiylashtirilgan tajriba uchun rol tanlang.',
      login_lang_label:'Til',
      login_enter_as:'Kirish:',
      login_note:'Demo muhit · sinov maʼlumotlari · autentifikatsiz',
      login_brand_tag:'AI-asosli biznes tahlili',
      login_hero1:'Qarorlar,',
      login_hero2:'ishonchli maʼlumotlar bilan.',
      login_hero_desc:'Barcha manbalarni ulang, oddiy tilda savol bering, zarardan oldin ogʻishlarni aniqlang va direktorlar kengashi uchun hisobotni soniyalar ichida tayyor qiling — Oʻzbekiston banklari, savdo, fintech va davlat tashkilotlari uchun yaratilgan.',
      login_stat_connectors:'Maʼlumot konnektorlari',
      login_stat_templates:'Soha shablonlari',
      login_stat_ai:'AI javoblari',
      login_onprem:'On-premise tayyor',
      login_residency:'Maʼlumotlar OʻZ\'da',
      login_audit_trail:'Toʻliq audit treyli',
      role_ceo_desc:'Rais / Yuqori boshqaruvchi',
      role_analyst_desc:'Biznes va maʼlumot tahlilchisi',
      role_dhead_desc:'Mintaqaviy va moliyaviy rahbar',
      role_dadmin_desc:'IT va platforma admini',
      // dashboard
      dash_sub:'Kompaniya koʻrsatkichlari · 12 daqiqa oldin yangilandi',
      dash_welcome:'Xush kelibsiz,',
      dash_period_changed:'Davr oʻzgartirildi',
      dash_exported:'Dashboard eksport qilindi',
      dash_layout_saved:'Dashboard tartibi saqlandi',
      btn_export:'Eksport', btn_customize:'Sozlash', btn_ask_ai:'AI\'dan soʻrash',
      dash_rev_trend:'Daromad trendi',
      dash_rev_sub:'Haqiqiy va reja · mlrd UZS · 12 oy',
      legend_actual:'Haqiqiy', legend_plan:'Reja',
      ai_insights:'AI tavsiyalari',
      lbl_new:'yangi',
      regional_perf:'Mintaqaviy koʻrsatkichlar',
      plan_vs_fact:'Reja va Haqiqiy',
      pvf_sub:'Mahsulot boʻyicha · mlrd UZS',
      op_efficiency:'Operatsion samaradorlik',
      eff_target:'90% maqsadga nisbatan',
      label_conv:'Konversiya', label_alerts:'Ogohlantirishlar',
      prod_perf:'Mahsulot / kategoriya koʻrsatkichlari',
      open_report:'Hisobotni ochish',
      tbl_product:'Mahsulot liniyasi', tbl_revenue:'Daromad', tbl_plan:'Reja',
      tbl_vs_plan:'Rejaga nisbatan', tbl_growth:'Oʻsish',
      active_alerts_title:'Faol ogohlantirishlar',
      drill_sub:'Batafsil maʼlumot · sinov maʼlumotlari',
      this_period:'Joriy davr', last_period:'Oʻtgan davr',
      forecast:'Prognoz', trend_breakdown:'Trend tahlili',
      ai_interpretation:'AI talqini',
      ai_drill_text:'Reja 1,4% ortiqcha bajarilmoqda, mobil oʻtkazmalar va karta chiqarish hisobiga. Fargʻona eng katta zararli yer; tiklanish ~13,5 mlrd UZS qoʻshadi.',
      ask_ai_this:'Bu haqda AIʼdan soʻrash',
      customize_title:'Dashboardni sozlash',
      customize_sub:'KPI kartochkalar va vidjetlarni yoqing/oʻchiring',
      lbl_kpi_cards:'KPI kartochkalar',
      save_layout:'Tartibni saqlash',
      lbl_filtered:'Filtr:',
      // kpi labels
      kpi_revenue:'Daromad', kpi_profit:'Sof foyda', kpi_volume:'Savdo hajmi',
      kpi_plan:'Reja va Haqiqiy', kpi_conv:'Konversiya', kpi_growth:'Mijozlar oʻsishi',
      kpi_risk:'Xavf ogohlantirishlari', kpi_eff:'Oper. samaradorlik',
      // alerts
      alerts_sub:'Barcha metrikalar boʻyicha avtomatik ogʻishlarni aniqlash',
      detection_rules:'Aniqlash qoidalari',
      high_sev_open:'Yuqori jiddiylikdagi ochiq',
      total_open:'Jami ochiq',
      est_impact:'Taxminiy biznes taʼsiri',
      tab_all:'Barchasi', tab_new:'Yangi', tab_inprogress:'Jarayonda', tab_resolved:'Hal etilgan',
      lbl_n_alerts:'ogohlantirish',
      create_task:'Vazifa yaratish', analyze_reason:'Sababni tahlil qilish',
      lbl_biz_impact:'Biznes taʼsiri', lbl_responsible:'Masʼul',
      lbl_metric:'Metrika', lbl_region:'Mintaqa',
      deviation_timeline:'Ogʻish vaqt jadvali',
      root_cause_preview:'Asosiy sabab koʻrinishi',
      root_cause_cta:'Har bir drayverni hissa tahlili uchun omil tahlilini ishga tushiring va tavsiyalangan harakatlarni oling.',
      task_title_lbl:'Vazifa nomi',
      lbl_assignee:'Ijrochi', lbl_priority:'Muhimlik', lbl_due_date:'Muddat', lbl_notes:'Eslatmalar',
      investigate_prefix:'Tekshirish:',
      default_notes:'Ogʻishni tekshiring va tuzatuvchi choralarni taklif qiling.',
      task_created:'Vazifa yaratildi va tayinlandi',
      // metrics
      metrics_sub_1:'boshqariladigan koʻrsatkich · yagona haqiqat manbai',
      btn_new_metric:'Yangi metrika',
      search_metrics:'Metrikalarni qidirish…',
      more_filters:'Koʻproq filtrlar',
      trust_score:'Ishonch darajasi',
      high_confidence:'Yuqori ishonch · tasdiqlangan manba',
      review_recommended:'Koʻrib chiqish tavsiya etiladi',
      lbl_definition:'Taʼrif', lbl_formula:'Formula',
      lbl_data_owner:'Maʼlumot egasi', lbl_source_system:'Manba tizim',
      lbl_update_freq:'Yangilanish chastotasi', lbl_department:'Boʻlim',
      use_in_dashboard:'Dashboardga qoʻshish', add_to_builder:'Konstruktorga qoʻshish',
      ask_ai_metric:'Bu metrika haqda AIʼdan soʻrash',
      metric_draft_created:'Yangi metrika qoʻlyozmasi yaratildi',
      metric_added_widget:'Metrika vidjet konstruktoriga qoʻshildi',
      // factor
      factor_sub:'Asosiy sabablar tahlili · AI yordamida',
      mgmt_summary:'Rahbariyat xulosasi',
      export_to_report:'Hisobotga eksport',
      sel_problem:'Tanlangan muammo',
      lbl_deviation:'Ogʻish', lbl_impact:'Taʼsir',
      contribution_ranking:'Hissa reytingi',
      segment_comparison:'Segmentlar taqqoslamasi',
      ai_explanation:'AI tushuntirishi',
      ai_explanation_text:'Trafik kamayishi va tovar yetishmasligi birgalikda Fargʻona boʻshligʻining 65%ni tushuntiradi. Pasayish 14-aprelda raqib kampaniyasidan keyin tezlashdi.',
      recommended_actions:'Tavsiya etilgan chora-tadbirlar',
      factor_action1:'48 soat ichida 3 flagman filialida top-5 SKUni toʻldirish',
      factor_action2:'Fargʻona vodiysida qarshi-aksiya ishga tushirish',
      factor_action3:'2 hafta davomida band soatlarda 2 ta qoʻshimcha xodim',
      mgmt_summary_sub:'AI tomonidan yaratilgan · Fargʻona savdo pasayishi',
      mgmt_summary_badge:'1,4 sekundda yaratildi',
      mgmt_summary_text:'Fargʻona daromadi rejadan 18% past (−13,5 mlrd UZS kvartalda). Tahlil: boʻshliqqning 65% — trafik kamayishi (−22%) va 3 flagman filialidagi tovar yetishmasligi, 14-aprel raqib kampaniyasi bilan kuchaytirilgan.',
      mgmt_rec_title:'Tavsiya etilgan qarorlar',
      mgmt_rec1:'Favqulodda SKU toʻldirish (48 soat)',
      mgmt_rec2:'Fargʻona qarshi-aksiya byudjetini tasdiqlash',
      mgmt_rec3:'Vaqtinchalik xodimlarni mustahkamlash',
      mgmt_recovery:'Kutilayotgan tiklanish: bu hafta chora koʻrilsa ikki oyda ~9–11 mlrd UZS.',
      problem_title:'Fargʻonada savdo tushdi',
      added_to_report:'Hisobot konstruktoriga qoʻshildi',
      // library
      btn_new_dashboard:'Yangi dashboard',
      share_dashboard:'Dashboardni ulashish',
      invite_people:'Odamlarni taklif qilish',
      access_level:'Kirish darajasi',
      can_view:'Koʻrish mumkin', can_edit:'Tahrirlash mumkin', full_access:'Toʻliq kirish',
      people_access:'Kirish huquqiga ega foydalanuvchilar',
      tbl_dashboard:'Dashboard', tbl_owner:'Egasi', tbl_access:'Kirish',
      tbl_widgets:'Vidjetlar', tbl_updated:'Yangilangan',
      menu_open:'Ochish', menu_duplicate:'Nusxa olish', menu_share:'Ulashish', menu_export_pdf:'PDF eksport',
      link_copied:'Havola nusxalandi',
      dashboard_shared:'Dashboard ulashildi',
      dashboard_duplicated:'Dashboard nusxalandi',
      // widget
      widget_sub:'Kodsiz vidjet konstruktori · oson sozlash',
      lbl_data_source:'Maʼlumot manbai', lbl_dimension:'Oʻlchov', lbl_chart_type:'Grafik turi',
      lbl_filters:'Filtrlar', add_filter:'Filtr qoʻshish',
      ai_suggestion:'AI taklifi', save_widget:'Vidjetni saqlash',
      preview_label:'Koʻrinish', live_hourly:'Jonli · soatlik',
      ai_recommends_bar:'Bu maʼlumotlar uchun AI ustunli grafik tavsiya qiladi',
      widget_saved:'Vidjet dashboardga saqlandi',
      ai_suggested:'AI taklif qildi: mintaqa boʻyicha ustunli grafik',
      by_label:'boʻyicha',
      // templates
      templates_sub:'Oldindan tayyorlangan KPI, dashboard va ogohlantirishlar — Oʻzbekiston uchun',
      rec_kpis:'Tavsiya etilgan KPIlar',
      req_sources:'Zarur manbalar',
      example_alerts:'Namunaviy ogohlantirishlar',
      use_template:'Shablonni ishlatish',
      rec_config:'Tavsiya etilgan sozlama',
      template_created:'dashboard yaratildi',
      // reports
      reports_sub:'AI xulosalari bilan avtomatik hisobotlar',
      btn_new_report:'Yangi hisobot',
      new_report_opened:'Yangi hisobot konstruktori ochildi',
      btn_generate:'Yaratish', btn_schedule_report:'Jadvallash',
      generating_prefix:'Yaratilmoqda',
      agg_metrics:'Metrikalar jamlash',
      detecting_devs:'Ogʻishlarni aniqlash',
      writing_summary:'AI xulosasi yozilmoqda',
      report_preview:'Hisobot koʻrinishi',
      ai_summary_incl:'AI xulosasi kiritilgan',
      exec_summary:'Qisqacha xulosa',
      exec_summary_text:'Daromad 568 mlrd UZS (+6,8% oyga nisbatan), reja 101,4% bajarildi. Sof foyda 4,2% oʻsdi. Asosiy xavf — Fargʻona (−18%); 7 ogohlantirish faol, 1 jiddiy hal etilmagan.',
      export_pdf:'PDF eksport',
      schedule_delivery:'Yetkazib berishni jadvallashtirish',
      lbl_frequency:'Chastota', lbl_day:'Kun', lbl_time_field:'Vaqt',
      lbl_recipients_field:'Qabul qiluvchilar',
      sched_note:'Har dushanba soat 08:00 da AI xulosasi bilan PDF sifatida yetkaziladi.',
      report_exported:'Hisobot PDF sifatida eksport qilindi',
      email_scheduled:'Email yetkazish jadvalga qoʻshildi',
      // connectors
      btn_add_connector:'Konnektör qoʻshish',
      status_connected:'Ulangan', status_syncing:'Sinxronlanmoqda',
      status_idle:'Faolsiz', status_errors:'Xatolar',
      lbl_last_sync:'Oxirgi sinxron.', lbl_volume:'Hajm', lbl_security:'Xavfsizlik',
      btn_sync_now:'Sinxronlash', syncing_label:'Sinxronlanmoqda…',
      connect_prefix:'Ulash',
      step_credentials:'Hisob maʼlumotlari', step_tables:'Jadvallar', step_permissions:'Ruxsatlar',
      step_schedule:'Jadval', step_test:'Test', step_label:'Qadam',
      lbl_host:'Host', lbl_port:'Port', lbl_database:'Maʼlumotlar bazasi',
      lbl_username:'Foydalanuvchi nomi', lbl_password:'Parol',
      select_tables:'Sinxronlash uchun jadvallarni tanlang',
      rls_title:'Qator darajasida xavfsizlik',
      apply_regional:'Mintaqaviy maʼlumot cheklovlarini qoʻllash',
      lbl_access_role:'Kirish roli',
      analytics_read:'Tahlil (faqat oʻqish)', admin_full:'Admin (toʻliq)',
      sync_freq:'Sinxronlash chastotasi',
      conn_success:'Ulanish muvaffaqiyatli',
      conn_tested:'0,4 sekundda sinab koʻrildi · 3 jadval · 1,2M qator tayyor',
      conn_configured:'Konnektör sozlandi va ulandi',
      sync_completed:'Sinxronlash yakunlandi',
      incremental_note:'Har soatda inkremental sinxronlash, tunda soat 02:00 da toʻliq yangilash.',
      // documents
      docs_sub:'AI hujjat tahlili · xulosa, soʻrov, maʼlumot chiqarish',
      mode_summary:'Xulosa', mode_ask:'Soʻrash', mode_extract:'Chiqarish', mode_brief:'Konspekt',
      reading_doc:'Hujjat oʻqilmoqda…',
      ai_summary_label:'AI xulosasi',
      ai_summary_doc_text:'Ushbu hisobot 2-kvartal natijalarini qamrab oladi. Daromad rejadan yuqori, lekin Fargʻona mintaqasi 18% orqada. Favqulodda tovar toʻldirish va mintaqaviy aksiya tavsiya etiladi. Xavf narxi oshmoqda va kuzatuvni talab qiladi.',
      meeting_brief:'Uchrashuv konspekti',
      add_to_catalog:'Metrikalar katalogiga qoʻshish',
      metrics_suggested:'Metrikalar katalog uchun taklif qilindi',
      upload_opened:'Yuklash oynasi ochildi',
      brief_item1:'Daromad +6,8%, rejadan yuqori',
      brief_item2:'Fargʻona −18% — tiklanish rejasi kerak',
      brief_item3:'Favqulodda SKU toʻldirish byudjetini tasdiqlash',
      brief_item4:'Xavf narxining oshishini kuzatish',
      // admin
      btn_add_user:'Foydalanuvchi qoʻshish',
      on_premise:'On-premise joylashtirish',
      on_premise_desc:'Mijoz serverida joylashtirilgan · air-gap varianti mavjud',
      data_residency:'Maʼlumotlar: Oʻzbekiston',
      data_residency_desc:'Barcha maʼlumotlar milliy chegaralar ichida · muvofiq',
      tab_users:'Foydalanuvchilar', tab_roles:'Rollar', tab_access_matrix:'Kirish matritsasi', tab_workflow:'Ish jarayoni',
      tbl_user:'Foydalanuvchi', tbl_role:'Rol', tbl_dept:'Boʻlim', tbl_mfa:'MFA', tbl_status:'Holat',
      mfa_on:'Yoniq', mfa_off:'Oʻchiq', lbl_n_users:'foydalanuvchi',
      add_user_title:'Foydalanuvchi qoʻshish', add_user_sub:'Jamoa aʼzosini taklif qilish',
      lbl_full_name:'Toʻliq ism', lbl_email:'Email',
      lbl_role_label:'Rol', lbl_dept_label:'Boʻlim',
      require_mfa:'Koʻp faktorli autentifikatsiyani talab qilish',
      send_invite:'Taklif yuborish', invite_sent:'Taklif yuborildi',
      approver_label:'Tasdiqluvchi:',
      workflow_active:'Faol',
      // audit
      audit_sub:'Platforma barcha faoliyatining oʻzgarmas jurnali',
      tbl_event:'Hodisa', tbl_user_col:'Foydalanuvchi', tbl_target:'Obʼyekt', tbl_ip:'IP', tbl_time:'Vaqt',
      // settings
      settings_sub:'Ish muhitingizni sozlang',
      tab_company:'Kompaniya', tab_appearance:'Koʻrinish', tab_notifications:'Bildirishnomalar',
      tab_ai_asst:'AI yordamchi', tab_data:'Maʼlumotlar', tab_security_tab:'Xavfsizlik',
      company_profile:'Kompaniya profili',
      lbl_company_name:'Kompaniya nomi', lbl_industry:'Soha',
      lbl_country:'Mamlakat', lbl_currency:'Asosiy valyuta', lbl_fiscal:'Moliya yili boshlanishi',
      appearance_title:'Koʻrinish',
      lbl_theme:'Mavzu', theme_dark:'Qorongʻu', theme_light:'Yorugʻ', lbl_language:'Til',
      notif_title:'Bildirishnomalar',
      notif_alerts_lbl:'Yuqori jiddiylikdagi ogohlantirishlar', notif_alerts_desc:'Tezkor push + email',
      notif_reports_lbl:'Rejalashtirilgan hisobotlar', notif_reports_desc:'Hisobot yetkazilganda',
      notif_weekly_lbl:'Haftalik xulosa', notif_weekly_desc:'Dushanba ertalab xulosa',
      ai_asst_title:'AI yordamchi',
      lbl_response_style:'Javob uslubi',
      style_concise:'Qisqa', style_balanced:'Muvozanatli', style_detailed:'Batafsil',
      voice_input:'Ovozli kiritish', voice_input_desc:'Savollar uchun mikrofonni yoqing',
      proactive_insights:'Proaktiv tavsiyalar', proactive_insights_desc:'Anomaliyalarni avtomatik aniqlash',
      lbl_data_scope:'Maʼlumotlar doirasi',
      scope_company:'Kompaniya boʻylab (ruxsatlar bilan)', scope_dept:'Faqat mening boʻlimim',
      data_refresh_title:'Maʼlumotlarni yangilash',
      lbl_refresh:'Standart yangilanish oraligʻi',
      lbl_cache:'Kesh davomiyligi',
      cache_5m:'5 daqiqa', cache_15m:'15 daqiqa', cache_1h:'1 soat',
      lower_intervals_note:'Qisqa oraliqlar manba tizimlarga yuklama oshiradi.',
      security_title:'Xavfsizlik',
      sso_label:'Yagona kirish (SSO)', sso_desc:'SAML 2.0 / OIDC',
      masking_label:'Maʼlumotlarni yashirish', masking_desc:'Adminlar boʻlmaganlar uchun maxfiy maydonlarni yashirish',
      session_timeout:'Sessiya muddati',
      timeout_30m:'30 daqiqa', timeout_1h:'1 soat', timeout_8h:'8 soat',
      settings_saved:'Sozlamalar saqlandi',
      // notifications panel
      notif_header:'Bildirishnomalar', notif_n_new:'yangi',
      notif1_title:'Fargʻonada savdo 18% tushdi',
      notif2_title:'Haftalik CEO xulosasi tayyor',
      notif3_title:'CRM sinxronizatsiyasi muvaffaqiyatsiz',
      notif4_title:'Banking Core sinxronlandi',
      // profile menu
      profile_sign_out:'Chiqish va rolni oʻzgartirish',
      profile_admin_access:'Boshqaruv va kirish',
      // mobile
      mobile_greeting:'Xayrli tong,',
      company_overview:'Kompaniya koʻrinishi',
      ai_brief:'AI xulosa',
      ai_brief_text:'Daromad 568 mlrd UZS (+6,8%), reja 101,4% bajarildi. Fargʻona −18% bu haftaning asosiy xavfi.',
      mobile_ask_ai:'AIʼga savol bering',
      mobile_home:'Bosh', mobile_ai_label:'AI', mobile_alerts_label:'Ogohlantirishlar',
      mobile_boards:'Boardlar', mobile_data_label:'Maʼlumotlar',
      close_preview:'Yopish',
      mobile_preview_label:'Mobil koʻrinish · moslashuvchan tartib',
      // ai screen
      ai_screen_sub:'Biznes savollarini oddiy tilda bering — GenBI grafiklar, tavsiyalar va harakatlar yaratadi.',
      new_chat:'Yangi suhbat',
      // coming soon
      coming_soon_sub:'Bu ekran tayyorlanmoqda.',
      detection_rules_opened:'Aniqlash qoidalari ochildi',
    },
  };
  window.I18N = I18N;
})();
